services:
  postgres:
    image: postgres:18
    volumes:
      - db_postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=open-schedule
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d open-schedule" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"

  app-open-schedule:
    image: alphnology/open-schedule:latest
    ports:
      - "51675:51675"
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=open-schedule
      - EVENT_WEBSITE=https://alphnology.com/
    volumes:
      - ./assets:/assets
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_postgres: