logging:
  level:
    org:
      atmosphere: warn

server:
  port: ${PORT:51675}


vaadin:
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,com.alphnology,com.github.appreciated.apexcharts
  # Launch the default browser when starting the application in development mode
  launch-browser: true
  pnpm:
    enable: true
#  frontend:
#    hotdeploy=true:

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

spring:
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: [ classpath:db/migration/prod ] #, filesystem:./sql
    placeholderReplacement: false
  jpa:
    show-sql: false

  mustache:
    check-template-location: false

  # MySQL configuration.
  datasource:
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:open-schedule}
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    enabled: true

event:
  website: ${EVENT_WEBSITE:https://alphnology.com}
  schedule: ${EVENT_SCHEDULE:https://alphnology.com}
#Varaible Formatter.
application:
  url: ${APP_URL:https://alphnology.com}
  name: ${APP_NAME:@project.description@}
  version: @project.version@


  formatter:
    date: ${FORMATTER_DATE:MM-dd-yyyy}
    time: ${FORMATTER_TIME:HH:mm}
    time-12: ${FORMATTER_TIME_12:hh:mm a}
    datetime: ${FORMATTER_DATE_TIME:MM-dd-yyyy HH:mm}
    date-time-12: ${FORMATTER_DATE_TIME_12:MM-dd-yyyy hh:mm a}
    decimal: ${FORMATTER_DECIMAL:#,##0.00}

  notification:
    time: ${NOTIFICATION_TIME:3000}

  pattern:
    password: '^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%&*()_+.]).{5,}$'
    email: '^[\w-\.]+@([\w-]+\.)+[\w-]{2,}$'

  email:
    from:
      address: ${EMAIL_FROM_ADDRESS:#{null}}
      name: ${EMAIL_FROM_NAME:#{null}}
    smtp:
      enabled: true
      host: ${EMAIL_SMTP_HOST:}
      port: ${EMAIL_SMTP_PORT:587}
      username: ${EMAIL_SMTP_USERNAME:}
      password: ${EMAIL_SMTP_PASSWORD:}


github:
  api:
    token: ${GIT_HUB_API_TOKEN:ghp_YourSecretTokenHere}
  repository:
    name: ${GIT_HUB_REPOSITORY_NAME:alphnology/open-schedule}
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: true
    locations: [ classpath:db/migration/prod, classpath:db/migration/dev ] #, filesystem:./sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  devtools:
    restart:
      enabled: true  # Set to enable hot deployment
      additional-paths: src/main/java # restart directory
      quiet-period: 1s
      poll-interval: 2s
      log-condition-evaluation-delta: false

application:
  url: ${http://localhost:${server.port}}