CREATE TABLE attender
(
    code      bigserial    NOT NULL,
    name      VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    company   VARCHAR(100),
    title     VARCHAR(100),
    email     VARCHAR(100),
    phone     VARCHAR(100),
    country   VARCHAR(5),
    CONSTRAINT pk_attender PRIMARY KEY (code)
);

CREATE INDEX idx_3646bc2ee8b2214d4cac8693c ON attender (name);

CREATE INDEX idx_b3f7cb5284c093a7bfe65731e ON attender (last_name);


INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Adão José', 'Martins', '', '', 'adao.martins@estudante.ufscar.br', '', ''),
       ('Adrián', 'Gómez Árciga', 'Universidad Autónoma De Baja California', '', 'adrian.arciga@uabc.edu.mx', '', ''),
       ('Adriana', 'Breda', 'Universidad De Barcelona', '', 'adriana.breda@ub.edu', '', ''),
       ('Adriana', 'Toxtle Colotl', 'Benemérita Universidad Autónoma De Puebla', '', 'toxtleadry9@gmail.com', '', ''),
       ('Adriana', 'Gonzalez', 'MINERD, Reg. 13', '', 'adriana.gonzalez@minerd.gob.do', '', ''),
       ('Adriana', 'Richter', 'UFFS-ERECHIM', '', 'adrianarichit@gmail.com', '', ''),
       ('Adriano', 'Angustia', 'MINERD, Reg. 04', '', 'elastro3000@gmail.com', '', ''),
       ('Agostinho Iaqchan Ryokiti', 'Homa', 'Universidade Franciscana', '', 'iaqchan@hotmail.com', '', ''),
       ('Agueda', 'Baez', '', '', 'aguedabaezj@gmail.com', '', ''),
       ('Agueda Nicole', 'Báez Jiménez', 'Isfodosu', '', 'aguedabaezj@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Alba Iris De Las M.', 'Gonzalez German', 'MINERD, Reg. 15', '', 'alba.gonzalezg1@minerd.gob.do', '', ''),
       ('Alberto', 'Zapatera Llinares', 'Universidad De Alicante', '', 'alberto.zapatera@ua.es', '', ''),
       ('Alberto Agustín', 'Pérez Cruz', 'Isfodosu', '', 'alberto.perez@isfodosu.edu.do', '', ''),
       ('Alejandra', 'Sánchez Ávila', 'UNED', '', 'alsanchez@uned.ac.cr', '', ''),
       ('Alejandro José', 'Taveras Reyes', 'Isfodosu', '', 'alejandro.taveras@isfodosu.edu.do', '', ''),
       ('Alexander', 'Difó Rodríguez', 'MINERD', '', 'alexander.difo@minerd.gob.do', '', ''),
       ('Alexánder', 'Hernández', 'Universidad De La Laguna', '', 'alexander.hernandez@ull.edu.es', '', ''),
       ('Alexandra', 'Fregueiro', 'Consejo De Formación En Educación', '', 'suresmeralda@hotmail.com', '', ''),
       ('Alexandre', 'Xavier Dos Santos', 'Governo Do Estado Do Rio Grande Do Sul', '', 'alexandrexrs@gmail.com', '',
        ''),
       ('Alfonso', 'Romero Huertas', 'Universidad Antonio Nariño', '', 'romerohuertas78@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Allan Guillermo', 'Gen Palma', 'UNED Costa Rica', '', 'agen@uned.ac.cr', '', ''),
       ('Alma', 'Soto Castillo', 'Benemérita Universidad Autónoma De Puebla, México', '', 'soto_castillo10@hotmail.com',
        '', ''),
       ('Altagracia', 'Nais Pérez', 'MINERD, Reg. 15', '', 'altagracianais27@gmail.com', '', ''),
       ('Altagracia', 'Nais Perez', 'MINERD, Reg. 15', '', 'altagracianais27@gmail.com', '', ''),
       ('Alvaro Rafael', 'Lecompte Montes', 'Universidad Interamericana De Puerto Rico', '', 'alvarolecompte@gmail.com',
        '', ''),
       ('Amabile', 'Mesquita', 'PUC-SP', '', 'amabile.mesquita@ueg.br', '', ''),
       ('Ambar Larimar', 'Pinales De la Cruz', 'MINERD, Reg. 04', '', 'ambarpinales@gmail.com', '', ''),
       ('Ana', 'Maroto Sáez', 'Universidad De Valladolid', '', 'anaisabel.maroto@uva.es', '', ''),
       ('Ana Catalina', 'Siles Murillo', '', '', 'ana.silesmurillo@ucr.ac.cr', '', ''),
       ('Ana Edith', 'Varela Achurra', 'Universidad De Panamá', '', 'ana.varela@up.ac.pa', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Ana josefina', 'Castillo Canejeter', 'MINERD, Reg. 10', '', 'anacanejeter16@gmail.com', '', ''),
       ('Analia', 'Bergé', 'Université Du Québec À Rimouski (UQAR)', '', 'analia_berge@uqar.ca', '', ''),
       ('Ana Liliana', 'Abreu Perdomo', 'Isfodosu', '', 'ana.liliana@isfodosu.edu.do', '', ''),
       ('Ana María', 'González García', 'O&M', '', 'anamariagg28@gmail.com', '', ''),
       ('Ana Mercedes', 'Candelario Solano', 'MINERD, Reg. 04', '', 'ana,candelario@minerd.gb.do', '', ''),
       ('Ana Mercedes', 'Báez', 'ISA', '', 'abaez@isa.edu.do', '', ''),
       ('Ana Paola', 'Castillo Domenech', 'Mathkind Global', '', 'pao@mathkind.org', '', ''),
       ('Ana Sofia', 'Montenegro Arango', 'Fundación Universitaria Salesiana', '', 'ana.montenegro@salesiana.edu.co',
        '', ''),
       ('Anderzon', 'Araujo', 'MINERD, Reg. 10', '', 'anderzon.moreno@minerd.do.gob', '', ''),
       ('Andrea', 'Dipré Jiménez', 'MINERD, Reg. 04', '', 'andrea.dipre@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Andrea', 'Pinto', 'Universidad De Santiago De Chile', '', 'andrea.pinto@usach.cl', '', ''),
       ('Andrea', 'Araya Chacón', 'Universidad De Costa Rica', '', 'andrea.arayachacon@ucr.ac.cr', '', ''),
       ('Andrea', 'Serna Rivera', 'Universidad Del Valle', '', 'andrea.serna@correounivalle.edu.co', '', ''),
       ('Andrea Milena', 'Osorio Cardenas', 'Secretaría De Educación De Manizales', '', 'milenacardenas23@gmail.com',
        '', ''),
       ('Andréia', 'Araújo De Farias Aquino', 'UEM/IFPR', '', 'andreia.aquino@ifpr.edu.br', '', ''),
       ('André Luis', 'TrevISAn', 'UTFPR', '', 'andreluistrevisan@gmail.com', '', ''),
       ('Andrés Antonio', 'Valdés Retamal', 'Universidad Cátolica Del Maule', '', 'v.andres.r@hotmail.com', '', ''),
       ('Andrés Fernando', 'Mosquera Díaz', '', '', 'afernando.mosquera@udea.edu.co', '', ''),
       ('Andrés Gabriel', 'Silverio Vásquez', '', '', 'andresgabrielsilveriovasquez@ gmail.com', '', ''),
       ('Andy Gabriel', 'Tavarez Tejada', 'PUCMM', '', 'andygt1822@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Andy José', 'Rivas Moreno', 'MINERD, Reg. 05', '', 'andyrivas45@gmail.com', '', ''),
       ('Anerfri', 'Lora Acosta', 'MINERD, Reg. 04', '', 'anerfri06@gmail.com', '', ''),
       ('Aneudy', 'Minier', 'MINERD, Reg. 00', '', 'aneudy.minier@minerd.gob.do', '', ''),
       ('Angel', 'Ruiz', 'Universidad De Costa Rica', '', 'ruizz.angel@gmail.com', '', ''),
       ('Angel', 'Mastromartino Perez', 'PUCMM', '', 'a.mastromartino@ce.pucmm.edu.do', '', ''),
       ('Angela', 'Chalas', 'MINERD, Reg. 04', '', 'angelachalasb@gmail.com', '', ''),
       ('Angela', 'de Leon Ogando', 'MINERD, Reg. 02', '', 'angela.deleon@minerd.gob.do', '', ''),
       ('Àngela', 'Buforn Lloret', 'Univesidad De Alicante', '', 'angela.buforn@ua.es', '', ''),
       ('Angel Gabriel', 'Lopez Rodriguez', 'PUCMM', '', 'aglr0003@ce.pucmm.edu.do', '', ''),
       ('Angel Manuel', 'Ortiz Montas', 'PUCMM', '', 'amom0002@ce.pucmm.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Ángel Manuel', 'Díaz González', 'MINERD, Reg. 16', '', 'angel.diazgo@minerd.gob.do', '', ''),
       ('Angie Carlina', 'de los Santos Reyes', 'MINERD, Reg. 10', '', 'angiedelossantos22@gmail.com', '', ''),
       ('Angie De Los Ángeles', 'Vega Vega', 'Universidad De Costa Rica-Sede Sur', '', 'angie.vegavega@ucr.ac.cr', '',
        ''),
       ('Angy Carelly', 'Coronel Suárez', 'Universidad De Puerto Rico En Mayagüez', '', 'angy.coronel@upr.edu', '', ''),
       ('Anny', 'del Valle Zarzuela', 'MINERD, Reg. 18', '', 'anny.delvalle@minerd.gob.do', '', ''),
       ('Antonia Del Carmen', 'Álvarez Reynoso', 'Isfodosu', '', 'antonia.alvarez@isfodosu.edu.do', '', ''),
       ('Antonio', 'de los Santos', 'MINERD, Reg. 04', '', 'kataleyavasquez987@gmail.com', '', ''),
       ('Antonio', 'Rivero Alexanderson', 'PUCMM', '', 'ariveroalex@gmail.com', '', ''),
       ('Aquiles Julio', 'Guerrero Fondeur', 'Isfodosu', '', 'julio.guerrero@isfodosu.edu.do', '', ''),
       ('Arelis', 'Manzueta Sanchez', 'MINERD, Reg. 15', '', 'arelismanzuetasanchez@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Arelis', 'Manzueta Sánchez', 'Instituto Superior De Estudio Pedro Poveda', '',
        'arelismanzuetasanchez@gmail.com', '', ''),
       ('Argenis Elpidio', 'López Stubbs', 'MINERD, Reg. 00', '', 'argenis.lopez@minerd.gob.do', '', ''),
       ('Ariana Inés', 'Rodríguez Flores', 'Universidad De Puerto Rico, Recinto De Río Piedras', '',
        'ariana.rodriguez20@upr.edu', '', ''),
       ('Ariana Kazumi', 'Mayuri Jimenez', '', '', 'arianakmj@gmail.com', '', ''),
       ('Ariana Paola', 'Lozano Campos', 'Universidad Nacional De Costa Rica', '', 'plozano725@gmail.com', '', ''),
       ('Arianna', 'Corporán Montero', '', '', 'ariannacorporanmontero@gmail.com ', '', ''),
       ('Arisbel', 'Tavárez Tavárez', 'PUCMM', '', 'axtt0002@ce.pucmm.edu.do', '', ''),
       ('Arsenia', 'De Jesús Severino', 'UTECO', '', 'arsenia.severino@uteco.edu.do', '', ''),
       ('Aselys Lisbeth', 'Lora Rodríguez', 'PUCMM', '', 'allr0002@ce.pucmm.edu.do', '', ''),
       ('Ashley', 'Gutierrez', '', '', 'ashley.gutierrez@ideice.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Augusta Rosa Maria', 'Osorio Gonzales', 'PUCP', '', 'arosorio@pucp.edu.pe', '', ''),
       ('Aury Rafael', 'Pérez Cuevas', 'MINERD, Reg. 00', '', 'aury.perez@minerd.gob.do', '', ''),
       ('Axel', 'Jiménez Matamoros', 'Universidad De Costa Rica', '', 'axel.jimenezmatamoros@ucr.ac.cr', '', ''),
       ('Azarías', 'Escarramán Barrera', 'PUCMM', '', 'axeb0001@ce.pucmm.edu.do', '', ''),
       ('Balbara Massiel', 'Marte Gonzalez', 'MINERD, Reg. 15', '', 'barbara.marte@minerd.gob.do', '', ''),
       ('Bartolo Máximo', 'Triana Hernández', 'MESCyT', '', 'bartolotriana@gmail.com', '', ''),
       ('Berkis de', 'la Cruz Belen', 'MINERD, Reg. 10', '', 'belkisdelacruzbelen80@gmail.com', '', ''),
       ('Biarcy De Jesús', 'Franco Cuello', 'MINERD, Reg. 06', '', 'biarcy-jima@hotmail.com', '', ''),
       ('Bienvenida', 'Urbaez', 'MINERD, Reg. 04', '', 'bienbaurbaez@hotmail.com', '', ''),
       ('Blanca Esthela', 'Ledezma Durán', 'Escuela Normlal Miguel F. Martínez', '', 'blanca.ledezma@enmfm.edu.mx', '',
        '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Brayan Ricardo', 'Andrade Zambrano', '', '', 'brayan.andrade@correounivalle.edu.co', '', ''),
       ('Brigitte Johana', 'Sanchez Robayo', 'Universidad Distrital Francisco José De Caldas', '',
        'bjsanchezr@udistrital.edu.co', '', ''),
       ('Bruna Aparecida', 'Ferreira De Castro', 'UNESPAR', '', 'brunaacastro217@gmail.com', '', ''),
       ('Caridad Anselma', 'Espinal Matías', 'PUCMM', '', 'ca.espinal@ce.pucmm.edu.do', '', ''),
       ('Carina', 'Rivera Londoño', 'Udea', '', 'carina.rivera@udea.edu.co', '', ''),
       ('Carlos', 'Sanchez Marquez', 'MINERD, Reg. 02', '', 'iancasama@gmail.com', '', ''),
       ('Carlos', 'Sánchez Fernández', 'Universidad De La Habana', '', 'csanchez@matcom.uh.cu', '', ''),
       ('Carlos Adrián', 'Genao Marcelino', 'PUCMM', '', 'cagm0003@ce.pucmm.edu.do', '', ''),
       ('Carlos David', 'Vargas González', 'MINERD, Reg. 15', '', 'carloesdavid@gmail.com', '', ''),
       ('Carlos Eduardo', 'Rojas Bruna', 'Pontificia Universidad Católica De Chile', '', 'carojasb@uc.cl', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Carlos Jacinto', 'Vargas Samaniego', 'Universidad De Panamá', '', 'carlos23199220@gmail.com', '', ''),
       ('Carlos Manuel', 'De La Cruz', 'MINERD, Reg. 10', '', 'carlosdelacruzsuero@gmai.com', '', ''),
       ('Carlos Mario', 'Jaramillo López', '', '', 'carlos.jaramillo1@udea.edu.co', '', ''),
       ('Carmen', 'Vieira Mathias', 'Universidade Federal De Santa Maria', '', 'carmen@ufsm.br', '', ''),
       ('Carmen Eulalia', 'Calle Palomeque', 'Universidad De Cuenca', '', 'eulalia.calle@ucuenca.edu.ec', '', ''),
       ('Carmen Larissa', 'Rodríguez Poveda', 'Universidad De Panamá', '', 'carmen.rodriguezp@up.ac.pa', '', ''),
       ('Carmen LuISA', 'Lopez De Pena', 'PUCMM', '', 'cl.lopez@ce.pucmm.edu.do', '', ''),
       ('Carmen Miguelina', 'Santos Abreu', 'PUCMM', '', 'cm.santos@ce.pucmm.edu.do', '', ''),
       ('Carolina', 'Ruminot', 'Universidad De Ottawa', '', 'cruminot@uottawa.ca', '', ''),
       ('Carolyn', 'Rodríguez Núñez', 'PUCMM', '', 'cxrn0001@ce.pucmm.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Catalina', 'Molano Carranza', 'Secretaria De Educacion Cundinamarca', '', 'ebenezercata@hotmail.com', '', ''),
       ('Cecilia', 'Marleny Mambrú', 'MINERD, Reg. 15', '', 'katy.duran@minerd.gob.do', '', ''),
       ('Celia Elizabeth', 'Villagra', 'Facultad Regional Orán', '', 'villagracelia@gmail.com', '', ''),
       ('Celina', 'Abar', 'PUC-SP', '', 'abarcaap@pucsp.br', '', ''),
       ('César Abel', 'Santil Glass', 'MINERD, Reg. 10', '', 'cesar.santil@minerd.gob.do', '', ''),
       ('Cila Eduviges', 'Mola Reyes', 'MESCyT', '', 'cilaeduvijesmolareyes@gmail.com', '', ''),
       ('Cirilo', 'Peña Gonzalez', 'MINERD, Reg. 17', '', 'cirilopenagonzalez@gmail.com', '', ''),
       ('Claribel', 'Hernández Dipré', 'MINERD, Reg. 15', '', 'claribelhd2980@gmail.com', '', ''),
       ('Claudel Santiago', 'Santana Camacho', 'MINERD, Reg. 15', '', 'cssc1021@gmail.com', '', ''),
       ('Claudia Amelia', 'Matus Zuñiga', 'USACH', '', 'claudia.matus.z@usach.cl', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Claudia Janet', 'Jiménez Peguerro', 'MINERD, Reg. 15', '', 'jclaudiajanet@gmail.com', '', ''),
       ('Claudia Jisela', 'Dorantes Villa', 'IPN', '', 'cjdorante@yahoo.com.mx', '', ''),
       ('Claudia Lisete', 'Oliveira Groenwald', 'Universidade Franciscana', '', 'claudiag1959@gmail.com', '', ''),
       ('Claudia Lorena', 'Vargas Díaz', 'Universidad De Santiago De Chile', '', 'claudia.vargas.d@usach.cl', '', ''),
       ('Corina', 'Tejada Polanco', 'UASD', '', 'ctejada40@uasd.edu.do', '', ''),
       ('Crisanta', 'Rodríguez', 'MINERD, Reg. 15', '', 'crisantar79 @gmail.com', '', ''),
       ('Crismeiry Rosalía', 'Fortuna Rivera', 'PUCMM', '', 'crfr0001@ce.pucmm.edu.do', '', ''),
       ('Cristiana Amparo', 'Abreu Espinal', '', '', 'cr.abreu@ce.pucmm.edu.do', '', ''),
       ('Cristian Andrés', 'Ortega Aguilar', '', '', 'cristian.ortega@ucr.ac.cr', '', ''),
       ('Cristian Eduardo', 'Quesada Fernández', 'UNED', '', 'cquesadaf@uned.ac.cr', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Cristian Martin', 'Medina Ferreras', 'MINERD, Reg. 18', '', 'cristian.medina@minerd.gob.do', '', ''),
       ('Cristòbal', 'Peralta', 'MINERD, Reg. 15', '', 'cristobal.peralta@minerd.gob.do', '', ''),
       ('Crystal', 'Kalinec-Craig', 'University Of Texas At San Antonio', '', 'crystal.kalinec-craig@utsa.edu', '', ''),
       ('Dagoberto Moises', 'Pena', 'PUCMM', '', 'dm.pena@ce.pucmm.edu.do', '', ''),
       ('Dakeisi Janel', 'Perdomo Espinal', 'UAPA', '', 'dakeisiperdomo@uapa.edu.do', '', ''),
       ('Damarys Dinorah', 'Castellanos', 'Isfodosu', '', 'damarysuni0928@gmail.com', '', ''),
       ('Danitza Soledad', 'Mirabal Aybar', '', '', 'danitzamirabal920@gmail.com', '', ''),
       ('Dannael', 'Carrero Pellicier', 'Universidad Interamericana De Puerto Rico, Recinto De Ponce', '',
        'dannael.carrero@upr.edu', '', ''),
       ('Darwin Alexander', 'Moreno Gatica', '', '', 'darwinmoreno56@gmail.com', '', ''),
       ('Darwin Dacier', 'Peña González', 'Universidad Del Magdalena', '', 'ddpenag@unimagdalena.edu.co', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('David Fernando', 'Méndez Vargas', '', '', 'david.mendez@udea.edu.co', '', ''),
       ('Daysi', 'Paola Nuñez', 'MINERD, Reg. 10', '', 'dpnunezm@gmail.com', '', ''),
       ('Delvi Antonio', 'Polanco Adames', 'MINERD, Reg. 00', '', 'delvi.polancoad@minerd.gob.do', '', ''),
       ('Denise Deyanira', 'Chamorro Manríquez', 'Universidad Católica De La Santísima Concepción', '',
        'dechamorrom@gmail.com', '', ''),
       ('Denzel Johan', 'Martínez Herrera', 'PUCMM', '', 'djmh0001@ce.pucmm.edu.do', '', ''),
       ('Diana', 'Hernández Rivera', 'Universidad Autónoma De Coahuila, México.', '', 'diana_hernandez@uadec.edu.mx',
        '', ''),
       ('Diana Carolina', 'Vélez Pantaleon', 'MINERD, Reg. 15', '', 'dianavelezp@hotmail.com', '', ''),
       ('Diana Carolina', 'Pineda Pérez', '', '', 'dianapineda1710@gmail.com', '', ''),
       ('Diego Eduardo', 'Lieban', 'Ifrs-CAMPUS BENTO GONÇALVES', '', 'diego.lieban@bento.ifrs.edu.br', '', ''),
       ('Dionisio', 'Portes Moreta', 'MINERD, Reg. 02', '', 'dionisio.portes@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Dirwin Alfonzo', 'Muñoz Pinto', 'Isfodosu', '', 'dirwin.munoz@isfodosu.edu.do', '', ''),
       ('Disneyri', 'Juliao Espinosa', 'PUCMM', '', 'disneyrijuliaoespinosa@gmail.com', '', ''),
       ('Dominicana', 'Asencio Germán', 'UNPHU', '', 'da6606@unphu.edu.do', '', ''),
       ('Dumas', 'Manzano Franco', 'Universidad Del Cauca, Colombia', '', 'dmfranco@unicauca.edu.co', '', ''),
       ('Edgar', 'Garcia', 'PUCMM', '', 'edgar_deni@outlook.com', '', ''),
       ('Edgar Alberto', 'Guacaneme Suárez', 'Universidad Pedagógica Nacional', '', 'guacaneme@pedagogica.edu.co', '',
        ''),
       ('Edgar Esaúl', 'Saucedo Becerra', 'Instituto Tecnológico De Zacatecas Tecnm', '', 'esaul.saucedo@itz.edu.mx',
        '', ''),
       ('Edith Marcela', 'Chorolque', 'U.N.Sa F.R.O.', '', 'marcelachorolque@gmail.com', '', ''),
       ('Eduardo', 'Minaya', 'MINERD, Reg. 10', '', 'eduardo.minaya@minerd.gob.do', '', ''),
       ('Eduardo', 'Basurto Hidalgo', 'ULSA', '', 'basurto.e@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Eduardo Emiliano', 'Muñoz Ortiz', 'Universidad De Costa Rica', '', 'eduardo.munos@ucr.ac.cr', '', ''),
       ('Eduardo Iván', 'Mancera Alarcón', '', '', 'eduardoivanma@gmail.com', '', ''),
       ('Edward', 'Mendez', 'MINERD, Reg. 10', '', 'mendezedward95@gmail.com', '', ''),
       ('Edwin Abad', 'Núñez Díaz', 'MINERD, Reg. 09', '', 'edwinabadnunezdia@gmail.com', '', ''),
       ('Edwin Antonio', 'Chaves Esquivel', '', '', 'echavese@gmail.com', '', ''),
       ('Edwin Eduardo', 'Domínguez Pérez', 'PUCMM', '', 'eedp0001@ce.pucmm.edu.do', '', ''),
       ('Edwin William', 'Ortiz Pimentel', 'MINERD, Reg. 00', '', 'edwin.ortiz@minerd.gob.do', '', ''),
       ('Efraín Ambiórix', 'López Tejeda', 'Isfodosu', '', 'efrain.lopez@isfodosu.edu.do', '', ''),
       ('Elcio', 'Pasolini Milli', 'IFES', '', 'elciopmilli@gmail.com', '', ''),
       ('Elidania', 'Moreta Matías', 'PUCMM', '', 'exmm0007@ce.pucmm.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Elidia', 'Florian Santana', 'MINERD, Reg. 10', '', 'ediliaflorian08@gmail.com', '', ''),
       ('Eliecer Leonardo', 'Fitoria Pérez', '', '', 'eliecer.fitoria@ucr.ac.cr', '', ''),
       ('Elizabeth', 'Torres Puentes', 'Universidad Pedagógica Nacional', '', 'etorresp@pedagogica.edu.co', '', ''),
       ('Elizabeth', 'Adames', 'MINERD, Reg. 10', '', 'eadamesa1@gmail.com', '', ''),
       ('Elizabeth', 'Figueroa', 'MINERD, Reg. 10', '', 'elizabeth.figueroa@minerd.gob.do ', '', ''),
       ('Elizabeth', 'Michel Mustafá', '', '', ' elizabethmichelmustafa@gmail.com', '', ''),
       ('Elizabeth', 'Michel Mustafa', 'MINERD, Reg. 15', '', 'tecnicomustafa@gmail.com', '', ''),
       ('Elizabeth', 'Rincón Santana', 'UASD', '', 'te10elirisa@gmail.com', '', ''),
       ('Emely Esmeralda', 'De La Rosa Del Rosario', 'PUCMM', '', 'eedd0001@ce.pucmm.edu.do', '', ''),
       ('Emily Caroline', 'Felix Cordeiro', 'Uel-UNIVERSIDADE ESTADUAL DE LONDRINA', '', 'emilycfcordeiro@gmail.com',
        '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Enmanuel de Jesús', 'Rodríguez Vargas', '', '', 'enmanuelbonifacio9@gmail.com', '', ''),
       ('Eric Iván', 'Figueroa González', 'Universidad De Puerto Rico', '', 'eric.figueroagonzalez@upr.edu', '', ''),
       ('Erick', 'Padilla Bonilla', 'Isfodosu', '', '202230056@issu.edu.do', '', ''),
       ('Eric Ricardo', 'Padilla Mora', 'Universidad Estatal A Distancia', '', 'epadillamora@gmail.com', '', ''),
       ('Erika', 'Arias', '', '', 'erikaariasblanco17@gmail.com', '', ''),
       ('Ernesto Geovani', 'Figueroa-González', 'Universidad Juárez Del Estado De Durango, México.', '',
        'geovani.figueroa@ujed.mx', '', ''),
       ('Esbelin Altagracia', 'Pérez Mora', 'MINERD, Reg. 10', '', 'esbelynperz26@gmail.com', '', ''),
       ('Esteban Junior', 'Rodriguez Arias', 'PUCMM', '', 'ejra0002@ce.pucmm.edu.do', '', ''),
       ('Esther Judith', 'Núñez Ureña', 'MINERD, Reg. 10', '', 'esther.nuñez@minerd.gob.do ', '', ''),
       ('Eudy Margarita', 'Lebrón Fernández', 'MINERD, Reg. 06', '', 'almanicole0605@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Fabián Alonso', 'Vásquez Hernández', 'Universidad De Costa Rica', '', 'fvasquez0600@gmail.com', '', ''),
       ('Fabienne Genevieve Marcelle', 'Venant', 'UQAM', '', 'venant.fabienne@uqam.ca', '', ''),
       ('Fabio Hernán', 'Echeverry Pérez', 'Institución Educativa María Auxiliadora', '', 'fachelo13@gmail.com', '',
        ''),
       ('Fabiola', 'Arrivillaga Hurtado', 'Universidad Rafael Landívar', '', 'farrivillaga@url.edu.gt', '', ''),
       ('Federico', 'De Olivera Lamas', '', '', 'fededeo@gmail.com', '', ''),
       ('Felipe De Jesús', 'Cordero González', 'Isfodosu', '', 'felipe.cordero@isfodosu.edu.do', '', ''),
       ('Felix', 'De La Cruz Serrano', '', '', 'feldese@gmail.com', '', ''),
       ('Fernanda', 'Drummond Pequeno Valadão', 'UNB', '', 'nandadrummond09@gmail.com', '', ''),
       ('Fernando', 'Hitt', 'Cinvestav Y UQAM', '', 'ferhitt@yahoo.com', '', ''),
       ('Filánder', 'Sequeira Chavarría', 'Universidad Nacional Y Universidad De Costa Rica', '',
        'filander.sequeira.chavarria@una.ac.cr', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Francheska', 'Rodríguez Santana', 'MINERD, Reg. 10', '', 'franches2800@gmail.com', '', ''),
       ('Franciele', 'Santos Teixeira', 'UNESP', '', 'fs.teixeira@unesp.br', '', ''),
       ('Francis', 'Mora Ferreras', 'UNPHU', '', 'fm10900@unphu.edu.do', '', ''),
       ('Francisca Altagracia', 'Morrobel Arias', 'MINERD, Reg. 09', '', 'famniarias2282@gmail.com', '', ''),
       ('Francisco Del Rosario', 'Sánchez Fernández', 'UTESA', '', 'franciscosanchez@utesa.edu', '', ''),
       ('Francoise Bárbara', 'Molina Vazquez', 'MINERD, Reg. 15', '', 'francoisemolina27@gmail.com', '', ''),
       ('Franderly', 'Acostada Valdez', 'PUCMM', '', 'f.acosta@ce.pucmm.edu.do', '', ''),
       ('Frankely', 'Escolastico Robles', 'MINERD, Reg. 16', '', 'frankely.escolastico@docente.edu.do', '', ''),
       ('Franklin Rafael', 'Astudillo Villalba', 'Isfodosu', '', 'franklin.villalba@isfodosu.edu.do', '', ''),
       ('Freddy Nicolás', 'Saviñón Peralta', 'PUCMM', '', 'fnsp0001@ce.pucmm.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Fredy', 'Rivadeneira Loor', 'Universidad Técnica De Manabí', '', 'fredy.rivadeneira@utm.edu.ec', '', ''),
       ('Freisy Elisa', 'Cabrera Tejeda', 'MINERD, Reg. 03', '', 'freisytejeda@gmail.com', '', ''),
       ('Gabriel', 'Dos Santos E Silva', 'Universidade Federal Do Paraná', '', 'gabriel.santos22@gmail.com', '', ''),
       ('Gabriela', 'Gomez Pasquali', 'Omapa', '', 'gabriela@omapa.org.py', '', ''),
       ('Gabriela', 'Rodriguez', 'Sociedad Peruana De Educacion Matematica', '', 'gabyrodriguez.pe@gmail.com', '', ''),
       ('Gemimax', 'Anderson Pook', 'MINERD, Reg. 15', '', 'gemimaxpool@gmail.com', '', ''),
       ('Genesis', 'Ramirez', 'PUCMM', '', 'gxrx0002@ce.pucmm.edu.do', '', ''),
       ('Geovanny Arturo', 'Lachapell Maldonado', 'MINERD, Reg. 00', '', 'geovanny.lachapell@minerd.gob.do', '', ''),
       ('German', 'Cadavid  Arango', 'Universidad Tecnológica De Pereira. Utp', '', 'gcadavid@utp.edu.co', '', ''),
       ('Germania', 'Jiménez Sánchez', 'MINERD, Reg. 00', '', 'germania.jimenez@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Gerobal', 'Tejeda', 'MINERD, Reg. 04', '', 'gerobaltejeda@gmail.com', '', ''),
       ('Gert', 'Schubring', 'UFRJ', '', 'gert.schubring@uni-bielefeld.de', '', ''),
       ('Gilbert', 'Valverde', '', '', 'gvalverde@albany.edu', '', ''),
       ('Gilberto', 'Chavarría Arroyo', 'Universidad Nacional, Costa Rica', '', 'gilberto.chavarria.arroyo@una.cr', '',
        ''),
       ('Gilberto De Jesus', 'Obando Zapata', 'Universidad De Antioquia', '', 'gilberto.obando@udea.edu.co', '', ''),
       ('Gilberto Santos', 'Cerqueira', 'UFC', '', 'giufarmacia@gmail.com', '', ''),
       ('Girbelis', 'Guante Terrero', 'PUCMM', '', 'gxgt0001@ce.pucmm.edu.do', '', ''),
       ('Gloria Estefani', 'Morel Brito', 'PUCMM', '', 'gemb0002@ce.pucmm.edu', '', ''),
       ('Glory Bel', 'Pérez', 'PUCMM', '', 'gb.perez@ce.pucmm.edu.do', '', ''),
       ('Gregorina', 'Deprats Peña', 'MINERD, Reg. 15', '', 'depratsgrego@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Gretty Maria', 'Tavarez Perez', 'MINERD, Reg. 00', '', 'gretty.tavarez@minerd.gob.do', '', ''),
       ('Guillermo Enrique', 'Ramirez Montes', 'Universidad De Costa Rica', '', 'guillermo.ramirez_m@ucr.ac.cr', '',
        ''),
       ('Hamlet Humberto', 'Castillo Alvino', 'PUCMM', '', 'hcastillo@pucmm.edu.do', '', ''),
       ('Hanser', 'Peña Gonzalez', 'MINERD, Reg. 18', '', 'hanser.peña@minerd.gob.do', '', ''),
       ('Héctor Alonso', 'Rosas Álvarez', 'Escuela Normal Miguel F. Martínez', '', 'hector.rosas@enmfm.edu.mx', '', ''),
       ('Helen', 'Guillén Oviedo', 'Universidad Naciona, Costa Rica', '', 'hellen.guillen.oviedo@una.ac.cr', '', ''),
       ('Helmer Jesus', 'Ruiz Diaz', 'Universidad Del Cauca, Colombia', '', 'hjdiaz@unicauca.edu.co', '', ''),
       ('Henry Alexander', 'Ramírez Bernal', '', '', 'haramirezb@udistrital.edu.co', '', ''),
       ('Henry Rafael', 'Mejía Álvarez', 'PUCMM', '', 'hr.mejia@ce.pucmm.edu.do', '', ''),
       ('Hilda Mignolia', 'Rivera Espinal', 'MINERD, Reg. 14', '', 'hilda.riveraqminerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Hilda Nohely De', 'La Cruz Morel', 'MINERD, Reg. 17', '', 'hilda.delacruz@minerd.gob.do', '', ''),
       ('Hildebrando', 'Diaz Soler', 'Secretaria De Educacion De Boyaca', '', 'hildebrandodiaz@hotmail.com', '', ''),
       ('Ibelise', 'García Contreras', 'MINERD, Reg. 17', '', 'ibelisegarciacontreras@gmail,com', '', ''),
       ('Ilma Edisa', 'Arrivillaga Hernández', 'Escuela Oficial Rural', '', 'edisaarrivillaga@yahoo.es', '', ''),
       ('Imenia', 'Mercedes Sabino', 'MINERD, Reg. 17', '', 'imenia.sabino@minerd.gob.do', '', ''),
       ('Inés Jovanna', 'Ramírez De Los Santos', 'PUCMM', '', 'ij.ramirez@ce.pucmm.edu.do', '', ''),
       ('Iris Josefa', 'Mendez Lopez', 'MINERD, Reg. 15', '', 'irismendezlopez15@gmail.com', '', ''),
       ('ISAbel Cristina', 'Márquez De Mastromartino', 'PUCMM', '', 'ic.marquez@ce.pucmm.edu.do', '', ''),
       ('Isabel Hortensia', 'Miguez', '', '', 'miguezisa26@gmail.com', '', ''),
       ('Isabella', 'Revelo Mera', '', '', 'isabella.revelo@correounivalle.edu.co', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Iselgis Janeth', 'De Diego Vásquez', 'Universidad De Panamá', '', 'iselgis.dediego@up.ac.pa', '', ''),
       ('Ismael', 'Hernández Hernández', 'Universidad De Costa Rica', '', 'ismaelhernan1122@gmail.com', '', ''),
       ('Ismely Miguelina', 'Abreu Ventura', '', '', 'ismely abreu ventura <lamaestraismely@gmail.com>', '', ''),
       ('Israely', 'Kaide Placencio', 'MINERD, Reg. 15', '', 'israely.placencio@minerd.gob.do', '', ''),
       ('Ivan', 'Leger', 'MINERD, Reg. 04', '', 'ivanleger2103@gmail.com', '', ''),
       ('Ivan Enrique', 'Leger Puello', 'MINERD, Reg. 04', '', 'ivanleger2103@gmail.com', '', ''),
       ('Ivonete', 'Pereira Amador', '', '', 'ivoneteamador67@gmail.com', '', ''),
       ('Jahaner Antonio', 'Sosa silvestres', 'MINERD, Reg. 17', '', 'jahaner.sosa@minerdgob.do', '', ''),
       ('Jaime Maria', 'Monteiro De Carvalho', '', '', 'jaimecs@mat.uc.pt', '', ''),
       ('Jaime Vladimir', 'González De La Cruz', 'UNPHU', '', 'jgonzalez@unphu.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Jairo Arturo', 'Ayala Godoy', 'Universidad De Puerto Rico', '', 'jairoarturo.ayala@upr.edu', '', ''),
       ('Jaroly', 'Méndez Subervi', 'PUCMM', '', 'jxms0005@ce.pucmm.edu.do', '', ''),
       ('Jawal Berihuete', 'de los Santos', 'MINERD, Reg. 10', '', 'reynacrystal2412@gmail.com', '', ''),
       ('Jawer Raulin Encarnación', 'De Óleo', 'MINERD, Reg. 10', '', 'jawered2092@gmail.com', '', ''),
       ('Jazmín Adriana', 'Juárez Ramírez', 'Instituto Politécnico Nacional', '', 'jjuarezr@ipn.mx', '', ''),
       ('Jennifer', 'Fonseca Castro', 'Universidad Nacional', '', 'jennifer.fonseca.castro@una.cr', '', ''),
       ('Jennifer', 'Cid Reyes', '', '', 'jennifer.cid@rdmescyt.edu.do ', '', ''),
       ('Jeremias', 'Willmore Metivier', 'PUCMM', '', 'j.willmore@ce.pucmm.edu.do', '', ''),
       ('Jeser Caleb', 'Candray Menjívar', 'Universidad Francisco Gavidia', '', 'jccandray@gmail.com', '', ''),
       ('Jesus', 'Valdez Cabrera', 'MINERD, Reg. 10', '', 'jesus031385@outlook.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Jesús Ramón', 'Guillén Ruiz', 'Isfodosu', '', 'jesus.guillen@isfodosu.edu.do', '', ''),
       ('Jhonny', 'Perez Alcantara', 'MINERD, Reg. 02', '', 'jhonny.perez@minerd.gob.do', '', ''),
       ('Jhoselyn', 'Adames Adames', 'MINERD, Reg. 16', '', 'jhoselyn.adames@minerd.gob.do', '', ''),
       ('Joab', 'Dos Santos Silva', 'IFPB', '', 'joab.silva@ifpb.edu.br', '', ''),
       ('Jocelyn Pierre', 'Louis Vilmeney', 'MINERD, Reg. 10', '', 'jocelyn.pierrelouis@docente.edu.do', '', ''),
       ('Joel Miguel', 'Corona Rodríguez', '', '', 'joelcorona_01@hotmail.com', '', ''),
       ('Jordy', 'Diaz Payano', 'MINERD, Reg. 12', '', 'jordy.diazp@minerd.gob.do', '', ''),
       ('Jorge', 'Blanco', 'PUCMM', '', 'ja.blanco@ce.pucmm.edu.do', '', ''),
       ('Jorge Daniel', 'Mello Román', 'Universidad Nacional De Concepción', '', 'jdmello@facet-unc.edu.py', '', ''),
       ('Jorge Guillermo', 'Jabalera Bastardo', 'MINERD, Reg. 05', '', 'jorge.jabalera@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Jorge Luis', 'Gutierrez Villegas', 'Mathkind Global', '', 'jorge@mathkind.org', '', ''),
       ('Jose', 'Saquimux', '', '', 'jsaquimux@yahoo.co.uk', '', ''),
       ('José', 'Manuel Veloz', 'MINERD, Reg. 10', '', 'jomavegar@gmail.com ', '', ''),
       ('José', 'Bosch Betancor', 'SMPM Emma Castelnuovo', '', 'jobobet@gmail.com', '', ''),
       ('José Antonio', 'Juárez López', '', '', 'jajul1969@gmail.com', '', ''),
       ('Jose Atilio', 'Guerrero', 'Isfodosu', '', 'jose.guerrero@isfodosu.edu.do', '', ''),
       ('José Bitsmar', 'Núñez Vargas', 'PUCMM', '', 'jo.nunez@ce.pucmm.edu.do', '', ''),
       ('Jose David', 'Francisco', 'MINERD, Reg. 10', '', 'jose.franciscom@minerd.gob.do', '', ''),
       ('José David', 'Vargas Gamboa', '', '', 'jose.vargas_g@ucr.ac.cr', '', ''),
       ('José David', 'Arias Rosa', 'PUCMM', '', 'jdar0002@ce.pucmm.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Josefa Andrea', 'Valdez Rijo', 'MINERD, Reg. 12', '', 'ajosefa.valdez@minerd.gbo.do', '', ''),
       ('José Gerardo', 'Vasconcelos', 'UFC', '', 'gerardovasconcelos@ufc.br', '', ''),
       ('José Israel', 'González geraldino', 'MINERD, Reg. 11', '', 'geraldino33@gmail.com', '', ''),
       ('Jose Luis', 'Henostroza Gamboa', 'Pontificia Universidad Católica Del Perú', '', 'jhenost@pucp.pe', '', ''),
       ('Jose Luis', 'Bossio Velez', 'Universidad De Antioquia', '', 'jose.bossio@udea.edu.co', '', ''),
       ('Jose  Luis', 'Permuy  Garcia', 'UNAPEC', '', 'j7madeleine.permuy@mail.com', '', ''),
       ('Joselyn', 'De Jesús Collado', 'MINERD, Reg. 08', '', 'joselyncollado01@gmail.com', '', ''),
       ('Jose Manuel', 'Castillo Sedano', 'UNISON', '', 'a215290112@unison.mx', '', ''),
       ('José Manuel', 'Torrez Vasquez', 'Isfodosu', '', 'jose.torrez@isfodosu.edu.do', '', ''),
       ('José María', 'Chamoso Sánchez', 'Universidad De Salamanca, España', '', 'jchamoso@usal.es', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('José Miguel', 'Suero Rico', 'Isfodosu', '', 'jose.suero@isfodosu.edu.do', '', ''),
       ('Joseph Davitte', 'Morrison Brito', '', '', 'josephmorrisonpga@gmail.com', '', ''),
       ('José Ramón', 'Jiménez Rodríguez', 'Universidad De Sonora', '', 'joseramon.jimenez@unison.mx', '', ''),
       ('José Ramón', 'Mota Pichardo', 'Isfodosu', '', 'jose.mota@isfodosu.edu.do', '', ''),
       ('José Romilio', 'Loría Fernández', 'Universidad Nacional De Costa Rica', '', 'jose.loria.fernandez@una.cr', '',
        ''),
       ('Joshua Mauricio', 'Paniagua-Chavarría', 'Universidad De Costa Rica', '', 'joshua.paniagua@ucr.ac.cr', '', ''),
       ('Josias Rosselin', 'Carrión Cordones', 'UNPHU', '', 'jrcarrion00@gmail.com', '', ''),
       ('Juan', 'Manzueta Mendez', 'MINERD, Reg. 17', '', 'juanmaz1983@gmail.com', '', ''),
       ('Juana Esther Ureña Cortorreal', 'De Nuñez', '', '', ' juana.urenac@minerd.gob.do', '', ''),
       ('Juana Evangelina', 'Caraballo León', 'PUCMM', '', 'z_caraballo@hotmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Juana Iris', 'Salvador López', 'MINERD', '', 'iris.lopezsena@gmail.com', '', ''),
       ('Juana Odalys', 'Caraballo De León', 'MINERD, Reg. 05', '', 'juana.caraballo@minerd.gob.do', '', ''),
       ('Juan Ariel De', 'Los Santos Arcángel', 'MINERD, Reg. 10', '', 'ariel24141002@gmail.com', '', ''),
       ('Juan Carlos', 'Sandí-Delgado', 'Universidad De Costa Rica', '', 'juan.sandidelgado@ucr.ac.cr', '', ''),
       ('Juan Esteban', 'Gordillo Niño', 'Universidad Distrital Francisco José De Caldas', '', 'jusanic12@gmail.com',
        '', ''),
       ('Juan Orlando', 'Cueto Santos', '', '', 'juan.cueto@minerd.gob.do', '', ''),
       ('Juliana', 'Ramírez Ramírez', '', '', 'juliana.ramirez7@udea.edu.co', '', ''),
       ('Juliana Andrea', 'Marín Mosquera', '', '', 'andrea.marin5@udea.edu.co', '', ''),
       ('Julio César', 'Díaz Cabrera', 'MINERD, Reg. 15', '', 'juliodc3838@gmail.com', '', ''),
       ('Julissa', 'Peña Mercedes', 'PUCMM', '', 'jxpm0004@ce.pucmm.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Junior', 'Rafael Rodriguez', 'MINERD, Reg. 12', '', 'juniorr.rodriguez@minerd.gob.do', '', ''),
       ('Karen', 'Mancera', '', '', 'dra.kelokumpu@gmail.com', '', ''),
       ('Karen Gabriela', 'Tamayo Pérez', '', '', 'karenga_35@hotmail.com', '', ''),
       ('Karina Amalia', 'Rizzo', 'Siglo 21-UNIVERSIDAD TECNOLÓGICA NACIONAL. FRA', '', 'karinarizzo71@gmail.com', '',
        ''),
       ('Karina Nunes Da', 'Silva', '', '', 'karina.nunes@rede.ulbra.br', '', ''),
       ('Katherine', 'Matos Valdez', '', '', 'maestrakatherinemv@gmail.com', '', ''),
       ('Katherine', 'Anyeline Sánchez', 'MINERD, Reg. 10', '', 'licdasanchezmate@gmail.com', '', ''),
       ('Kelly Altagracia', 'Báez Sosa', 'MINERD, Reg. 15', '', 'kellybaezsosa04@gmail.com', '', ''),
       ('Kendall', 'Valdez Jaquez', 'MINERD, Reg. 02', '', 'kendall.valdez@minerd.gob.do', '', ''),
       ('Kenneth', 'Esquivel Murillo', 'Universidad De Costa Rica-Sede Sur', '', 'kenneth.esquivelmurillo@ucr.ac.cr',
        '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Laidys Ámbar', 'Jiménez Bernard', '', '', 'laidys ámbar <ambarfj1728@gmail.com', '', ''),
       ('Laura Gabriela', 'Alvarez Paniagua', 'PUCMM', '', 'ga719953@gmail.com', '', ''),
       ('Lázaro', 'Pérez', 'UNISA', '', 'lperez@isa.edu.do', '', ''),
       ('Leanny Elizabeth', 'De Los Santos Toledo', 'PUCMM', '', 'ledt0002@ce.pucmm.edu.do', '', ''),
       ('Ledy', 'Garcia Rivera', '', '', 'ledy.garcia@upch.pe', '', ''),
       ('Lenny Amado', 'González Cruz', 'MINERD, Reg. 11', '', 'lic.lennygonzalez@gmail.com', '', ''),
       ('Leobel', 'Morell Pérez', 'Universidad Estatal Amazónica. Ecuador', '', 'leobelm2014@gmail.com', '', ''),
       ('Leonardo', 'Ariel Muñoz', '', '', 'leonardoariel749@gmail.com', '', ''),
       ('Leonardo Favio', 'Trujillo Diaz', 'Universidad Surcolombiana', '', 'leonardotrujillo@usco.edu.co', '', ''),
       ('Libeth', 'Dilone López', '', '', 'libethdilonelopez1991@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Lilian Akemi', 'Kato', 'Universidade Estadual De Maringá', '', 'lakato@uem.br', '', ''),
       ('Lilian Amparo', 'Díaz Concepción', 'MINERD, Reg. 10', '', 'lilianamparod90@gmail.com', '', ''),
       ('Lilimar', 'Carmona Pizarro', 'O&M', '', 'lcarmona@udoym.edu.do', '', ''),
       ('Linosca Dominga', 'Ulloa Rosario', '', '', 'lnc_girl@hotmail.com', '', ''),
       ('Lizbeth', 'Alvarado Vargas', 'Universidad De Puerto Rico', '', 'lizbeth.alvarado@upr.edu', '', ''),
       ('Lucia', 'Polonia Tavarez', 'MINERD, Reg. 15', '', 'lucia.poloniata@minerd.gob.do', '', ''),
       ('Luciana', 'Olesker', '', '', 'lucianao05@gmail.com', '', ''),
       ('LUCIana', 'Boemer Cesar Pereira', 'UTFPR', '', 'lucianapereira@utfpr.edu.br', '', ''),
       ('Luciana Maria', 'Dias De Ávila Rodrigues', 'Universidade De Brasília', '', 'luavila83@gmail.com', '', ''),
       ('Luis', 'Caceres', 'Universidad De Puerto Rico En Mayaguez', '', 'luis.caceres1@upr.edu', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Luisa', 'Samboy', 'MINERD, Reg. 15', '', 'laminisamboy@gmail.com', '', ''),
       ('Luis Ángel', 'Bohórquez Arenas', 'Universidad Distrital Francisco José De Caldas', '',
        'labohorqueza@udistrital.edu.co', '', ''),
       ('Luis Antonio', 'Soto Hernández', 'Universidad Pedagógica Nacional Francisco Morazán', '', 'lsoto@upnfm.edu.hn',
        '', ''),
       ('Luis Ariel', 'Acosta Rodríguez', '', '', 'luisarielrey23@gmail.com', '', ''),
       ('Luis Armando', 'Hernandez Solis', 'Universidad Estatal A Distancia De Costa Rica', '', 'lhernandez@uned.ac.cr',
        '', ''),
       ('Luis Carlos', 'Arboleda Aparicio', '', '', 'luis.carlos.arboleda@gmail.com', '', ''),
       ('Luis Daniel', 'Torres Lebrón', 'UPR', '', 'luis.torres78@upr.edu', '', ''),
       ('Luis Daniel', 'Cea Sosa', 'MINERD, Reg. 15', '', 'luis.cea@minerd.gob.do', '', ''),
       ('Luis Diego', 'Chavarria Brenes', 'Universidad De Costa Rica', '', 'luis.chavarriabrenes@ucr.ac.cr', '', ''),
       ('Luis Eligio', 'Vasquez Marquez', 'Isfodosu', '', 'luis.vasquez@isfodosu.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Luis Fabián', 'Gutiérrez Fallas', 'Universidad De Costa Rica', '', 'luisfabian.gutierrez@ucr.ac.cr', '', ''),
       ('Luis Humberto', 'Uribe Díaz', 'MINERD, Reg. 15', '', 'humbertouribe653@gmail.com', '', ''),
       ('Luis Manuel', 'Henríquez Grullón', 'PUCMM', '', 'lhenriquez@pucmm.edu.do', '', ''),
       ('Luis Manuel', 'Montero Hernández', 'Universidad Nacional De Costa Rica', '', 'luismanuel1808@gmail.com', '',
        ''),
       ('Luis Miguel', 'Amador Silva', 'UNISON', '', 'luis.amador@unison.mx', '', ''),
       ('Luis Ramón M.', 'García De La Cruz', 'MINERD, Reg. 15', '', 'luisgarcia73@hotmail.com', '', ''),
       ('Luis Sebastião', 'Barbosa Bemme', 'Universidade Franciscana', '', 'luis.bemme@ufn.edu.br', '', ''),
       ('Luiza', 'Ojeda Hoffmann', '', '', 'luizaojeda@hotmail.com', '', ''),
       ('Luz', 'Valoyes Chávez', 'Universidad Católica De Temuco', '', 'lvaloyes@uct.cl', '', ''),
       ('Luz María Rodríguez', 'De Aza', 'MINERD, Reg. 00', '', 'luz.rodriguez@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Luz Marina', 'Alvarez Rojas', '', '', 'luzval1@yahoo.es', '', ''),
       ('Luz Stella', 'Calderon Rebellon', 'Isfodosu', '', 'luz.calderon@isfodosu.edu.do', '', ''),
       ('Luz Vimeiry', 'Gómez De Peña', 'PUCMM', '', 'lvgd0001@ce.pucmm.edu.do', '', ''),
       ('Lyda Constanza', 'Mora Mendieta', '', '', 'lmendieta@pedagogica.edu.co', '', ''),
       ('Maderlyn', 'Silverio Hurtado', 'MINERD, Reg. 11', '', 'maderlynsh@gmail.com', '', ''),
       ('Maderlyn', 'Silverio Hurtado', '', '', 'maderlynsg@gmail.com', '', ''),
       ('Magdalena Waleska', 'Aldana Segura', '', '', 'waldanasegura@gmail.com', '', ''),
       ('Mahsa', 'Allahbakhshi', 'Pontificia Universidad Católica De Chile', '', 'maallahbakhshi@uc.cl', '', ''),
       ('Manuel Alberto', 'Montero Lora', 'PUCMM', '', 'manuelmonterolora@gmail.com', '', ''),
       ('Manuel Arismendy', 'Batista Villa', 'UTECO', '', 'manuelm.batista@uteco.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Manuel Calixto', 'Rodriguez Gonzalez', 'PUCMM', '', 'mca.rodriguez@ce.pucmm.edu.do', '', ''),
       ('Manueliza', 'Rodriguez Encarnación', 'PUCMM', '', 'mxre0002@ce.pucmm.edu.do', '', ''),
       ('Marcela Alejandra', 'Ribas García', '', '', 'marcelaribasgarcia@gmail.com', '', ''),
       ('Marcelina', 'De Paula Manzueta', 'O&M', '', 'mercelabella@gmail.com', '', ''),
       ('Marcelina', 'Piña Del Rosario', 'CHPI', '', 'marcelina.pina@gmail.com', '', ''),
       ('Marcelina  Del Carmen', 'Cigarruista', 'Colegio Jose O. Huertas', '', 'rodrigo.combe@matexam.net', '', ''),
       ('Marcelo', 'Bairral', 'Universidad Federal Rural De Rio De Janeiro', '', 'mbairral@ufrrj.br', '', ''),
       ('Marcia Maria', 'Fusaro Pinto', 'Universidade Federal Do Rio De Janeiro (UFRJ)', '', 'marcia@im.ufrj.br', '',
        ''),
       ('Marcília', 'Cavalcante Viana', 'Fundação Cearense De PesquISA E Cultura/UFC', '', 'marciliaviana80@gmail.com',
        '', ''),
       ('Marcio', 'De Almeida', 'PUC-SP', '', 'marcioalmeidasp@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Marco Vinicio', 'Gutiérrez Montenegro', 'Tecnológico De Costa Rica', '', 'vgutierrez@itcr.ac.cr', '', ''),
       ('Maria', 'Mercedes Cano', 'MINERD, Reg. 02', '', 'mariamercedesc72@gmail.com', '', ''),
       ('María', 'Penkova Vassileva', 'Intec', '', 'maria.penkova@intec.edu.do', '', ''),
       ('María Alejandra', 'Pérez Torres', 'Universidad Distrital Francisco José De Caldas', '',
        'mariaaperez0802@gmail.com', '', ''),
       ('Maria Alice', 'Veiga Ferreira De Souza', 'Instituto Federal Do Espírito Santo', '', 'alicevfs@gmail.com', '',
        ''),
       ('María Altagracia', 'Tavárez Rodríguez', 'Isfodosu', '', 'maria.tavarez@isfodosu.edu.do', '', ''),
       ('María del Carmen', 'Suero Suero', '', '', 'mariadelcarmen.suero@minerd.gov.do', '', ''),
       ('María Del Pilar', 'Álvarez Martín', 'PUCMM', '', 'md.alvarez@ce.pucmm.edu.do', '', ''),
       ('Maria Do Carmo De', 'Sousa', 'Universidade Federal De São Carlos-UFSCAR', '', 'mdcsousa@ufscar.br', '', ''),
       ('Maria Dolores', 'Then Alvarado', 'UCNE', '', 'morynathen@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Maria Eliene', 'Magalhães Da Silva Alves', '', '', 'jacyraufc@gmail.com', '', ''),
       ('María ISAbel', 'Agustín Ramos', 'PUCMM', '', 'miar0001@ce.pucmm.edu.do', '', ''),
       ('Maria José', 'Costa Dos Santos', 'Fundação Cearense De PesquISA E Cultura/UFC', '', 'mazeautomatic@gmail.com',
        '', ''),
       ('María Lissette', 'Carballo Lemus', 'Universidad Rafael Landívar', '', 'mlcarballo@url.edu.gt', '', ''),
       ('Maria Lourdes', 'Veras De Santos', 'UAPA', '', 'mariaveras@f.uapa.edu.do', '', ''),
       ('Maria Madalena', 'Dullius', '', '', 'madalena@univates.br', '', ''),
       ('Mariana', 'Corujo Zubelso', '', '', 'mcorujozubelso@gmail.com', '', ''),
       ('Marianela', 'Alpízar Vargas', 'Universidad Nacional, Costa Rica.', '', 'marianela.alpizar.vargas@una.cr', '',
        ''),
       ('Mariano', 'Agramonte', 'MINERD, Reg. 15', '', 'marianoagramonte1592@gmail.com', '', ''),
       ('Maria Teresa', 'Fernández Blanco', 'Universidad De Santiago De Compostela', '', 'teref.blanco@usc.es', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Maribel', 'Galvá', 'MINERD, Reg. 00', '', 'maribel.galva@minerd.gob.do ', '', ''),
       ('Mariela', 'Encarnación', '', '', 'marielaencarnacion23@gmail.com', '', ''),
       ('Marinelys', 'Peguero', 'MINERD, Reg. 12', '', 'marinelyspeguero383@gmail.com', '', ''),
       ('Marino', 'Brito Guillén', 'Isfodosu', '', 'marino.brito@isfodosu.edu.do', '', ''),
       ('Mario Nicolas', 'Covaleda Olave', '', '', 'nicova9207@gmail.com', '', ''),
       ('Maritza Estella', 'Coba De Chen', 'Universidad Tecnológica De Panamá', '', 'rodrigo.combe@utp.ac.pa', '', ''),
       ('Marli Teresinha', 'Quartieri', 'Universidade Do Vale Do Taquari-UNIVATES', '', 'mtquartieri@univates.br', '',
        ''),
       ('Martha Lima Soares Martins', 'Martha', '', '', 'martalimas12@gmail.com', '', ''),
       ('Martín', 'García Olivo', 'MINERD, Reg. 00', '', 'martín.garcia@minerd.gob.do', '', ''),
       ('Marvin', 'Diaz Mendez', 'MINERD, Reg. 18', '', 'marvin.diaz@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Maryuri', 'Rodriguez', 'MINERD, Reg. 08', '', 'mariajavier497@gmail.com', '', ''),
       ('Mauricio Antonio', 'Hernandez Garcia', 'UAFAM', '', 'hmauricioantonio@gmail.com', '', ''),
       ('Mauri Luís', 'Tomkelski', 'SEDUC/RS E Uricer', '', 'mauriluis@gmail.com', '', ''),
       ('Máxima', 'Méndez Rosa', 'ISA', '', 'mmendez@isa.edu.do', '', ''),
       ('Melissa', 'Vásquez Hernández', 'Isfodosu', '', 'melissavh0611@gmail.com', '', ''),
       ('Miancer David', 'Rubio Abreu', 'MINERD, Reg. 00', '', 'miancer.rubio@minerd.gob.do', '', ''),
       ('Michael Jefree', 'Manzanillo Jiménez', 'PUCMM', '', 'mjmj0001@ce.pucmm.edu.do', '', ''),
       ('Michèle Jeanne', 'Lanne Artigue', 'Université Paris Cité', '', 'michele.artigue@gmail.com', '', ''),
       ('Miguel', 'Onelio de la Rosa', 'MINERD, Reg. 04', '', 'miguel.delarosa@minerd.gob.do', '', ''),
       ('Miguel Ángel', 'Delgado Fernández', 'Universidad Interamericana De Puerto Rico, Recinto De San Germán', '',
        'miguel.delgado2773@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Miguel Antonio', 'Leonardo Sepúlveda', 'Isfodosu', '', 'miguel.leonardo@isfodosu.edu.do', '', ''),
       ('Miguel Antonio', 'Tavares Luis', 'Isfodosu', '', 'miguel.tavares@isfodosu.edu.do', '', ''),
       ('Miguelina Elizabeth', 'Sirí Cabrera', '', '', 'elysirenita@gmail.com', '', ''),
       ('Mikael Cristopher', 'Souza De Barros', '', '', 'mikaelcristopher1@gmail.com', '', ''),
       ('Miledis Teresa', 'Tavarez Marzan', 'UASD', '', 'miledyst@gmail.com', '', ''),
       ('Milvia', 'Roa Familia', 'MINERD, Reg. 10', '', 'milvia .roa@minerd.gob.do', '', ''),
       ('Miranda Elena', 'Lebron De Los Santos', 'PUCMM', '', 'meld0002@ce.pucmm.edu.do', '', ''),
       ('Mireille', 'Saboya', 'Université Du Québec À Montréal', '', 'saboya.mireille@uqam.ca', '', ''),
       ('Mirlandy', 'Bautista García', 'MINERD, Reg. 15', '', 'bmirlandy@gmail.com', '', ''),
       ('Miselanea', 'Perez Gomez', 'MINERD, Reg. 10', '', 'miselania.perezgo@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Mónica Del Rocío', 'Torres Ibarra', 'Universidad Autónoma De Zacatecas', '', 'mtorres@uaz.edu.mx', '', ''),
       ('Myriam Rocío', 'Pallares Muñoz', '', '', 'mrocio03@hotmail.com', '', ''),
       ('Natalia', 'Ruiz López', 'Universidad Autónoma De Madrid', '', 'natalia.ruiz@uam.es', '', ''),
       ('Natalia', 'Chicora', '', '', 'nataliachicora@gmail.com', '', ''),
       ('Nathael', 'Santana Redman', 'MINERD, Reg. 15', '', 'nathael13@gmail.com', '', ''),
       ('Nathalie Silvia', 'Anwandter Cuellar', 'Université Du Québec En Outaouais', '', 'nathalie.anwandter@uqo.ca',
        '', ''),
       ('Neel Lobatchewski', 'Báez Ureña', 'UASD', '', 'nbaez18@uasd.edu.do', '', ''),
       ('Nelson', 'Ortiz Pascual', 'MINERD, Reg. 17', '', 'nelson.ortizpa@minerd.gob.do', '', ''),
       ('Nelson', 'Gómez López', 'UAPA', '', 'nelsongomez@uapa.edu.do', '', ''),
       ('Nereyda', 'Julan Ovilsano', 'MINERD, Reg. 05', '', 'nereyda.julian@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Nestor', 'Montero', 'MINERD, Reg. 10', '', 'nestor.montero@minerd.gob.do/', '', ''),
       ('Newman Yonander', 'Zambrano Leal', 'Isfodosu', '', 'newman.zambrano@issu.edu.do', '', ''),
       ('Nidia Natasha', 'Agüero Paulino', 'MINERD, Reg. 04', '', 'nidianatacha1@gmail.com', '', ''),
       ('Nilsi Nikaury', 'Pichardo Devora', 'MINERD, Reg. 10', '', 'nilsi.pichardo@minerd.gob.do', '', ''),
       ('Ninoska Torres', 'de la Guarda', 'MINERD, Reg. 17', '', 'ninoska.torres@minerd.gob.do', '', ''),
       ('Noelia', 'Saleme', 'Universidad Nacional De Catamarca', '', 'noeliasaleme@unca.edu.ar', '', ''),
       ('Nohemy Marcela', 'Bedoya Ríos', 'Universidad Distrital Francisco José De Caldas', '',
        'nmbedoyar@udistrital.edu.co', '', ''),
       ('Nurkis Amalia', 'Ruiz Nina', 'Unicaribe', '', 'nruiz@unicaribe.edu.do', '', ''),
       ('Olga Lidia', 'Pérez González', 'MESCyT', '', 'olguitapg@gmail.com', '', ''),
       ('Omar Eduardo', 'Castillo Muñoz', 'Univesidad Agroforestal Fernando Arturos De Meriño', '',
        'omarr99c@hotmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Onesimo', 'Valenzuela De Los Santos', 'MINERD, Reg. 15', '', 'onesimoacademico@gmail.com', '', ''),
       ('Orquídea', 'Acevedo', '', '', 'orquideacvd2026@gmail.com', '', ''),
       ('Oscar Alejandro', 'Barrios Candil', 'UPN Colombia', '', 'oscalej2@gmail.com', '', ''),
       ('Osvaldo Jesus', 'Rojas Ve3Lazquez', 'Universidad Antonio Nariño', '', 'orojasv69@uan.edu.co', '', ''),
       ('Otto', 'Manuel Pérez', 'MINERD, Reg. 17', '', 'ottoperez2610@gmail.com', '', ''),
       ('Paco', 'Castillo', 'MINERD, Reg. 01', '', 'poco.castillo@minerd.gob.do', '', ''),
       ('Paola', 'Hidalgo Vargas', 'PUCMM', '', 'nphv0001@ce.pucmm.edu.do', '', ''),
       ('Paola Judith', 'Amaris Ruidiaz', 'Uptc', '', 'paola.amaris@uptc.edu.co', '', ''),
       ('Paola Ximena', 'Valero Dueñas', '', '', 'paola.valero@su.se', '', ''),
       ('Pascual', 'Leocadio', 'UASD', '', 'pleocadio76@uasd.edu.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Pascual Ovidio', 'Hernández Payano', 'MINERD, Reg. 17', '', 'pascual112783@gmail.com', '', ''),
       ('Patricia', 'Maríano', 'MINERD, Reg. 10', '', 'roseiri1096@gmail.com', '', ''),
       ('Patrick', 'Scott', 'CIAEM', '', 'pscott@nmsu.edu', '', ''),
       ('Patrick', 'Gonzales July', 'UPRM', '', 'patrick.gonzales@upr.edu', '', ''),
       ('Paula V', 'Santana Mercado', 'PUCMM', '', 'pv.santana@ce.pucmm.edu.do', '', ''),
       ('Pedro', 'Pimenta', 'Agrupamento De Escolas Da Caparica / Universidade Nova De Lisboa', '',
        'pedropimenta@aecaparica.pt', '', ''),
       ('Penelope', 'Rodríguez Moreta', 'Isfodosu', '', '202230054@issu.edu.do', '', ''),
       ('Perla Maciel', 'Lape', 'PUCMM', '', '20186419@ce.pucmm.edu.do', '', ''),
       ('Perla Nicol', 'Soriano Perez', 'MINERD, Reg. 10', '', 'perlasoriano24@gmail.com', '', ''),
       ('Poliana', 'Figueiredo Cardoso Rodrigues', '', '', 'polianacar@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Rafael', 'Pantoja Rangel', 'Universidad De Guadalajara', '', 'rafael.prangel@academicos.udg.mx', '', ''),
       ('Rafael David', 'Francisco Ventura', 'Isfodosu', '', 'rafael.ventura@isfodosu.edu.do', '', ''),
       ('Rafael Pastor', 'Martinez Vargas', 'Isfodosu', '', 'rafael.martinez@isfodosu.edu.do', '', ''),
       ('Ramiro', 'Rueda', 'Isfodosu', '', 'ramiro.rueda@isfodosu.edu.do', '', ''),
       ('Ramón', 'De Los Santos Suero', 'PUCMM', '', 'r.delossantos@ce.pucmm.edu.do', '', ''),
       ('Ramón Alexis Moreno', 'De Los Santos', 'MINERD, Reg. 17', '', 'alexismoreno1001@gmail.com', '', ''),
       ('Ramón Aridio', 'Cueto Mejia', 'PUCMM', '', 'aridiocm@hotmail.com', '', ''),
       ('Ramón Bienvenido', 'de la Cruz Marte', 'MINERD, Reg. 10', '', 'ramonb38@hotmail.com', '', ''),
       ('Raquel', 'Carneiro Dörr', 'Universidade De Brasília', '', 'raqueldorr@unb.br', '', ''),
       ('Reiman', 'Acuña Chacón', 'Tecnológico De Costa Rica', '', 'reiacuna@itcr.ac.cr', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Reina Altagracia', 'Taveras', 'UASD', '', 'rtaveras22@uasd.edu.do', '', ''),
       ('Reina María', 'Cuevas Peña', 'MINERD, Reg. 04', '', 'reina.cuevas@minerd.gob.do', '', ''),
       ('Reinier', 'Abreu Naranjo', 'Universidad Estatal Amazónica', '', 'rabreu@uea.edu.ec', '', ''),
       ('Reiny', 'Rojas', 'PUCMM', '', 'rarg0004@ce.pucmm.edu.do', '', ''),
       ('Ricardo', 'Poveda Vásquez', 'UNA', '', 'ricardopovedav@gmail.com', '', ''),
       ('Robert', 'Naveo Hernandez', 'PUCMM', '', 'rxnh0001@ce.pucmm.edu.do', '', ''),
       ('Roberto', 'Mejía', 'MINERD, Reg. 10', '', 'md07roberto@gmail.com', '', ''),
       ('Roberto', 'Lantigua Pereyra', 'MINERD, Reg. 15', '', 'lantigua29@hotmail.com', '', ''),
       ('Roberto Carlos', 'Torres Peña', '', '', 'rtorres@unimagdalena.edu.co', '', ''),
       ('Rodrigo Yoel', 'Combe Aparicio', 'Universidad De Panamá', '', 'rcombe11@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Rogel Rafael', 'Rojas Bello', 'Isfodosu', '', 'rogel.rojas@isfodosu.edu.do', '', ''),
       ('Ronald Javier', 'Quesada Cordova', 'Universidad De Lima', '', 'rquesada@ulima.edu.pe', '', ''),
       ('Rosa', 'Esther Pierre', 'MINERD, Reg. 10', '', 'proferosapierre@gmail.com', '', ''),
       ('Rosa Herminia', 'Mirabal Paulino', 'PUCMM', '', 'rh.mirabal@ce.pucmm', '', ''),
       ('Rosaida', 'Andujar Fermin', 'MINERD, Reg. 14', '', 'rosaida.andujar@minerd.gob.do', '', ''),
       ('Rosa María', 'Almonte Batista', 'UASD', '', 'ralmonte49@uasd.edu.do', '', ''),
       ('Rosana', 'Soares Pinheiro', '', '', 'pfrosana@gmail.com', '', ''),
       ('Rosanna Mártires', 'Zapata Casado', 'MINERD, Reg. 03', '', 'rosanna.zapata@minerd.gob.do', '', ''),
       ('Rosely', 'Meran Ramirez', 'PUCMM', '', 'larossi0417@gmail.com', '', ''),
       ('Rossy Danny', 'Reyes Gonzalez', 'MINERD, Reg. 10', '', 'rossyreyes6@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Roxana', 'Cabrera Puig.', '', '', 'roxycabrera706@gmail.com', '', ''),
       ('Rudy M.', 'López Matos', 'MINERD, Reg. 01', '', 'rudi.lopez@minerd.gob.do', '', ''),
       ('Rui', 'Seimetz', 'Universidade De Brasília', '', 'rseimetz@unb.br', '', ''),
       ('Sadsa', 'Sssas', 'UCI', '', '2212@gmail.com', '', ''),
       ('Saghasiehany', 'De Jesús Bencosme', 'MINERD, Reg. 00', '', 'saghasiehany.dejesus@minerd.gob.do', '', ''),
       ('Salvador', 'José Antonio', 'UFSCAR', '', 'jasalvador@ufscar.br', '', ''),
       ('Salvador', 'Llinares', 'Universidad De Alicante', '', 'salvadorllc@gmail.com', '', ''),
       ('Samuel', 'Perez', 'MINERD, Reg. 04', '', 'samuelpvizcaino565@gmail.com', '', ''),
       ('Sandra A.', 'Peña Matos', 'MINERD, Reg. 15', '', 'lic.sandramatos@gmail.com', '', ''),
       ('Sandra Marcela', 'Vera', 'IES Estanislao Maldones', '', 'verasandramarcela@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Sandra Yolima', 'Ruiz Yacumal', 'Universidad Del Cauca, Colombia', '', 'sandray@unicauca.edu.co', '', ''),
       ('Santa Daysi', 'Sánchez González', '', '', 'sanchez.daysi@gmail.com', '', ''),
       ('Santa Gribel', 'Azor King', 'MINERD, Reg. 00', '', 'santa.azor@minerd.gob.do', '', ''),
       ('Santo', 'Franco Bautista', 'MINERD, Reg. 04', '', 'santo.franco@minerd.gob.do', '', ''),
       ('Santos', 'Concepción Fernández', 'MINERD, Reg. 07', '', 'santos.concepcionfe@minerd.gob.do', '', ''),
       ('Sarah Esther Calderón', 'De Coronado', 'MINERD, Reg. 15', '', 'sarah2027c@gmail.com', '', ''),
       ('Sara Ynes', 'González Sued', 'PUCMM', '', 'sarahgonzalez@pucmm.edu.do', '', ''),
       ('Saúl Eduardo', 'Méndez Larios', 'Mathkind Global', '', 'saul@mathkind.org', '', ''),
       ('Scarlin Aurora', 'Martínez Herrera', 'PUCMM', '', 'samh0001@ce.pucmm.edu.do', '', ''),
       ('Sheila Elizabeth', 'De La Rosa Silvestre', 'MINERD, Reg. 10', '', 'silvestresheila2@gmail', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Sibeli', 'Da Rosa Da Rocha', 'Universidade Federal Do Paraná (ufpr)', '', 'sibarocha02@gmail.com', '', ''),
       ('Silmara Louise Da Silva', 'Silmara Louise', 'IFTM Instituto Federal Do Triângulo Mineiro Campus Paracatu', '',
        'silmaraba10@gmail.com', '', ''),
       ('Silsi Maria', 'Ortiz Albuez', 'MINERD, Reg. 17', '', 'silsi.ortiz@minerd.gob.do', '', ''),
       ('Silverio', 'Pérez García', 'MINERD, Reg. 01', '', 'silverio.perez@minerd.gob.do', '', ''),
       ('Silvia', 'Frizzarini', 'UDESC', '', 'silvia.frizzarini@udesc.br', '', ''),
       ('Silvia Gabriela', 'Pérez', 'Gpdm-IFDC', '', 'perezdaq@gmail.com', '', ''),
       ('Sobeida', 'Antonia Nuñez', 'MINERD, Reg. 03', '', 'sobeida.nunez@minerd.gob.do', '', ''),
       ('Sonia Ximena Nivia', 'Cordero Cárdenas', 'Universidad Mayor De San Andrés', '', 'soniacordero3r@gmail.com', '',
        ''),
       ('Soraya Eugenia', 'Pol', '', '', 'sorayaepol@gmail.com', '', ''),
       ('Stephany', 'Gil Sanchez', 'MINERD, Reg. 10', '', 'stephanygilsanchez@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Stephany', 'Quevedo Cortorreal', 'PUCMM', '', 'stephanyquevedo45@gmail.com', '', ''),
       ('Steven Josué', 'Rodríguez Gómez', 'Universidad De Costa Rica', '', 'steven.rodriguezgomez@ucr.ac.cr', '', ''),
       ('Sylvia', 'Celedon-Pattichis', 'University Of Texas At Austin', '', 'sylvia.celedon@austin.utexas.edu', '', ''),
       ('Tania Azucena', 'Chicalote Jiménez', 'UNAM', '', 'tazjimenez@ciencias.unam.mx', '', ''),
       ('Tania Beatriz', 'Cordero Javier', 'MINERD, Reg. 10', '', 'taniacordero1723@gmail.com', '', ''),
       ('Teovaldo', 'García Romero', 'Universidad Popular Del Cesar-COLOMBIA', '', 'teovaldogarcia@gmail.com', '', ''),
       ('Teresa de Jesus', 'Lima de Santana', 'MINERD, Reg. 15', '', 'coordinadorateresalima01@gmail.com', '', ''),
       ('Teresa Yocelyn', 'Matos Garcia', 'MINERD, Reg. 15', '', 'teresamatos@cepmsd.edu.do', '', ''),
       ('Teudis', 'Santana Meran', 'MINERD, Reg. 15', '', 'teudisantanameran@gmail.com', '', ''),
       ('Thais', 'Machado', 'Universidade De Brasília (UNB)', '', 'thaisrfm013@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Tirso Del Jesús', 'Figuereo Guerrero', 'MINERD, Reg. 15', '', 'tirso.figuereo@docente.edu.do', '', ''),
       ('Valeria', 'Ocoro Rebolledo', '', '', 'valeria.ocoro@correounivalle.edu.co', '', ''),
       ('Valery Dahian', 'Liriano Cruz', 'PUCMM', '', 'vd.liriano@ce.pucmm.edu.do', '', ''),
       ('Vanilde', 'Bisognin', 'Universidade Franciscana-UFN', '', 'vanilde@ufn.edu.br', '', ''),
       ('Verónica Cecilia', 'Easton Perotti', '', '', 'veaston@claeh.edu.uy', '', ''),
       ('Vìctor', 'R. Nùñez', 'MINERD, Reg. 14', '', 'victor.nunez@minerd.gob.do ', '', ''),
       ('Victor Alfonso', 'García Aracena', 'MINERD, Reg. 15', '', 'profesormatvictorgarcia@gmail.com', '', ''),
       ('Víctor José', 'Galán Céspedes', 'UTECO', '', 'victorj.galan@uteco.edu.do', '', ''),
       ('Víctor Manuel', 'Féliz Méndez', 'MINERD, Reg. 01', '', 'victor.feliuz@minerd.gob.do', '', ''),
       ('Víctor Roldan', 'Núñez Vásquez', '', '', 'victor.nunez@minerd.gob.do ', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Vidal', 'Rodriguez Del Carmen', 'O&M', '', 'vrodriguez@udoym.edu.do', '', ''),
       ('Vienbenida', 'Igualada Cortez', 'Universidad De Panamá', '', 'vienbenida27@gmail.com', '', ''),
       ('Vilma Elizabeth', 'Enciso Gavilán', '', '', 'elizaenci@gmail.com', '', ''),
       ('Vivian Libeth', 'Uzuriaga López', 'Universidad Tecnológica De Pereira', '', 'vuzuriaga@utp.edu.co', '', ''),
       ('Vladiana', 'Costa Dos Santos', '', '', 'vladyanasantos@gmail.com', '', ''),
       ('Wander Francisco', 'Lara Medina', 'PUCMM', '', 'wflm0001@ce.pucmm.edu.do', '', ''),
       ('Wellington Fernando', 'Valenzuela Perez', 'Unicaribe', '', 'wellington.valenzuela@unicaribe.edu.do', '', ''),
       ('Wendy Alt.', 'Mejía Aybar', 'MINERD, Reg. 17', '', 'wendy.mejia@minerd.gob.do', '', ''),
       ('Wendy Altagracia', 'Mejia Aybar', 'MINERD, Reg. 17', '', 'wendyaltagraciamejiaaybar@gmail.com', '', ''),
       ('Wendy Carolina', 'Carolina Hernàndez', 'MINERD, Reg. 15', '', 'wencar895@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Wildebrando', 'Miranda Vargas', 'Universidad Del Valle', '', 'wildebrando.miranda@correounivalle.edu.co', '',
        ''),
       ('Wilfredo', 'Marte FortUNAto', 'Isfodosu', '', 'wilfredo.marte@isfodosu.edu.do', '', ''),
       ('William', 'Vieira', 'IFSP Guarulhos', '', 'wvieira@ifsp.edu.br', '', ''),
       ('William Stevens', 'Perea Diaz', '', '', 'william.perea@correounivalle.edu.co', '', ''),
       ('Wilmary', 'Gómez Soto', 'PUCMM', '', 'wxgs0002@ce.pucmm.edu.do', '', ''),
       ('Wilmer Lucidio', 'Arzolay Abreu', 'Isfodosu', '', 'wilmer.arzolay@isfodosu.edu.do', '', ''),
       ('Wilson', 'Rodríguez Calderón', 'ESAP', '', 'wilroca50@hotmail.com', '', ''),
       ('Wilson LUCIlo', 'Heredia Amparo', 'UTECO', '', 'wilsonl.heredia@uteco.edu.do', '', ''),
       ('Wirlenia', 'Marrero Cepeda', 'PUCMM', '', 'wxmc0001@ce.pucmm.edu.do', '', ''),
       ('Yadira', 'Sanabria Mejía', 'Fundación Universitaria Salesiana', '', 'yadira.sanabriam@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Yadira', 'Sanabria', 'Salesiana', '', 'yadira.sanabria@salesiana.edu.co', '', ''),
       ('Yajaira', 'Manzueta Manzueta', 'PUCMM', '', 'yxmm0003@ce.pucmm.edu.do', '', ''),
       ('Yaneris', 'Polanco Rosario', 'MINERD, Reg. 10', '', 'yanerispolqnco14@gmail.com', '', ''),
       ('Yasmiris Daiana', 'Calvo Volquez', 'MINERD, Reg. 10', '', 'daianaclv@gmail.com', '', ''),
       ('Yeison Osvaldo', 'Rodriguez Rojas', '', '', 'yeisonosvaldo.rodriguez@upr.edu', '', ''),
       ('Yesenia Maribel', 'Santamaria Leyba', 'MINERD, Reg. 17', '', 'yesenia.santa@minerd.gob.do', '', ''),
       ('Yesenia Maribel', 'Santamaría Leyba', 'MINERD, Reg. 17', '', 'yesenia.santa@minerd.gob.do', '', ''),
       ('Yesica Dayan', 'Audor Marmolejo', 'Institución Educativa María Auxiliadora', '', 'artembera.sevilla@gmail.com',
        '', ''),
       ('Yetcenia', 'Licett Pérez', 'MINERD, Reg. 03', '', 'yetcenia.diaz@minerd.gob.do', '', ''),
       ('Yeuris', 'Suares', 'MINERD, Reg. 10', '', 'yeuris.suarez@minerd.gob.do', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Yilenny Isabel', 'Sosa Santos', '', '', 'sosayilenny@gmail.com', '', ''),
       ('Yilmar Stiven', 'Barreto Rodriguez', '', '', 'yilmar.barreto@correounivalle.edu.co', '', ''),
       ('Yoandri', 'Romano', 'MINERD, Reg. 05', '', 'sofonias_hageos@hotmail.com', '', ''),
       ('Yobanes Cabrera', 'De La Rosa', 'MINERD, Reg. 15', '', 'segundinooperaciones@gmail.com', '', ''),
       ('Yojana', 'Rivera Disla', 'MINERD, Reg. 17', '', 'yojanariveradisla@gmail.com', '', ''),
       ('Yordalisa del Rosario', 'De los Santos', 'MINERD, Reg. 17', '', 'yorda147delrosario@gmail.com', '', ''),
       ('Yugelis', 'De La Rosa Mendez', 'MINERD, Reg. 18', '', 'yugelis.delarosa@minerd.gob.do', '', ''),
       ('Yuri', 'Morales Lopez', 'Universidad Nacional', '', 'yurimoralesl@yahoo.com', '', ''),
       ('Yuriko', 'Baldin', 'Universidade Federal De São Carlos', '', 'yuriko@ufscar.br', '', ''),
       ('Yvelise', 'de Jesús Silverio', 'MINERD, Reg. 07', '', 'yvelisedejesussilverio@gmail.com', '', '');
INSERT INTO attender ("name", last_name, company, title, email, phone, country)
VALUES ('Yvette', 'Rivera Martínez', 'Universidad Interamericana De Puerto Rico, Recinto De Ponce', '',
        'yriveram@ponce.inter.edu', '', ''),
       ('Zaida Altagracia', 'De Jesús Guzmán', 'Intec', '', 'zaida.dejesus@intec.edu.do', '', ''),
       ('Zaida Margot', 'Santa Ramírez', 'Universidad De Antioquia', '', 'zaida.santa@udea.edu.co', '', '');

