INSERT INTO speakers (name, title, company, country, bio, networking, photo)
VALUES ('Álvaro Lecompte-Montes', '', '', 'PR', '', '[]', null),
       ('Aarón Álvarez Araujo', '', '', 'ES', '', '[]', null),
       ('Abel Adrián Robledo Carrillo', '', '', 'MX', '', '[]', null),
       ('Adão José Martins Dedé', '', '', 'BR', '', '[]', null),
       ('Adelita Postiglioni Nunes', '', '', 'BR', '', '[]', null),
       ('Adrián Gómez Árciga', '', '', 'MX', '', '[]', null),
       ('Adriana Breda', '', '', 'ES', '', '[]', null),
       ('Adriana Richit', '', '', 'BR', '', '[]', null),
       ('Adriana Santos', '', '', 'DO', '', '[]', null),
       ('Adriana Toxtle Colotl', '', '', 'MX', '', '[]', null),
       ('Agostinho Iaqchan Ryokiti Homa', '', '', 'BR', '', '[]', null),
       ('Agueda Nicole Báez Jiménez', '', '', 'DO', '', '[]', null),
       ('Agustín Prieto Carmona', '', '', 'ES', '', '[]', null),
       ('Aileen Velázquez Estrella', '', '', 'PR', '', '[]', null),
       ('Ainhoa Berciano', '', '', 'ES', '', '[]', null),
       ('Aitana Martín-Ferraz', '', '', 'ES', '', '[]', null),
       ('Alberto Zapatera Llinares', '', '', 'ES', '', '[]', null),
       ('Alcibiades Medina', '', '', 'PA', '', '[]', null),
       ('Aldo Parra', '', '', 'CO', '', '[]', null),
       ('Alejandra Duque Molina', '', '', 'CO', '', '[]', null),
       ('Alejandra Idárraga Rincón', '', '', 'CO', '', '[]', null),
       ('Alejandra Marín Ríos', '', '', 'CO', '', '[]', null),
       ('Alejandra Sánchez Ávila', '', '', 'CR', '', '[]', null),
       ('Alejandro Díaz Llano', '', '', 'CO', '', '[]', null),
       ('Alejandro Martínez Acosta', '', '', 'CO', '', '[]', null),
       ('Alejandro Rosas Mendoza', '', '', 'MX', '', '[]', null),
       ('Alessandro Jacques Ribeiro', '', '', 'BR', '', '[]', null),
       ('Alex Montecino', '', '', 'CL', '', '[]', null),
       ('Alex Sandro de Castilho', '', '', 'BR', '', '[]', null),
       ('Alexánder Hernández Hernández', '', '', 'ES', '', '[]', null),
       ('Alexander Paredes Martínez', '', '', 'CO', '', '[]', null),
       ('Alexandre Xavier dos Santos', '', '', 'BR', '', '[]', null),
       ('Alfonso Romero Huertas', '', '', 'CO', '', '[]', null),
       ('Aline Cristyna Gonzaga Alves', '', '', 'BR', '', '[]', null),
       ('Allan Gen Palma', '', '', 'CR', '', '[]', null),
       ('Alma Soto Castillo', '', '', 'MX', '', '[]', null),
       ('Aluska Dias Ramos de Macedo Silva', '', '', 'BR', '', '[]', null),
       ('Alvaro Lecompte', '', '', 'PR', '', '[]', null),
       ('Amabile Jeovana Neiris Mesquita', '', '', 'BR', '', '[]', null),
       ('Amador Augusto Paredes Chavez', '', '', 'PE', '', '[]', null),
       ('Ana Carolina Castro', '', '', 'BR', '', '[]', null),
       ('Ana Edith Varela', '', '', 'PA', '', '[]', null),
       ('Ana Helvia Quintero', '', '', 'PR', '', '[]', null),
       ('Ana María Torres Blanco', '', '', 'CO', '', '[]', null),
       ('Ana Maroto Sáez', '', '', 'ES', '', '[]', null),
       ('Ana Mercedes Báez', '', '', 'DO', '', '[]', null),
       ('Ana Paola Castillo Domenech', '', '', 'EC', '', '[]', null),
       ('Ana Sofía Montenegro Arango', '', '', 'CO', '', '[]', null),
       ('Analía Bergé', '', '', 'CA', '', '[]', null),
       ('André Luis Trevisan', '', '', 'BR', '', '[]', null),
       ('Andrea Alejandra Díaz Amaro', '', '', 'MX', '', '[]', null),
       ('Andrea Araya Chacón', '', '', 'CR', '', '[]', null),
       ('Andrea Milena Osorio Cárdenas', '', '', 'CO', '', '[]', null),
       ('Andrea Pinto Vergara', '', '', 'CL', '', '[]', null),
       ('Andrea Vergara Gómez', '', '', 'CL', '', '[]', null),
       ('Andréia Araújo de Farias Aquino', '', '', 'BR', '', '[]', null),
       ('Andrés Felipe Betancourth López', '', '', 'CO', '', '[]', null),
       ('Andrés Felipe Suárez Zuleta', '', '', 'CO', '', '[]', null),
       ('Andrés Fernando Mosquera Díaz', '', '', 'CO', '', '[]', null),
       ('Andrés Navas', '', '', 'CL', '', '[]', null),
       ('Andres Valdés Retamal', '', '', 'CL', '', '[]', null),
       ('Àngela Buforn', '', '', 'ES', '', '[]', null),
       ('Angela Gabriela Beltrán Cavazos', '', '', 'MX', '', '[]', null),
       ('Angie Vega', '', '', 'CR', '', '[]', null),
       ('Angy Carelly Coronel-Suárez', '', '', 'PR', '', '[]', null),
       ('Antía Fernández López', '', '', 'ES', '', '[]', null),
       ('António Domingos', '', '', 'PT', '', '[]', null),
       ('Antonio Marcos Justino Matias', '', '', 'BR', '', '[]', null),
       ('Antonio Oliveira Carlos', '', '', 'BR', '', '[]', null),
       ('Antonio Rey Roque', '', '', 'CU', '', '[]', null),
       ('Antonio Rivero', '', '', 'DO', '', '[]', null),
       ('Antony Guzmán', '', '', 'DO', '', '[]', null),
       ('Ariana I Rodríguez Flores', '', '', 'PR', '', '[]', null),
       ('Ariana Kazumi Mayuri Jimenez', '', '', 'PE', '', '[]', null),
       ('Ariana Paola Lozano Campos', '', '', 'CR', '', '[]', null),
       ('Arnaldo Dias Ferreira', '', '', 'BR', '', '[]', null),
       ('Augusta Osorio Gonzales', '', '', 'PE', '', '[]', null),
       ('Aura Taramuel Cuaical', '', '', 'CO', '', '[]', null),
       ('Aury Rafael Pérez Cuevas', '', '', 'DO', '', '[]', null),
       ('Bárbara Campos', '', '', 'DO', '', '[]', null),
       ('Beatriz Adriana Flores López', '', '', 'MX', '', '[]', null),
       ('Beatriz Horst Figueira', '', '', 'BR', '', '[]', null),
       ('Beatriz Vargas Dorneles', '', '', 'BR', '', '[]', null),
       ('Benilda María Cantillo-Rudas', '', '', 'CO', '', '[]', null),
       ('Blanca Esthela Ledezma Durán', '', '', 'MX', '', '[]', null),
       ('Bolívar Alonso Ramírez Santamaría', '', '', 'CR', '', '[]', null),
       ('Brayan Ricardo Andrade Zambrano', '', '', 'CO', '', '[]', null),
       ('Brigitte Johana Sanchez Robayo', '', '', 'CO', '', '[]', null),
       ('Bruno de Moraes Turci', '', '', 'BR', '', '[]', null),
       ('Caíque Oliveira', '', '', 'BR', '', '[]', null),
       ('Camila Peres Nogues', '', '', 'BR', '', '[]', null),
       ('Camilo Andrés Rodríguez-Nieto', '', '', 'CO', '', '[]', null),
       ('Caridad Espinal Matías', '', '', 'DO', '', '[]', null),
       ('Carina Rivera Londoño', '', '', 'CO', '', '[]', null),
       ('Carla Damisa', '', '', 'UY', '', '[]', null),
       ('Carlos Eduardo Guerrero Cuy', '', '', 'CO', '', '[]', null),
       ('Carlos Flores', '', '', 'DO', '', '[]', null),
       ('Carlos Mario Jaramillo López', '', '', 'CO', '', '[]', null),
       ('Carlos Martínez-Bonilla', '', '', 'PR', '', '[]', null),
       ('Carlos Rojas Bruna', '', '', 'CL', '', '[]', null),
       ('Carlos Sánchez Fernández', '', '', 'CU', '', '[]', null),
       ('Carlos Vargas', '', '', 'PA', '', '[]', null),
       ('Carmen Caiseda', '', '', 'PR', '', '[]', null),
       ('Carmen Miguelina Santos Abreu', '', '', 'DO', '', '[]', null),
       ('Carmen Rodríguez Poveda', '', '', 'PA', '', '[]', null),
       ('Carmen Vieira Mathias', '', '', 'BR', '', '[]', null),
       ('Carolina Archila Prada', '', '', 'CO', '', '[]', null),
       ('Carolina Carrillo García', '', '', 'MX', '', '[]', null),
       ('Carolina Ruminot', '', '', 'CA', '', '[]', null),
       ('Caroline Lajoie', '', '', 'CA', '', '[]', null),
       ('Cassiana Mendes Jacques', '', '', 'BR', '', '[]', null),
       ('Catalina Molano Carranza', '', '', 'CO', '', '[]', null),
       ('Catalina Palacios Bezama', '', '', 'CL', '', '[]', null),
       ('Celia Elizabeth Villagra', '', '', 'AR', '', '[]', null),
       ('Celina Aparecida Almeida Pereira Abar', '', '', 'BR', '', '[]', null),
       ('Ceneida Fernández Verdú', '', '', 'ES', '', '[]', null),
       ('César Guillermo Rendón Mayorga', '', '', 'CO', '', '[]', null),
       ('Christian Alfaro Carvajal', '', '', 'CR', '', '[]', null),
       ('Claudia Gallegos Anaya', '', '', 'MX', '', '[]', null),
       ('Claudia Ines Horn', '', '', 'BR', '', '[]', null),
       ('Claudia Lisete Oliveira Groenwald', '', '', 'BR', '', '[]', null),
       ('Claudia Matus Zúñiga', '', '', 'CL', '', '[]', null),
       ('Claudia Vargas', '', '', 'CL', '', '[]', null),
       ('Comité Organizador Local', '', '', 'DO', '', '[]', null),
       ('Cristian Andrés Ortega Aguilar', '', '', 'CR', '', '[]', null),
       ('Cristian Mauricio Arias Aristizábal', '', '', 'CO', '', '[]', null),
       ('Cristian Quesada Fernández', '', '', 'CR', '', '[]', null),
       ('Cristina Costa', '', '', 'PT', '', '[]', null),
       ('Cristina Teixeira', '', '', 'BR', '', '[]', null),
       ('Cristina Trigo Martínez', '', '', 'ES', '', '[]', null),
       ('Crystal Kalinec-Craig', '', '', 'US', '', '[]', null),
       ('Daiver Vélez Ramos', '', '', 'PR', '', '[]', null),
       ('Daniel Fernando Castillo Vázquez', '', '', 'MX', '', '[]', null),
       ('Daniel Moreno Caicedo', '', '', 'CO', '', '[]', null),
       ('Daniela Pages', '', '', 'UY', '', '[]', null),
       ('Danitza Soledad Mirabal Aybar', '', '', 'DO', '', '[]', null),
       ('Dannael Carrero Pellicier', '', '', 'PR', '', '[]', null),
       ('Danny Esteban Ramírez Lobo', '', '', 'CR', '', '[]', null),
       ('Darly Alina Kú Euán', '', '', 'MX', '', '[]', null),
       ('Darwin Alexander Moreno Gatica', '', '', 'GT', '', '[]', null),
       ('Darwin Peña González', '', '', 'CO', '', '[]', null),
       ('David Enrique Uribe Suarez', '', '', 'CO', '', '[]', null),
       ('David Fernando Méndez Vargas', '', '', 'CO', '', '[]', null),
       ('Delvi Antonio Polanco Adames', '', '', 'DO', '', '[]', null),
       ('Denise Deyanira Chamorro Manríquez', '', '', 'CL', '', '[]', null),
       ('Diana Carolina Pineda Pérez', '', '', 'BR', '', '[]', null),
       ('Diana Hernández Rivera', '', '', 'MX', '', '[]', null),
       ('Diego Lieban', '', '', 'BR', '', '[]', null),
       ('Domingo Felipe Aráuz Chévez', '', '', 'NI', '', '[]', null),
       ('Dulce Rodríguez', '', '', 'DO', '', '[]', null),
       ('Dumas Manzano Franco', '', '', 'CO', '', '[]', null),
       ('Eddie Arrieta-Arrieta', '', '', 'PR', '', '[]', null),
       ('Edgar Alberto Guacaneme Suárez', '', '', 'CO', '', '[]', null),
       ('Edgar Esaúl Saucedo Becerra', '', '', 'MX', '', '[]', null),
       ('Edilaine Damann da Luz Silva', '', '', 'BR', '', '[]', null),
       ('Edith Marcela Chorolque', '', '', 'AR', '', '[]', null),
       ('Edmar Reis Thiengo', '', '', 'BR', '', '[]', null),
       ('Eduardo Basurto', '', '', 'MX', '', '[]', null),
       ('Eduardo Emiliano Muñoz Ortiz', '', '', 'CR', '', '[]', null),
       ('Eduardo Iván Mancera', '', '', 'MX', '', '[]', null),
       ('Eduardo Luna', '', '', 'DO', '', '[]', null),
       ('Eduardo Quevedo', '', '', 'ES', '', '[]', null),
       ('Edwan Ariza-Echeverri', '', '', 'CO', '', '[]', null),
       ('Edwin Chaves', '', '', 'CR', '', '[]', null),
       ('Edwin Pertuz Barón', '', '', 'CO', '', '[]', null),
       ('Eithel Trigueros Rodríguez', '', '', 'CR', '', '[]', null),
       ('Elcio Pasolini Milli', '', '', 'BR', '', '[]', null),
       ('Eleni Bisognin', '', '', 'BR', '', '[]', null),
       ('Eliane Maria de Oliveira Araman', '', '', 'BR', '', '[]', null),
       ('Eliecer Cedeño', '', '', 'PA', '', '[]', null),
       ('Élise Abdallah', '', '', 'CA', '', '[]', null),
       ('Elizabeth Advíncula Clemente', '', '', 'PE', '', '[]', null),
       ('Elizabeth Torres Puentes', '', '', 'CO', '', '[]', null),
       ('Ellery Chacuto López', '', '', 'CO', '', '[]', null),
       ('Emily Caroline Felix Cordeiro', '', '', 'BR', '', '[]', null),
       ('Eric Figueroa González', '', '', 'PR', '', '[]', null),
       ('Eric Ricardo Padilla Mora', '', '', 'CR', '', '[]', null),
       ('Ernesto Geovani Figueroa-González', '', '', 'MX', '', '[]', null),
       ('Eruin Alonso Sánchez Ordóñez', '', '', 'CO', '', '[]', null),
       ('Eulalia Calle', '', '', 'EC', '', '[]', null),
       ('Eurivalda Ribeiro Dos Santos Santana', '', '', 'BR', '', '[]', null),
       ('Evania Vergara Jaramillo', '', '', 'CL', '', '[]', null),
       ('Evarista Matías', '', '', 'DO', '', '[]', null),
       ('Evelio Bedoya Moreno', '', '', 'CO', '', '[]', null),
       ('Fabián Enrique Martínez Valencia', '', '', 'CO', '', '[]', null),
       ('Fabián Gutiérrez Fallas', '', '', 'CR', '', '[]', null),
       ('Fabiana Ramos Savani', '', '', 'BR', '', '[]', null),
       ('Fabio Echeverry Pérez', '', '', 'CO', '', '[]', null),
       ('Fabiola Arrivillaga Hurtado', '', '', 'GT', '', '[]', null),
       ('Federico De Olivera Lamas', '', '', 'UY', '', '[]', null),
       ('Felipe Leite Granato', '', '', 'BR', '', '[]', null),
       ('Felismina de Sousa Neta', '', '', 'BR', '', '[]', null),
       ('Felix Andrés Luna Chavarría', '', '', 'CO', '', '[]', null),
       ('Felix De la Cruz Serrano', '', '', 'PE', '', '[]', null),
       ('Fernanda Drummond Pequeno Valadão', '', '', 'BR', '', '[]', null),
       ('Fernando Hitt', '', '', 'CA', '', '[]', null),
       ('Filánder Sequeira Chavarría', '', '', 'CR', '', '[]', null),
       ('Flavia Fabiani Marcatto', '', '', 'BR', '', '[]', null),
       ('Flor Monserrat Rodríguez-Vásquez', '', '', 'MX', '', '[]', null),
       ('Franciele Santos Teixeira', '', '', 'BR', '', '[]', null),
       ('Francisco Regis Vieira Alves', '', '', 'BR', '', '[]', null),
       ('Francy Paola González Castelblanco', '', '', 'CO', '', '[]', null),
       ('Franklin Astudillo Villalba', '', '', 'DO', '', '[]', null),
       ('Fredy Rivadeneira-Loor', '', '', 'EC', '', '[]', null),
       ('Gabriel dos Santos e Silva', '', '', 'BR', '', '[]', null),
       ('Gabriel Pacheco', '', '', 'BR', '', '[]', null),
       ('Gabriela Gómez Pasquali', '', '', 'PY', '', '[]', null),
       ('Geison Duvan Gómez A.', '', '', 'CO', '', '[]', null),
       ('Gemma Sala-Sebastià', '', '', 'ES', '', '[]', null),
       ('Geovanny Arturo Lachapell Maldonado', '', '', 'DO', '', '[]', null),
       ('Geraldo Eustáquio Moreira Geraldo Eustáquio', '', '', 'BR', '', '[]', null),
       ('German Cadavid Arango', '', '', 'CO', '', '[]', null),
       ('Germania Jiménez Sánchez', '', '', 'DO', '', '[]', null),
       ('Giane Fernanda Schneider Gross', '', '', 'BR', '', '[]', null),
       ('Gilbert A. Valverde', '', '', 'US', '', '[]', null),
       ('Gilberto Chavarría Arroyo', '', '', 'CR', '', '[]', null),
       ('Gilberto Obando', '', '', 'CO', '', '[]', null),
       ('Gloria Nancy Blandón', '', '', 'CO', '', '[]', null),
       ('Glory Bel Pérez Reyes', '', '', 'DO', '', '[]', null),
       ('Guilherme Gonçalo Nogueira', '', '', 'BR', '', '[]', null),
       ('Guillermo Enrique Ramírez Montes', '', '', 'CR', '', '[]', null),
       ('Héctor Alonso Rosas Álvarez', '', '', 'MX', '', '[]', null),
       ('Héctor Gerardo Sánchez Bedoya', '', '', 'CO', '', '[]', null),
       ('Heidy Gómez', '', '', 'SY', '', '[]', null),
       ('Helen Alfaro Víquez', '', '', 'CR', '', '[]', null),
       ('Helen Guillén Oviedo', '', '', 'CR', '', '[]', null),
       ('Helmer Jesús Ruiz Diaz', '', '', 'CO', '', '[]', null),
       ('Henry Alexander Ramírez Bernal', '', '', 'CO', '', '[]', null),
       ('Hilario Ernesto Gallo Cajina', '', '', 'NI', '', '[]', null),
       ('Hildebrando Díaz Soler', '', '', 'CO', '', '[]', null),
       ('Hugo Alvarado', '', '', 'CL', '', '[]', null),
       ('Ieda Maria Giongo', '', '', 'BR', '', '[]', null),
       ('Ignacio Antonio Rodríguez Pérez', '', '', 'DO', '', '[]', null),
       ('Igor dos Santos Lima', '', '', 'BR', '', '[]', null),
       ('Igor Rocha Siqueira', '', '', 'BR', '', '[]', null),
       ('Inácio Antônio Athayde-Oliveira', '', '', 'BR', '', '[]', null),
       ('Irving Aarón Díaz-Espinoza', '', '', 'MX', '', '[]', null),
       ('Isabel Hortensia Miguez', '', '', 'AR', '', '[]', null),
       ('Isabella Revelo Mera', '', '', 'CO', '', '[]', null),
       ('Iselgis De Diego Vásquez', '', '', 'PA', '', '[]', null),
       ('Ismael Hernández Hernández', '', '', 'CR', '', '[]', null),
       ('Ivanovnna Cruz', '', '', 'DO', '', '[]', null),
       ('Ivette Anel Delgado Valdez', '', '', 'MX', '', '[]', null),
       ('Ivonete Pereira Amador', '', '', 'BR', '', '[]', null),
       ('Jaime Carvalho e Silva', '', '', 'PT', '', '[]', null),
       ('Jairo A. Ayala Godoy', '', '', 'PR', '', '[]', null),
       ('Javier Lezama Andalon', '', '', 'MX', '', '[]', null),
       ('Jazmín Adriana Juárez Ramírez', '', '', 'MX', '', '[]', null),
       ('Jean-François Maheux', '', '', 'CA', '', '[]', null),
       ('Jennifer Fonseca Castro', '', '', 'CR', '', '[]', null),
       ('Jeremi Saul Santana', '', '', 'DO', '', '[]', null),
       ('Jeremías Willmore Metivier', '', '', 'DO', '', '[]', null),
       ('Jeser Candray', '', '', 'SV', '', '[]', null),
       ('Jéssica Jiménez Moscoso', '', '', 'CR', '', '[]', null),
       ('Jesús Andrés Jaimes León', '', '', 'CO', '', '[]', null),
       ('Jesús Guillermo Sotelo-Asef', '', '', 'MX', '', '[]', null),
       ('Jesus Montejo Gámez', '', '', 'ES', '', '[]', null),
       ('Joab Dos Santos Silva', '', '', 'BR', '', '[]', null),
       ('Joalisson Rego Pavão', '', '', 'BR', '', '[]', null),
       ('Joalkys Cuevas Recio', '', '', 'DO', '', '[]', null),
       ('João Ygor Dias Cardoso', '', '', 'BR', '', '[]', null),
       ('Joaquín Pomares Blaise', '', '', 'CO', '', '[]', null),
       ('Johan David Gallego Guzmán', '', '', 'CO', '', '[]', null),
       ('Johan Espinoza González', '', '', 'CR', '', '[]', null),
       ('Johandy Osanny Gómez-Vásquez', '', '', 'DO', '', '[]', null),
       ('Jonathan Espinoza González', '', '', 'CR', '', '[]', null),
       ('Jorge Albella Martínez', '', '', 'ES', '', '[]', null),
       ('Jorge Alejandro Blanco García', '', '', 'DO', '', '[]', null),
       ('Jorge Blanco', '', '', 'DO', '', '[]', null),
       ('Jorge Carvalho Brandão', '', '', 'BR', '', '[]', null),
       ('Jorge Gaona Paredes', '', '', 'CL', '', '[]', null),
       ('Jorge Gutiérrez', '', '', 'EC', '', '[]', null),
       ('Jorge Luis Gutiérrez Villegas', '', '', 'EC', '', '[]', null),
       ('Jorge Mello Román', '', '', 'PY', '', '[]', null),
       ('José Antonio Juárez López', '', '', 'MX', '', '[]', null),
       ('José Antonio Salvador', '', '', 'BR', '', '[]', null),
       ('José Armando Ortiz Ruiz', '', '', 'MX', '', '[]', null),
       ('José Bitsmar Núñez Vargas', '', '', 'DO', '', '[]', null),
       ('José Chamoso', '', '', 'ES', '', '[]', null),
       ('José David Vargas Gamboa', '', '', 'CR', '', '[]', null),
       ('José de Jesús Maldonado-Gómez', '', '', 'MX', '', '[]', null),
       ('José Francisco Cano', '', '', 'DO', '', '[]', null),
       ('José Gerardo Córdoba Hernández', '', '', 'CR', '', '[]', null),
       ('José Gleison Alves da Silva', '', '', 'BR', '', '[]', null),
       ('José Luis Bossio Vélez', '', '', 'CO', '', '[]', null),
       ('José Luis Hinostroza Gamboa', '', '', 'PE', '', '[]', null),
       ('José Luis Lupiáñez Gómez', '', '', 'ES', '', '[]', null),
       ('José Manuel Castillo Sedano', '', '', 'MX', '', '[]', null),
       ('José María Chamoso Sánchez', '', '', 'ES', '', '[]', null),
       ('José María Marbán Prieto', '', '', 'ES', '', '[]', null),
       ('José Nunes Ferreira', '', '', 'BR', '', '[]', null),
       ('José Ramón Jiménez Rodríguez', '', '', 'MX', '', '[]', null),
       ('José Ricardo Amaro Jaramillo', '', '', 'MX', '', '[]', null),
       ('José Romilio Loría Fernández', '', '', 'CR', '', '[]', null),
       ('José Saquimux', '', '', 'GT', '', '[]', null),
       ('Jose Suero Rico', '', '', 'DO', '', '[]', null),
       ('José Vasconcelos', '', '', 'BR', '', '[]', null),
       ('Josune Landa', '', '', 'ES', '', '[]', null),
       ('Juan Alberto Martínez Marín', '', '', 'CO', '', '[]', null),
       ('Juan Carlos Sandi-Delgado', '', '', 'CR', '', '[]', null),
       ('Juan Esteban Gordillo Niño', '', '', 'CO', '', '[]', null),
       ('Juan Felipe López Arias', '', '', 'CO', '', '[]', null),
       ('Juan José Cabrera Rodríguez', '', '', 'MX', '', '[]', null),
       ('Juan P Vázquez Pérez', '', '', 'PR', '', '[]', null),
       ('Juan Víctor Alejandro Meléndez Gómez', '', '', 'MX', '', '[]', null),
       ('Juana Caraballo', '', '', 'DO', '', '[]', null),
       ('Juddy Amparo Valderrama Moreno', '', '', 'CO', '', '[]', null),
       ('Julián Felix', '', '', 'GT', '', '[]', null),
       ('Julián Jiménez', '', '', 'PR', '', '[]', null),
       ('Juliana Andrea Marín Mosquera', '', '', 'CO', '', '[]', null),
       ('Juliana da Silva Porto Mendonça', '', '', 'BR', '', '[]', null),
       ('Juliana França Viol Paulin', '', '', 'BR', '', '[]', null),
       ('Juliana Ramírez Ramírez', '', '', 'CO', '', '[]', null),
       ('Julio Iván Marín', '', '', 'CR', '', '[]', null),
       ('Julio Marín Sánchez', '', '', 'CR', '', '[]', null),
       ('Kamila Alves Morais', '', '', 'BR', '', '[]', null),
       ('Karen Daniela Cordova Villalobos', '', '', 'CL', '', '[]', null),
       ('Karen Gabriela Tamayo Pérez', '', '', 'MX', '', '[]', null),
       ('Karen Mancera', '', '', 'MX', '', '[]', null),
       ('Karina Nunes Da Silva', '', '', 'BR', '', '[]', null),
       ('Karina Rizzo', '', '', 'AR', '', '[]', null),
       ('Karla Contreras Monge', '', '', 'CR', '', '[]', null),
       ('Karla Sepúlveda Obreque', '', '', 'CL', '', '[]', null),
       ('Kauê Monteiro Pascotto', '', '', 'BR', '', '[]', null),
       ('Kenneth Esquivel Murillo', '', '', 'CR', '', '[]', null),
       ('khalil Oliveira Portugal', '', '', 'BR', '', '[]', null),
       ('Lara Ronise de Negreiros Pinto Scipião', '', '', 'BR', '', '[]', null),
       ('Larissa Dias de Araujo', '', '', 'BR', '', '[]', null),
       ('Laura Tiemme de Castro', '', '', 'BR', '', '[]', null),
       ('Leandra Tapia', '', '', 'DO', '', '[]', null),
       ('Ledy Garcia Rivera', '', '', 'PE', '', '[]', null),
       ('Lemerton Matos Nogueira', '', '', 'BR', '', '[]', null),
       ('Leobel Morell Pérez', '', '', 'EC', '', '[]', null),
       ('Leonardo Favio Trujillo Diaz', '', '', 'CO', '', '[]', null),
       ('Leonel Chaves Salas', '', '', 'CR', '', '[]', null),
       ('Liane Garcia Pinheiro Lemos', '', '', 'BR', '', '[]', null),
       ('Liceth Niño Camacho', '', '', 'CO', '', '[]', null),
       ('Lilian Akemi Kato', '', '', 'BR', '', '[]', null),
       ('Liliana Torres Rodríguez', '', '', 'PR', '', '[]', null),
       ('Lily Bacon', '', '', 'CA', '', '[]', null),
       ('Lineth Fernández-Sánchez', '', '', 'EC', '', '[]', null),
       ('Lizbeth Alvarado Vargas', '', '', 'PR', '', '[]', null),
       ('Lorena Alejandra Medina Hernández', '', '', 'MX', '', '[]', null),
       ('Lorena García Fernández', '', '', 'ES', '', '[]', null),
       ('Lucas Flores Lehnhart', '', '', 'BR', '', '[]', null),
       ('Lucas Linke Nunes', '', '', 'BR', '', '[]', null),
       ('Lucas Marinho Mendonça Dos Santos', '', '', 'BR', '', '[]', null),
       ('Luciana Boemer Cesar Pereira', '', '', 'BR', '', '[]', null),
       ('Luciana de Jesus Lemos', '', '', 'BR', '', '[]', null),
       ('Luciana Maria Dias de Ávila Rodrigues', '', '', 'BR', '', '[]', null),
       ('Luciana Olesker Pérez', '', '', 'UY', '', '[]', null),
       ('Luciana Yoshie Tsuchiya', '', '', 'BR', '', '[]', null),
       ('Luis A. Hernández Solís', '', '', 'CR', '', '[]', null),
       ('Luis Adrián Miranda Pérez', '', '', 'MX', '', '[]', null),
       ('Luis Alberto Cuenca Macas', '', '', 'EC', '', '[]', null),
       ('Luis Ángel Bohórquez Arenas', '', '', 'CO', '', '[]', null),
       ('Luis Antonio Soto Hernández', '', '', 'HN', '', '[]', null),
       ('Luis Cáceres', '', '', 'PR', '', '[]', null),
       ('Luis Carlos Arboleda', '', '', 'CO', '', '[]', null),
       ('Luis Dario Castillo Vega', '', '', 'PA', '', '[]', null),
       ('Luis Fabián Gutiérrez', '', '', 'CR', '', '[]', null),
       ('Luis Fernando Pizzatto', '', '', 'BR', '', '[]', null),
       ('Luis Manuel Aguayo Rendón', '', '', 'MX', '', '[]', null),
       ('Luis Manuel Montero Hernández', '', '', 'CR', '', '[]', null),
       ('Luis Miguel Amador Silva', '', '', 'MX', '', '[]', null),
       ('Luis Sebastião Barbosa Bemme', '', '', 'BR', '', '[]', null),
       ('Luis Torres', '', '', 'PR', '', '[]', null),
       ('Luiza Ojeda Hoffmann', '', '', 'BR', '', '[]', null),
       ('Luz Ayda Muñoz Mamian', '', '', 'CO', '', '[]', null),
       ('Luz Elena Palacio Loaiza', '', '', 'CO', '', '[]', null),
       ('Luz Mayela Lugo Hernández', '', '', 'MX', '', '[]', null),
       ('Luz Valoyes Chávez', '', '', 'CL', '', '[]', null),
       ('Lyda Constanza Mora Mendieta', '', '', 'CO', '', '[]', null),
       ('Magda Perla Mendoza Villarreal', '', '', 'MX', '', '[]', null),
       ('Magdalena Waleska Aldana Segura', '', '', 'GT', '', '[]', null),
       ('Mahsa Allahbakhshi', '', '', 'CL', '', '[]', null),
       ('Mainor Alberto Cruz-Alvarado', '', '', 'CR', '', '[]', null),
       ('Mar Moreno Moreno', '', '', 'ES', '', '[]', null),
       ('Marcela Luciano Vilela de Souza', '', '', 'BR', '', '[]', null),
       ('Marcelina Piña Del Rosario', '', '', 'DO', '', '[]', null),
       ('Marcelo Bairral', '', '', 'BR', '', '[]', null),
       ('Márcia Jussara Hepp Rehfeldt', '', '', 'BR', '', '[]', null),
       ('Márcia Maria Fusaro Pinto', '', '', 'BR', '', '[]', null),
       ('Márcia Rodrigues Leal', '', '', 'BR', '', '[]', null),
       ('Marcília Cavalcante Viana', '', '', 'BR', '', '[]', null),
       ('Marcio Vieira de Almeida', '', '', 'BR', '', '[]', null),
       ('Marco Diego Sáenz Trejos', '', '', 'CR', '', '[]', null),
       ('Marco Gutiérrez Montenegro', '', '', 'CR', '', '[]', null),
       ('Marco Jacome', '', '', 'EC', '', '[]', null),
       ('Margarida Teixeira de Castro', '', '', 'BR', '', '[]', null),
       ('Maria Alejandra Perez Torres', '', '', 'CO', '', '[]', null),
       ('María Alexandra Fregueiro', '', '', 'UY', '', '[]', null),
       ('Maria Alice Veiga Ferreira de Souza', '', '', 'BR', '', '[]', null),
       ('Maria Aves', '', '', 'BR', '', '[]', null),
       ('María Calderón Torres', '', '', 'CR', '', '[]', null),
       ('Maria Clara de Oliveira Zaparoli', '', '', 'BR', '', '[]', null),
       ('Maria do Carmo de Sousa Maria', '', '', 'BR', '', '[]', null),
       ('María Irena Seimetz', '', '', 'BR', '', '[]', null),
       ('Maria Jose Costa Dos Santos', '', '', 'BR', '', '[]', null),
       ('Maria Josefa Smart Torrealba', '', '', 'CL', '', '[]', null),
       ('Maria Lidia Retamal Perez', '', '', 'CL', '', '[]', null),
       ('Maria Madalena Dullius', '', '', 'BR', '', '[]', null),
       ('Maria Rita Otero', '', '', 'AR', '', '[]', null),
       ('María Soledad Salomón Plata', '', '', 'ES', '', '[]', null),
       ('Maria Teresa Zampieri', '', '', 'BR', '', '[]', null),
       ('Mariam Macías Gámez', '', '', 'MX', '', '[]', null),
       ('Mariana Corujo Zubelso', '', '', 'UY', '', '[]', null),
       ('Mariana Matulovic da Silva Rodrigueiro', '', '', 'BR', '', '[]', null),
       ('Marianela Alpízar Vargas', '', '', 'CR', '', '[]', null),
       ('Marianna Del Secchi Sypnievski', '', '', 'BR', '', '[]', null),
       ('Marisol Santacruz Rodríguez', '', '', 'CO', '', '[]', null),
       ('Maritza Galindo Illanes', '', '', 'CL', '', '[]', null),
       ('Maritza Luna Valenzuela', '', '', 'PE', '', '[]', null),
       ('Marli Teresinha Quartieri', '', '', 'BR', '', '[]', null),
       ('Martha Lima Soares Matin Martha', '', '', 'BR', '', '[]', null),
       ('Mateo Pinillos Zapata', '', '', 'CO', '', '[]', null),
       ('Matias Arce Sánchez', '', '', 'ES', '', '[]', null),
       ('Matías Camacho-Machín', '', '', 'ES', '', '[]', null),
       ('Mauri Luís Tomkelski', '', '', 'BR', '', '[]', null),
       ('Mayela Vargas Ramos', '', '', 'MX', '', '[]', null),
       ('Mayra Elizabeth Parra Amaya', '', '', 'CO', '', '[]', null),
       ('Meire Nadja Meira de Souza', '', '', 'BR', '', '[]', null),
       ('Melania Bernabeu', '', '', 'ES', '', '[]', null),
       ('Melissa de Sousa Luiz', '', '', 'BR', '', '[]', null),
       ('Melissa Vásquez-Hernández', '', '', 'DO', '', '[]', null),
       ('Melvin Ramírez Bogantes', '', '', 'CR', '', '[]', null),
       ('Michèle Artigue', '', '', 'FR', '', '[]', null),
       ('Miguel Ángel Delgado-Fernández', '', '', 'PR', '', '[]', null),
       ('Miguel Ángel Moreno Ramírez', '', '', 'CO', '', '[]', null),
       ('Miguel Picado-Alfaro', '', '', 'CR', '', '[]', null),
       ('Mikael Cristopher Souza de Barros', '', '', 'BR', '', '[]', null),
       ('Miledis Teresa Tavárez Marzán', '', '', 'DO', '', '[]', null),
       ('Milena de Souza Mangueira', '', '', 'BR', '', '[]', null),
       ('Milton Rosa', '', '', 'BR', '', '[]', null),
       ('Miluska Osorio Martínez', '', '', 'PE', '', '[]', null),
       ('Mireia Saboya', '', '', 'CA', '', '[]', null),
       ('Mónica Cruz Sánchez', '', '', 'CO', '', '[]', null),
       ('Mónica del Rocío Torres Ibarra', '', '', 'MX', '', '[]', null),
       ('Mónica Mora Badilla', '', '', 'CR', '', '[]', null),
       ('Mónica Torres', '', '', 'MX', '', '[]', null),
       ('Morgana Guadagnin', '', '', 'BR', '', '[]', null),
       ('Myriam Rocío Pallares Muñoz', '', '', 'CO', '', '[]', null),
       ('Nadine Bednarz', '', '', 'CA', '', '[]', null),
       ('Nancy Lucia Chacón Arteaga', '', '', 'CU', '', '[]', null),
       ('Natalia Chicora', '', '', 'BR', '', '[]', null),
       ('Natalia Gómez Maripán', '', '', 'CL', '', '[]', null),
       ('Natalia Ruiz López', '', '', 'ES', '', '[]', null),
       ('Natalia Solano', '', '', 'ES', '', '[]', null),
       ('Nathalie Anwandter Cuellar', '', '', 'CA', '', '[]', null),
       ('Newman Yonander Zambrano-Leal', '', '', 'DO', '', '[]', null),
       ('Newman Zambrano-Leal', '', '', 'DO', '', '[]', null),
       ('Noelia Saleme', '', '', 'AR', '', '[]', null),
       ('Nohelys Edith Díaz', '', '', 'PA', '', '[]', null),
       ('Nohemy Marcela Bedoya Ríos', '', '', 'CO', '', '[]', null),
       ('Omar Hernández Rodríguez', '', '', 'PR', '', '[]', null),
       ('Omayra Rivera-Rivera', '', '', 'PR', '', '[]', null),
       ('Oscar Alejandro Barrios Candil', '', '', 'CO', '', '[]', null),
       ('Oscar Henrique Reinke Backes', '', '', 'BR', '', '[]', null),
       ('Osvaldo Jesús Rojas Velázquez', '', '', 'CO', '', '[]', null),
       ('Pablo Sabatinelli', '', '', 'AR', '', '[]', null),
       ('Paloma Santonja Serrano', '', '', 'ES', '', '[]', null),
       ('Paola Judith Amaris Ruidiaz', '', '', 'CO', '', '[]', null),
       ('Paola Valero', '', '', 'SE', '', '[]', null),
       ('Patrick Gonzales', '', '', 'PR', '', '[]', null),
       ('Patrick Scott', '', '', 'US', '', '[]', null),
       ('Paula Sandoval Quidel', '', '', 'CL', '', '[]', null),
       ('Paulo Eugênio da Silva Silva', '', '', 'BR', '', '[]', null),
       ('Pedro Luiz Pedro', '', '', 'BR', '', '[]', null),
       ('Pedro Pimenta', '', '', 'PT', '', '[]', null),
       ('Poliana Figueiredo Cardoso Rodrigues', '', '', 'BR', '', '[]', null),
       ('Quendra Silva Cartier Larangeira', '', '', 'BR', '', '[]', null),
       ('Quetzarilis Guardia', '', '', 'PA', '', '[]', null),
       ('Rafael Aparicio Cuello', '', '', 'PR', '', '[]', null),
       ('Rafael David Francisco Ventura', '', '', 'DO', '', '[]', null),
       ('Rafael Pantoja González', '', '', 'MX', '', '[]', null),
       ('Rafael Pantoja Rangel', '', '', 'MX', '', '[]', null),
       ('Rafael Pastor Martínez Vargas', '', '', 'DO', '', '[]', null),
       ('Raimundo Nonato Barbosa Cavalcante', '', '', 'BR', '', '[]', null),
       ('Raphaëlle Dufour', '', '', 'CA', '', '[]', null),
       ('Raquel Carneiro Dörr', '', '', 'BR', '', '[]', null),
       ('Raquel Fernández-Cézar', '', '', 'ES', '', '[]', null),
       ('Rebeca Ventura Saravia', '', '', 'CR', '', '[]', null),
       ('REDUMATE', '', '', null, '', '[]', null),
       ('Regina da Silva Pina Neves', '', '', 'BR', '', '[]', null),
       ('Regina Pina Neves', '', '', 'BR', '', '[]', null),
       ('Reiman Yitsak Acuña Chacón', '', '', 'CR', '', '[]', null),
       ('Reina Altagracia Taveras', '', '', 'DO', '', '[]', null),
       ('Reina San Martín Aedo', '', '', 'CL', '', '[]', null),
       ('Reinier Abreu-Naranjo', '', '', 'EC', '', '[]', null),
       ('Rejane Bianchini', '', '', 'BR', '', '[]', null),
       ('Renan Severo Ferreira', '', '', 'BR', '', '[]', null),
       ('Renata da Silva Dessbesel', '', '', 'BR', '', '[]', null),
       ('Renata Sorah de Sousa e Silva', '', '', 'BR', '', '[]', null),
       ('Ricardo Poveda Vásquez', '', '', 'CR', '', '[]', null),
       ('Rita Díaz Flores', '', '', 'CR', '', '[]', null),
       ('Roberto Carlos Torres Peña', '', '', 'CO', '', '[]', null),
       ('Roberto Herrera', '', '', 'DO', '', '[]', null),
       ('Roberto Rafael Mesén-Hidalgo', '', '', 'CR', '', '[]', null),
       ('Roberto Seidi Imafuku', '', '', 'BR', '', '[]', null),
       ('Roberto Torres Peña', '', '', 'CO', '', '[]', null),
       ('Rocío Yaressi Cisneros Martínez', '', '', 'MX', '', '[]', null),
       ('Rodrigo Carlos Pinheiro', '', '', 'BR', '', '[]', null),
       ('Rodrigo Yoel Combe Aparicio', '', '', 'PA', '', '[]', null),
       ('Rolando Alonso Navarro Rodríguez', '', '', 'PA', '', '[]', null),
       ('Ronald Quesada Córdova', '', '', 'PE', '', '[]', null),
       ('Rosa María Almonte Batista', '', '', 'DO', '', '[]', null),
       ('Rosa Mirabal', '', '', 'DO', '', '[]', null),
       ('Rosalío Tortolero-Portugal', '', '', 'MX', '', '[]', null),
       ('Rosana Pinheiro', '', '', 'BR', '', '[]', null),
       ('Rosângela Maria Albuquerque', '', '', 'BR', '', '[]', null),
       ('Rosemar de Fatima Vestena', '', '', 'BR', '', '[]', null),
       ('Rosemeire Carvalho da Silva', '', '', 'BR', '', '[]', null),
       ('Rúben Dario Lara Escobar', '', '', 'CO', '', '[]', null),
       ('Rubén Lijó', '', '', 'ES', '', '[]', null),
       ('Rui Seimetz', '', '', 'BR', '', '[]', null),
       ('Ruth Coronel', '', '', 'EC', '', '[]', null),
       ('Sabrina Héroux', '', '', 'CA', '', '[]', null),
       ('Salomón Chaves Cascante', '', '', 'CR', '', '[]', null),
       ('Salvador Llinares Ciscar', '', '', 'ES', '', '[]', null),
       ('Samara Sales Frazão', '', '', 'BR', '', '[]', null),
       ('Sandra Crespo Luna', '', '', 'DO', '', '[]', null),
       ('Sandra Marcela Vera', '', '', 'AR', '', '[]', null),
       ('Sandra Rojas Sevilla', '', '', 'CO', '', '[]', null),
       ('Sandra Yazmín Palacio Ramírez', '', '', 'CO', '', '[]', null),
       ('Sandra Yolima Ruiz Yacumal', '', '', 'CO', '', '[]', null),
       ('Sara Milena Soto Vanegas', '', '', 'CO', '', '[]', null),
       ('Sarah González de Lora', '', '', 'DO', '', '[]', null),
       ('Saray Carrillo Paternina', '', '', 'CO', '', '[]', null),
       ('Saúl Eduardo Méndez Larios', '', '', 'GT', '', '[]', null),
       ('Saúl Méndez', '', '', 'GT', '', '[]', null),
       ('Sergio Clavero Ibáñez de Garayo', '', '', 'ES', '', '[]', null),
       ('Sibeli da Rosa da Rocha', '', '', 'BR', '', '[]', null),
       ('Silmara Louise da Silva', '', '', 'BR', '', '[]', null),
       ('Silvanio de Andrade', '', '', 'BR', '', '[]', null),
       ('Silvia Frizzarini', '', '', 'BR', '', '[]', null),
       ('Silvia Gabriela Pérez', '', '', 'AR', '', '[]', null),
       ('Silvia Maria de Aguiar Isaia', '', '', 'BR', '', '[]', null),
       ('Solange Roa Fuentes', '', '', 'CO', '', '[]', null),
       ('Soledad Estrella', '', '', 'CL', '', '[]', null),
       ('Solonildo Almeida da Silva', '', '', 'BR', '', '[]', null),
       ('Sonia Cordero', '', '', 'BO', '', '[]', null),
       ('Sônia Elisa Marchi Gonzatti', '', '', 'BR', '', '[]', null),
       ('Sonia Valbuena Duarte', '', '', 'CO', '', '[]', null),
       ('Sonnia Méndez', '', '', 'DO', '', '[]', null),
       ('Soraya Eugenia Pol', '', '', 'AR', '', '[]', null),
       ('Soraya Pol', '', '', 'AR', '', '[]', null),
       ('Steven Josué Rodríguez Gómez', '', '', 'CR', '', '[]', null),
       ('Sueli Liberatti Javaroni', '', '', 'BR', '', '[]', null),
       ('Suzilei Magosso Araujo Alabarces', '', '', 'BR', '', '[]', null),
       ('Sylvia Celedón Pattichis', '', '', 'US', '', '[]', null),
       ('Tainá Taiza de Araujo', '', '', 'BR', '', '[]', null),
       ('Tamara Isabel Terrazas Medina', '', '', 'MX', '', '[]', null),
       ('Tania Azucena Chicalote Jiménez', '', '', 'MX', '', '[]', null),
       ('Tania Julieth Plazas Merchán', '', '', 'CO', '', '[]', null),
       ('Telésforo Sol', '', '', 'ES', '', '[]', null),
       ('Teresa Fernández Blanco', '', '', 'ES', '', '[]', null),
       ('Thaís de Souza Machado', '', '', 'BR', '', '[]', null),
       ('Thais Regina Duarte Marçal', '', '', 'BR', '', '[]', null),
       ('Thaís Rodrigues Ferreira Machado Thaís', '', '', 'BR', '', '[]', null),
       ('Valeria Ocoro Rebolledo', '', '', 'CO', '', '[]', null),
       ('Valerie Carrasquillo Meléndez', '', '', 'PR', '', '[]', null),
       ('Valery Liriano Cruz', '', '', 'DO', '', '[]', null),
       ('Vanilde Bisognin', '', '', 'BR', '', '[]', null),
       ('Venant Fabienne', '', '', 'CA', '', '[]', null),
       ('Verena Rodríguez', '', '', 'CL', '', '[]', null),
       ('Verónica Easton Perotti', '', '', 'UY', '', '[]', null),
       ('Vicenç Font', '', '', 'ES', '', '[]', null),
       ('Virginia Méndez', '', '', 'UY', '', '[]', null),
       ('Vitor Martins Sontak', '', '', 'BR', '', '[]', null),
       ('Vitória de Mello Figueiredo', '', '', 'BR', '', '[]', null),
       ('Vivian Libeth Uzuriaga López', '', '', 'CO', '', '[]', null),
       ('Viviana Carolina Llanos', '', '', 'AR', '', '[]', null),
       ('Walter Fernando Castro Gordillo', '', '', 'CO', '', '[]', null),
       ('Wilbertt Moura', '', '', 'BR', '', '[]', null),
       ('Wildebrando Miranda Vargas', '', '', 'CO', '', '[]', null),
       ('William Jiménez Gómez', '', '', 'CO', '', '[]', null),
       ('William Perea Diaz', '', '', 'CO', '', '[]', null),
       ('William Vieira', '', '', 'BR', '', '[]', null),
       ('Willington Algeri Benítez Chará', '', '', 'CO', '', '[]', null),
       ('Wilson Rodríguez Calderón', '', '', 'CO', '', '[]', null),
       ('Yacsury Yamileth Montilla Arroyo', '', '', 'PA', '', '[]', null),
       ('Yadira Sanabria Mejía', '', '', 'CO', '', '[]', null),
       ('Yamily Colón Negrón', '', '', 'PR', '', '[]', null),
       ('Yeison Rodríguez', '', '', 'PR', '', '[]', null),
       ('Yesica Dayan Audor Marmolejo', '', '', 'CO', '', '[]', null),
       ('Yilmar Barreto Rodriguez', '', '', 'CO', '', '[]', null),
       ('Yilton Riascos Forero', '', '', 'CO', '', '[]', null),
       ('Yolanni Mercedes Peguero-Ovalles', '', '', 'DO', '', '[]', null),
       ('Yuri Morales-López', '', '', 'CR', '', '[]', null),
       ('Yuriko Baldin', '', '', 'BR', '', '[]', null),
       ('Yuriko Yamamoto Baldin', '', '', 'BR', '', '[]', null),
       ('Zaida Francisca Morlett Villa', '', '', 'MX', '', '[]', null),
       ('Zaida Margot Santa Ramírez', '', '', 'CO', '', '[]', null);
