DELETE
FROM attender;

INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Poliana', 'Figueiredo Cardoso Rodrigues', 'Externo', '', 'polianacar@gmail.com', 'QR-0001', 'BR'),
       ('Sara Ynes', 'González Sued', 'PUCMM', '', 'sarahgonzalez@pucmm.edu.do', 'QR-0002', 'DO'),
       ('Hamlet Humberto', 'Castillo Alvino', 'PUCMM', '', 'hcastillo@pucmm.edu.do', 'QR-0003', 'DO'),
       ('Ricardo', 'Poveda Vásquez', 'UNA', '', 'ricardopovedav@gmail.com', 'QR-0004', 'CR'),
       ('Ariana Kazumi', 'Mayuri Jimenez', 'Externo', '', 'arianakmj@gmail.com', 'QR-0006', 'PE'),
       ('Juan Carlos', 'Sandí-Delgado', 'Universidad De Costa Rica', '', 'juan.sandidelgado@ucr.ac.cr', 'QR-0007',
        'CR'),
       ('Diana', 'Hernández Rivera', 'Universidad Autónoma De Coahuila', '', 'diana_hernandez@uadec.edu.mx', 'QR-0008',
        'MX'),
       ('Celina', 'Abar', 'PUC-SP', '', 'abarcaap@pucsp.br', 'QR-0009', 'BR'),
       ('Thais', 'Machado', 'Universidade De Brasília', '', 'thaisrfm013@gmail.com', 'QR-0010', 'BR'),
       ('David Fernando', 'Méndez Vargas', 'Externo', '', 'david.mendez@udea.edu.co', 'QR-0011', 'CO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Sandra Marcela', 'Vera', 'Ies Estanislao Maldones', '', 'verasandramarcela@gmail.com', 'QR-0012', 'AR'),
       ('Silmara Louise Da Silva', 'Silmara Louise', 'IFTM', '', 'silmaraba10@gmail.com', 'QR-0013', 'BR'),
       ('Mariana', 'Corujo Zubelso', 'Externo', '', 'mcorujozubelso@gmail.com', 'QR-0014', 'UY'),
       ('Maria Do Carmo De', 'Sousa', 'UFSCAR', '', 'mdcsousa@ufscar.br', 'QR-0015', 'BR'),
       ('Verónica Cecilia', 'Easton Perotti', 'Externo', '', 'veaston@claeh.edu.uy', 'QR-0017', 'UY'),
       ('Vivian Libeth', 'Uzuriaga López', 'Universidad Tecnológica De Pereira', '', 'vuzuriaga@utp.edu.co', 'QR-0019',
        'CO'),
       ('Federico', 'De Olivera Lamas', 'Externo', '', 'fededeo@gmail.com', 'QR-0020', 'UY'),
       ('Marcela Alejandra', 'Ribas García', 'Externo', '', 'marcelaribasgarcia@gmail.com', 'QR-0021', 'UY'),
       ('Vanilde', 'Bisognin', 'Universidade Franciscana', '', 'vanilde@ufn.edu.br', 'QR-0023', 'BR'),
       ('Saúl Eduardo', 'Méndez Larios', 'Mathkind Global', '', 'saul@mathkind.org', 'QR-0024', 'GT');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Jorge Luis', 'Gutierrez Villegas', 'Mathkind Global', '', 'jorge@mathkind.org', 'QR-0025', 'EC'),
       ('Silvia', 'Frizzarini', 'Univ. Do Estado De Santa Catariana', '', 'silvia.frizzarini@udesc.br', 'QR-0026',
        'BR'),
       ('Juliana Andrea', 'Marin Mosquera', 'Externo', '', 'andrea.marin5@udea.edu.co', 'QR-0027', 'CO'),
       ('Alfonso', 'Romero Huertas', 'Universidad Antonio Nariño', '', 'romerohuertas78@gmail.com', 'QR-0028', 'CO'),
       ('Lilian Akemi', 'Kato', 'Universidade Estadual De Maringá', '', 'lakato@uem.br', 'QR-0029', 'BR'),
       ('Luz Marina', 'Alvarez Rojas', 'Externo', '', 'luzval1@yahoo.es', 'QR-0030', 'CO'),
       ('Fernando', 'Hitt', 'CINVESTAV-UQAM', '', 'ferhitt@yahoo.com', 'QR-0031', 'CA'),
       ('José Bitsmar', 'Núñez Vargas', 'PUCMM', '', 'jo.nunez@ce.pucmm.edu.do', 'QR-0032', 'DO'),
       ('Luis Daniel', 'Torres Lebrón', 'Univ. Puerto Rico', '', 'luis.torres78@upr.edu', 'QR-0035', 'PR'),
       ('Crystal', 'Kalinec-Craig', 'University Of Texas At San Antonio', '', 'crystal.kalinec-craig@utsa.edu',
        'QR-0036', 'US');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('André Luis', 'Trevisan', 'UTFPR', '', 'andreluistrevisan@gmail.com', 'QR-0037', 'BR'),
       ('Marcia Maria', 'Fusaro Pinto', 'Universidade Federal Do Rio De Janeiro', '', 'marcia@im.ufrj.br', 'QR-0038',
        'BR'),
       ('Luis', 'Caceres', 'Univ. Puerto Rico, Mayagüez', '', 'luis.caceres1@upr.edu', 'QR-0039', 'PR'),
       ('Wildebrando', 'Miranda Vargas', 'Universidad Del Valle', '', 'wildebrando.miranda@correounivalle.edu.co',
        'QR-0040', 'CO'),
       ('Maria José', 'Costa Dos Santos', 'Fund. Cearense De Pesquisa E Cultura', '', 'mazeautomatic@gmail.com',
        'QR-0041', 'BR'),
       ('Marcília', 'Cavalcante Viana', 'Fund. Cearense De Pesquisa E Cultura', '', 'marciliaviana80@gmail.com',
        'QR-0042', 'BR'),
       ('Analia', 'Bergé', 'Université Du Québec À Rimouski', '', 'analia_berge@uqar.ca', 'QR-0043', 'CA'),
       ('Adriana', 'Toxtle Colotl', 'Benemérita Univ. Autónoma De Puebla', '', 'toxtleadry9@gmail.com', 'QR-0044',
        'MX'),
       ('Teovaldo', 'García Romero', 'Universidad Popular Del Cesar', '', 'teovaldogarcia@gmail.com', 'QR-0045', 'CO'),
       ('Ana', 'Maroto Sáez', 'Universidad De Valladolid', '', 'anaisabel.maroto@uva.es', 'QR-0046', 'ES');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Nohemy Marcela', 'Bedoya Ríos', 'Univ. Distrital Francisco José De Caldas', '', 'nmbedoyar@udistrital.edu.co',
        'QR-0047', 'CO'),
       ('Ledy', 'Garcia Rivera', 'Externo', '', 'ledy.garcia@upch.pe', 'QR-0048', 'PE'),
       ('Lyda Constanza', 'Mora Mendieta', 'Externo', '', 'lmendieta@pedagogica.edu.co', 'QR-0049', 'CO'),
       ('Salvador', 'José Antonio', 'UFSCAR', '', 'jasalvador@ufscar.br', 'QR-0050', 'BR'),
       ('Elizabeth', 'Torres Puentes', 'Universidad Pedagógica Nacional', '', 'etorresp@pedagogica.edu.co', 'QR-0051',
        'CO'),
       ('Adão José', 'Martins', 'Externo', '', 'adaojosemartins89@gmail.com', 'QR-0052', 'BR'),
       ('Alexandra', 'Fregueiro', 'Consejo De Formación En Educación', '', 'suresmeralda@hotmail.com', 'QR-0053', 'UY'),
       ('Sibeli', 'Da Rosa Da Rocha', 'Universidade Federal Do Paraná', '', 'sibarocha02@gmail.com', 'QR-0054', 'BR'),
       ('Mireille', 'Saboya', 'Université Du Québec À Montréal', '', 'saboya.mireille@uqam.ca', 'QR-0055', 'CA'),
       ('Natalia', 'Chicora', 'Externo', '', 'nataliachicora@gmail.com', 'QR-0056', 'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Karina Nunes Da', 'Silva', 'Externo', '', 'karina.nunes@rede.ulbra.br', 'QR-0057', 'BR'),
       ('Steven Josué', 'Rodríguez Gómez', 'Universidad De Costa Rica', '', 'steven.rodriguezgomez@ucr.ac.cr',
        'QR-0059', 'CR'),
       ('Rui', 'Seimetz', 'Universidade De Brasília', '', 'rseimetz@unb.br', 'QR-0060', 'BR'),
       ('Martha Lima Soares Martins', 'Martha', 'Externo', '', 'martalimas12@gmail.com', 'QR-0062', 'BR'),
       ('Brayan Ricardo', 'Andrade Zambrano', 'Externo', '', 'brayan.andrade@correounivalle.edu.co', 'QR-0063', 'CO'),
       ('William Stevens', 'Perea Diaz', 'Externo', '', 'william.perea@correounivalle.edu.co', 'QR-0064', 'CO'),
       ('Valeria', 'Ocoro Rebolledo', 'Externo', '', 'valeria.ocoro@correounivalle.edu.co', 'QR-0065', 'CO'),
       ('Andrea', 'Serna Rivera', 'Universidad Del Valle', '', 'andrea.serna@correounivalle.edu.co', 'QR-0066', 'CO'),
       ('Yilmar Stiven', 'Barreto Rodriguez', 'Externo', '', 'yilmar.barreto@correounivalle.edu.co', 'QR-0067', 'CO'),
       ('Cristian Andrés', 'Ortega Aguilar', 'Externo', '', 'cristian.ortega@ucr.ac.cr', 'QR-0068', 'CR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Isabella', 'Revelo Mera', 'Externo', '', 'isabella.revelo@correounivalle.edu.co', 'QR-0069', 'CO'),
       ('Alberto', 'Zapatera Llinares', 'Universidad De Alicante', '', 'alberto.zapatera@ua.es', 'QR-0070', 'ES'),
       ('José David', 'Vargas Gamboa', 'Externo', '', 'jose.vargas_g@ucr.ac.cr', 'QR-0071', 'CR'),
       ('Àngela', 'Buforn Lloret', 'Univesidad De Alicante', '', 'angela.buforn@ua.es', 'QR-0072', 'ES'),
       ('Felix', 'De La Cruz Serrano', 'Externo', '', 'feldese@gmail.com', 'QR-0073', 'PE'),
       ('Nathalie Silvia', 'Anwandter Cuellar', 'Université Du Québec En Outaouais', '', 'nathalie.anwandter@uqo.ca',
        'QR-0074', 'CA'),
       ('Fabiola', 'Arrivillaga Hurtado', 'Universidad Rafael Landívar', '', 'farrivillaga@url.edu.gt', 'QR-0075',
        'GT'),
       ('Marianela', 'Alpízar Vargas', 'Universidad Nacional', '', 'marianela.alpizar.vargas@una.cr', 'QR-0076', 'CR'),
       ('Luis Ángel', 'Bohórquez Arenas', 'Univ. Distrital Francisco José De Caldas', '',
        'labohorqueza@udistrital.edu.co', 'QR-0077', 'CO'),
       ('Yesica Dayan', 'Audor Marmolejo', 'Institución Educativa María Auxiliadora', '', 'artembera.sevilla@gmail.com',
        'QR-0078', 'CO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Fabio Hernán', 'Echeverry Pérez', 'Institución Educativa María Auxiliadora', '', 'fachelo13@gmail.com',
        'QR-0079', 'CO'),
       ('Alexánder', 'Hernández', 'Universidad De La Laguna', '', 'alexander.hernandez@ull.edu.es', 'QR-0080', 'ES'),
       ('José Ramón', 'Jiménez Rodríguez', 'Universidad De Sonora', '', 'joseramon.jimenez@unison.mx', 'QR-0081', 'MX'),
       ('Vladiana', 'Costa Dos Santos', 'Externo', '', 'vladyanasantos@gmail.com', 'QR-0082', 'BR'),
       ('Ernesto Geovani', 'Figueroa-González', 'Univ. Juárez Del Estado De Durango', '', 'geovani.figueroa@ujed.mx',
        'QR-0083', 'MX'),
       ('Ilma Edisa', 'Arrivillaga Hernández', 'Escuela Oficial Rural', '', 'edisaarrivillaga@yahoo.es', 'QR-0084',
        'GT'),
       ('Gilberto Santos', 'Cerqueira', 'UFC', '', 'giufarmacia@gmail.com', 'QR-0085', 'BR'),
       ('Eric Ricardo', 'Padilla Mora', 'Universidad Estatal A Distancia', '', 'epadillamora@gmail.com', 'QR-0086',
        'CR'),
       ('German', 'Cadavid  Arango', 'Universidad Tecnológica De Pereira', '', 'gcadavid@utp.edu.co', 'QR-0087', 'CO'),
       ('Ana María', 'González García', 'O&M', '', 'anamariagg28@gmail.com', 'QR-0089', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Maria Lourdes', 'Veras De Santos', 'UAPA', '', 'mariaveras@f.uapa.edu.do', 'QR-0090', 'DO'),
       ('Nelson', 'Gómez López', 'UAPA', '', 'nelsongomez@uapa.edu.do', 'QR-0091', 'DO'),
       ('Allan Guillermo', 'Gen Palma', 'Uned Costa Rica', '', 'agen@uned.ac.cr', 'QR-0092', 'CR'),
       ('Dakeisi Janel', 'Perdomo Espinal', 'UAPA', '', 'dakeisiperdomo@uapa.edu.do', 'QR-0093', 'DO'),
       ('María', 'Penkova Vassileva', 'INTEC', '', 'maria.penkova@intec.edu.do', 'QR-0094', 'DO'),
       ('Nurkis Amalia', 'Ruiz Nina', 'UNICARIBE', '', 'nruiz@unicaribe.edu.do', 'QR-0095', 'DO'),
       ('Wellington Fernando', 'Valenzuela Perez', 'UNICARIBE', '', 'wellington.valenzuela@unicaribe.edu.do', 'QR-0096',
        'DO'),
       ('Francisco Del Rosario', 'Sánchez Fernández', 'UTESA', '', 'franciscosanchez@utesa.edu', 'QR-0097', 'DO'),
       ('Arsenia', 'De Jesús Severino', 'UTECO', '', 'arsenia.severino@uteco.edu.do', 'QR-0098', 'DO'),
       ('Marcio', 'De Almeida', 'PUC-SP', '', 'marcioalmeidasp@gmail.com', 'QR-0099', 'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Manuel Arismendy', 'Batista Villa', 'UTECO', '', 'manuelm.batista@uteco.edu.do', 'QR-0100', 'DO'),
       ('Eduardo Emiliano', 'Muñoz Ortiz', 'Universidad De Costa Rica', '', 'eduardo.munos@ucr.ac.cr', 'QR-0101', 'CR'),
       ('Wilson Lucilo', 'Heredia Amparo', 'UTECO', '', 'wilsonl.heredia@uteco.edu.do', 'QR-0102', 'DO'),
       ('Mauricio Antonio', 'Hernandez Garcia', 'UAFAM', '', 'hmauricioantonio@gmail.com', 'QR-0103', 'DO'),
       ('Omar Eduardo', 'Castillo Muñoz', 'Uaf Arturos De Meriño', '', 'omarr99c@hotmail.com', 'QR-0104', 'DO'),
       ('María Lissette', 'Carballo Lemus', 'Universidad Rafael Landívar', '', 'mlcarballo@url.edu.gt', 'QR-0105',
        'GT'),
       ('Ismael', 'Hernández Hernández', 'Universidad De Costa Rica', '', 'ismaelhernan1122@gmail.com', 'QR-0106',
        'CR'),
       ('Amabile', 'Mesquita', 'PUC-SP', '', 'amabile.mesquita@ueg.br', 'QR-0107', 'BR'),
       ('Jose  Luis', 'Permuy  Garcia', 'UNAPEC', '', 'j7madeleine.permuy@mail.com', 'QR-0108', 'DO'),
       ('José Gerardo', 'Vasconcelos', 'UFC', '', 'gerardovasconcelos@ufc.br', 'QR-0109', 'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Luiza', 'Ojeda Hoffmann', 'Externo', '', 'luizaojeda@hotmail.com', 'QR-0110', 'BR'),
       ('Joab', 'Dos Santos Silva', 'IFPB', '', 'joab.silva@ifpb.edu.br', 'QR-0112', 'BR'),
       ('Víctor José', 'Galán Céspedes', 'Externo', '', 'victorj.galan@uteco.edu.do', 'QR-0113', 'DO'),
       ('William', 'Vieira', 'Ifsp Guarulhos', '', 'wvieira@ifsp.edu.br', 'QR-0114', 'BR'),
       ('Luciana', 'Olesker', 'Externo', '', 'lucianao05@gmail.com', 'QR-0115', 'UY'),
       ('Marcelina', 'De Paula Manzueta', 'O&M', '', 'mercelabella@gmail.com', 'QR-0116', 'DO'),
       ('Reinier', 'Abreu Naranjo', 'Universidad Estatal Amazónica', '', 'rabreu@uea.edu.ec', 'QR-0117', 'EC'),
       ('Rosana', 'Soares Pinheiro', 'Externo', '', 'pfrosana@gmail.com', 'QR-0118', 'BR'),
       ('Reina Altagracia', 'Taveras', 'UASD', '', 'rtaveras22@uasd.edu.do', 'QR-0119', 'DO'),
       ('Rosa María', 'Almonte Batista', 'UASD', '', 'ralmonte49@uasd.edu.do', 'QR-0120', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Maria Eliene', 'Magalhães Da Silva Alves', 'Externo', '', 'jacyraufc@gmail.com', 'QR-0121', 'BR'),
       ('Lilimar', 'Carmona Pizarro', 'O&M', '', 'lcarmona@udoym.edu.do', 'QR-0122', 'DO'),
       ('Alma', 'Soto Castillo', 'Benemérita Univ. Autónoma De Puebla', '', 'soto_castillo10@hotmail.com', 'QR-0123',
        'MX'),
       ('Catalina', 'Molano Carranza', 'Secretaria De Educacion Cundinamarca', '', 'ebenezercata@hotmail.com',
        'QR-0124', 'CO'),
       ('Hildebrando', 'Diaz Soler', 'Secretaria De Educacion De Boyaca', '', 'hildebrandodiaz@hotmail.com', 'QR-0125',
        'CO'),
       ('Vilma Elizabeth', 'Enciso Gavilán', 'Externo', '', 'elizaenci@gmail.com', 'QR-0126', 'PY'),
       ('Edith Marcela', 'Chorolque', 'U.N.Sa F.R.O.', '', 'marcelachorolque@gmail.com', 'QR-0127', 'AR'),
       ('Reiman', 'Acuña Chacón', 'Tecnológico De Costa Rica', '', 'reiacuna@itcr.ac.cr', 'QR-0128', 'CR'),
       ('Marco Vinicio', 'Gutiérrez Montenegro', 'Tecnológico De Costa Rica', '', 'vgutierrez@itcr.ac.cr', 'QR-0129',
        'CR'),
       ('Vidal', 'Rodriguez Del Carmen', 'O&M', '', 'vrodriguez@udoym.edu.do', 'QR-0130', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Maria Alice', 'Veiga Ferreira De Souza', 'Instituto Federal Do Espírito Santo', '', 'alicevfs@gmail.com',
        'QR-0131', 'BR'),
       ('Ronald Javier', 'Quesada Cordova', 'Universidad De Lima', '', 'rquesada@ulima.edu.pe', 'QR-0132', 'PE'),
       ('Luciana Maria', 'Dias De Ávila Rodrigues', 'Universidade De Brasília', '', 'luavila83@gmail.com', 'QR-0133',
        'BR'),
       ('Isabel Hortensia', 'Miguez', 'Externo', '', 'miguezisa26@gmail.com', 'QR-0134', 'AR'),
       ('Celia Elizabeth', 'Villagra', 'Facultad Regional Orán', '', 'villagracelia@gmail.com', 'QR-0135', 'AR'),
       ('Zaida Margot', 'Santa Ramírez', 'Universidad De Antioquia', '', 'zaida.santa@udea.edu.co', 'QR-0136', 'CO'),
       ('Carmen Larissa', 'Rodríguez Poveda', 'Universidad De Panamá', '', 'carmen.rodriguezp@up.ac.pa', 'QR-0137',
        'PA'),
       ('Iselgis Janeth', 'De Diego Vásquez', 'Universidad De Panamá', '', 'iselgis.dediego@up.ac.pa', 'QR-0138', 'PA'),
       ('Karen Gabriela', 'Tamayo Pérez', 'Externo', '', 'karenga_35@hotmail.com', 'QR-0139', 'MX'),
       ('Mónica Del Rocío', 'Torres Ibarra', 'Universidad Autónoma De Zacatecas', '', 'mtorres@uaz.edu.mx', 'QR-0140',
        'MX');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Eric Iván', 'Figueroa González', 'Univ. Puerto Rico', '', 'eric.figueroagonzalez@upr.edu', 'QR-0141', 'PR'),
       ('Denise Deyanira', 'Chamorro Manríquez', 'Universidad Católica De La Santísima Concepción', '',
        'dechamorrom@gmail.com', 'QR-0142', 'CL'),
       ('Rodrigo Yoel', 'Combe Aparicio', 'Universidad De Panamá', '', 'rcombe11@gmail.com', 'QR-0143', 'PA'),
       ('Dannael', 'Carrero Pellicier', 'Univ. Interamericana De Puerto Rico', '', 'dannael.carrero@upr.edu', 'QR-0144',
        'PR'),
       ('Marcelina  Del Carmen', 'Cigarruista', 'Colegio Jose O. Huertas', '', 'rodrigo.combe@matexam.net', 'QR-0145',
        'PA'),
       ('Soraya Eugenia', 'Pol', 'Externo', '', 'sorayaepol@gmail.com', 'QR-0146', 'AR'),
       ('Ana Edith', 'Varela Achurra', 'Universidad De Panamá', '', 'ana.varela@up.ac.pa', 'QR-0147', 'PA'),
       ('Noelia', 'Saleme', 'Universidad Nacional, Catamarca', '', 'noeliasaleme@unca.edu.ar', 'QR-0148', 'AR'),
       ('Carina', 'Rivera Londoño', 'Externo', '', 'carina.rivera@udea.edu.co', 'QR-0150', 'CO'),
       ('Carlos Eduardo', 'Rojas Bruna', 'Pontificia Universidad Católica De Chile', '', 'carojasb@uc.cl', 'QR-0151',
        'CL');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Mahsa', 'Allahbakhshi', 'Pontificia Universidad Católica De Chile', '', 'maallahbakhshi@uc.cl', 'QR-0152',
        'CL'),
       ('Yadira', 'Sanabria Mejía', 'Fundación Universitaria Salesiana', '', 'yadira.sanabriam@gmail.com', 'QR-0153',
        'CO'),
       ('Ana Sofia', 'Montenegro Arango', 'Fundación Universitaria Salesiana', '', 'ana.montenegro@salesiana.edu.co',
        'QR-0154', 'CO'),
       ('Patrick', 'Gonzales July', 'Univ. Puerto Rico, Mayagüez', '', 'patrick.gonzales@upr.edu', 'QR-0155', 'HN'),
       ('Jairo Arturo', 'Ayala Godoy', 'Univ. Puerto Rico', '', 'jairoarturo.ayala@upr.edu', 'QR-0156', 'PR'),
       ('Jose Luis', 'Henostroza Gamboa', 'Pontificia Universidad Católica Del Perú', '', 'jhenost@pucp.pe', 'QR-0157',
        'PE'),
       ('Mauri Luís', 'Tomkelski', 'Seduc/Rs E Uricer', '', 'mauriluis@gmail.com', 'QR-0158', 'BR'),
       ('Adriana', 'Richter', 'UFFS-ERECHIM', '', 'adrianarichit@gmail.com', 'QR-0159', 'BR'),
       ('Yeison Osvaldo', 'Rodriguez Rojas', 'Externo', '', 'yeisonosvaldo.rodriguez@upr.edu', 'QR-0160', 'CO'),
       ('Yvette', 'Rivera Martínez', 'Univ. Interamericana De Puerto Rico', '', 'yriveram@ponce.inter.edu', 'QR-0161',
        'PR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Blanca Esthela', 'Ledezma Durán', 'Escuela Normal Miguel F. Martínez', '', 'blanca.ledezma@enmfm.edu.mx',
        'QR-0162', 'MX'),
       ('Fabián Alonso', 'Vásquez Hernández', 'Universidad De Costa Rica', '', 'fvasquez0600@gmail.com', 'QR-0163',
        'CR'),
       ('Andrés Antonio', 'Valdés Retamal', 'Universidad Cátolica Del Maule', '', 'v.andres.r@hotmail.com', 'QR-0164',
        'CL'),
       ('Oscar Alejandro', 'Barrios Candil', 'Universidad Pedagógica Nacional', '', 'oscalej2@gmail.com', 'QR-0165',
        'CO'),
       ('Tania Azucena', 'Chicalote Jiménez', 'UNAM', '', 'tazjimenez@ciencias.unam.mx', 'QR-0166', 'MX'),
       ('Fabienne Genevieve Marcelle', 'Venant', 'Université Du Québec À Montréal', '', 'venant.fabienne@uqam.ca',
        'QR-0167', 'CA'),
       ('José Antonio', 'Juárez López', 'Externo', '', 'jajul1969@gmail.com', 'QR-0168', 'MX'),
       ('Maritza Estella', 'Coba De Chen', 'Universidad Tecnológica De Panamá', '', 'rodrigo.combe@utp.ac.pa',
        'QR-0169', 'PA'),
       ('Carolina', 'Ruminot', 'Universidad De Ottawa', '', 'cruminot@uottawa.ca', 'QR-0170', 'CA'),
       ('Edgar Esaúl', 'Saucedo Becerra', 'Instituto Tecnológico De Zacatecas', '', 'esaul.saucedo@itz.edu.mx',
        'QR-0171', 'MX');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Darwin Alexander', 'Moreno Gatica', 'Externo', '', 'darwinmoreno56@gmail.com', 'QR-0172', 'GT'),
       ('Héctor Alonso', 'Rosas Álvarez', 'Escuela Normal Miguel F. Martínez', '', 'hector.rosas@enmfm.edu.mx',
        'QR-0173', 'MX'),
       ('Agostinho Iaqchan Ryokiti', 'Homa', 'Universidade Franciscana', '', 'iaqchan@hotmail.com', 'QR-0174', 'BR'),
       ('Andréia', 'Araújo De Farias Aquino', 'UEM/IFPR', '', 'andreia.aquino@ifpr.edu.br', 'QR-0175', 'BR'),
       ('Alexandre', 'Xavier Dos Santos', 'Gov. Do Estado Do Rio Grande Do Sul', '', 'alexandrexrs@gmail.com',
        'QR-0176', 'BR'),
       ('Ivonete', 'Pereira Amador', 'Externo', '', 'ivoneteamador67@gmail.com', 'QR-0177', 'BR'),
       ('Antonio', 'Rivero Alexanderson', 'PUCMM', '', 'ariveroalex@gmail.com', 'QR-0178', 'DO'),
       ('Kenneth', 'Esquivel Murillo', 'Universidad De Costa Rica - Sur', '', 'kenneth.esquivelmurillo@ucr.ac.cr',
        'QR-0179', 'CR'),
       ('Angie De Los Ángeles', 'Vega Vega', 'Universidad De Costa Rica - Sur', '', 'angie.vegavega@ucr.ac.cr',
        'QR-0180', 'CR'),
       ('Vienbenida', 'Igualada Cortez', 'Universidad De Panamá', '', 'vienbenida27@gmail.com', 'QR-0181', 'PA');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Mikael Cristopher', 'Souza De Barros', 'Externo', '', 'mikaelcristopher1@gmail.com', 'QR-0182', 'BR'),
       ('Henry Rafael', 'Mejía Álvarez', 'PUCMM', '', 'hr.mejia@ce.pucmm.edu.do', 'QR-0183', 'DO'),
       ('Leonardo Favio', 'Trujillo Diaz', 'Universidad Surcolombiana', '', 'leonardotrujillo@usco.edu.co', 'QR-0184',
        'CO'),
       ('Brigitte Johana', 'Sanchez Robayo', 'Univ. Distrital Francisco José De Caldas', '',
        'bjsanchezr@udistrital.edu.co', 'QR-0185', 'CO'),
       ('Angy Carelly', 'Coronel Suárez', 'Univ. Puerto Rico, Mayagüez', '', 'angy.coronel@upr.edu', 'QR-0186', 'PR'),
       ('Luz', 'Valoyes Chávez', 'Universidad Católica De Temuco', '', 'lvaloyes@uct.cl', 'QR-0187', 'CL'),
       ('Andrea', 'Araya Chacón', 'Universidad De Costa Rica', '', 'andrea.arayachacon@ucr.ac.cr', 'QR-0188', 'CR'),
       ('Helmer Jesus', 'Ruiz Diaz', 'Docente Investigador', '', 'hjdiaz@unicauca.edu.co', 'QR-0189', 'CO'),
       ('Guillermo Enrique', 'Ramirez Montes', 'Universidad De Costa Rica', '', 'guillermo.ramirez_m@ucr.ac.cr',
        'QR-0190', 'CR'),
       ('Roxana', 'Cabrera Puig.', 'Externo', '', 'roxycabrera706@gmail.com', 'QR-0191', 'CU');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Juan Esteban', 'Gordillo Niño', 'Univ. Distrital Francisco José De Caldas', '', 'jusanic12@gmail.com',
        'QR-0192', 'CO'),
       ('Ana Paola', 'Castillo Domenech', 'Mathkind Global', '', 'pao@mathkind.org', 'QR-0193', 'EC'),
       ('Carmen', 'Vieira Mathias', 'Universidade Federal De Santa Maria', '', 'carmen@ufsm.br', 'QR-0194', 'BR'),
       ('Dumas', 'Manzano Franco', 'Externo', '', 'dmfranco@unicauca.edu.co', 'QR-0195', 'CO'),
       ('Paola Judith', 'Amaris Ruidiaz', 'Externo', '', 'paola.amaris@uptc.edu.co', 'QR-0196', 'CO'),
       ('Rafael', 'Pantoja Rangel', 'Universidad De Guadalajara', '', 'rafael.prangel@academicos.udg.mx', 'QR-0197',
        'MX'),
       ('Paula V', 'Santana Mercado', 'PUCMM', '', 'pv.santana@ce.pucmm.edu.do', 'QR-0199', 'DO'),
       ('Cristian Eduardo', 'Quesada Fernández', 'UNED', '', 'cquesadaf@uned.ac.cr', 'QR-0200', 'CR'),
       ('Elcio', 'Pasolini Milli', 'IFES', '', 'elciopmilli@gmail.com', 'QR-0201', 'BR'),
       ('Rosa Herminia', 'Mirabal Paulino', 'PUCMM', '', 'rh.mirabal@ce.pucmm', 'QR-0202', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Caridad Anselma', 'Espinal Matías', 'PUCMM', '', 'ca.espinal@ce.pucmm.edu.do', 'QR-0203', 'DO'),
       ('Sandra Yolima', 'Ruiz Yacumal', 'Universidad Del Cauca, Colombia', '', 'sandray@unicauca.edu.co', 'QR-0204',
        'CO'),
       ('Juana Evangelina', 'Caraballo León', 'PUCMM', '', 'z_caraballo@hotmail.com', 'QR-0206', 'DO'),
       ('Valery Dahian', 'Liriano Cruz', 'PUCMM', '', 'vd.liriano@ce.pucmm.edu.do', 'QR-0207', 'DO'),
       ('Jorge', 'Blanco', 'PUCMM', '', 'ja.blanco@ce.pucmm.edu.do', 'QR-0208', 'DO'),
       ('Jaime Maria', 'Monteiro De Carvalho', 'Externo', '', 'jaimecs@mat.uc.pt', 'QR-0209', 'PT'),
       ('Paola Ximena', 'Valero Dueñas', 'Externo', '', 'paola.valero@su.se', 'QR-0210', 'CO'),
       ('Gilbert', 'Valverde', 'Externo', '', 'gvalverde@albany.edu', 'QR-0211', 'US'),
       ('Franderly', 'Acostada Valdez', 'PUCMM', '', 'f.acosta@ce.pucmm.edu.do', 'QR-0212', 'DO'),
       ('Glory Bel', 'Pérez', 'PUCMM', '', 'gb.perez@ce.pucmm.edu.do', 'QR-0213', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Myriam Rocío', 'Pallares Muñoz', 'Externo', '', 'mrocio03@hotmail.com', 'QR-0214', 'CO'),
       ('Alexander', 'Difó Rodríguez', 'MINERD', '', 'alexander.difo@minerd.gob.do', 'QR-0215', 'DO'),
       ('Ana Liliana', 'Abreu Perdomo', 'ISFODOSU', '', 'ana.liliana@isfodosu.edu.do', 'QR-0216', 'DO'),
       ('Luz Stella', 'Calderon Rebellon', 'ISFODOSU', '', 'luz.calderon@isfodosu.edu.do', 'QR-0217', 'DO'),
       ('Jesús Ramón', 'Guillén Ruiz', 'ISFODOSU', '', 'jesus.guillen@isfodosu.edu.do', 'QR-0218', 'DO'),
       ('Rogel Rafael', 'Rojas Bello', 'ISFODOSU', '', 'rogel.rojas@isfodosu.edu.do', 'QR-0219', 'DO'),
       ('José Ramón', 'Mota Pichardo', 'ISFODOSU', '', 'jose.mota@isfodosu.edu.do', 'QR-0220', 'DO'),
       ('José Miguel', 'Suero Rico', 'ISFODOSU', '', 'jose.suero@isfodosu.edu.do', 'QR-0221', 'DO'),
       ('José Manuel', 'Torrez Vasquez', 'Externo', '', 'jose.torrez@isfodosu.edu.do', 'QR-0222', 'DO'),
       ('María Altagracia', 'Tavárez Rodríguez', 'ISFODOSU', '', 'maria.tavarez@isfodosu.edu.do', 'QR-0223', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Felipe De Jesús', 'Cordero González', 'ISFODOSU', '', 'felipe.cordero@isfodosu.edu.do', 'QR-0224', 'DO'),
       ('Jose Atilio', 'Guerrero', 'ISFODOSU', '', 'jose.guerrero@isfodosu.edu.do', 'QR-0225', 'DO'),
       ('Miguel Antonio', 'Tavares Luis', 'ISFODOSU', '', 'miguel.tavares@isfodosu.edu.do', 'QR-0226', 'DO'),
       ('Rafael David', 'Francisco Ventura', 'ISFODOSU', '', 'rafael.ventura@isfodosu.edu.do', 'QR-0227', 'DO'),
       ('Efraín Ambiórix', 'López Tejeda', 'ISFODOSU', '', 'efrain.lopez@isfodosu.edu.do', 'QR-0228', 'DO'),
       ('Miguel Antonio', 'Leonardo Sepúlveda', 'ISFODOSU', '', 'miguel.leonardo@isfodosu.edu.do', 'QR-0230', 'DO'),
       ('Marino', 'Brito Guillén', 'ISFODOSU', '', 'marino.brito@isfodosu.edu.do', 'QR-0231', 'DO'),
       ('Wilfredo', 'Marte Fortunato', 'Externo', '', 'wilfredo.marte@isfodosu.edu.do', 'QR-0232', 'DO'),
       ('Ramiro', 'Rueda', 'ISFODOSU', '', 'ramiro.rueda@isfodosu.edu.do', 'QR-0233', 'DO'),
       ('Luis Eligio', 'Vasquez Marquez', 'ISFODOSU', '', 'luis.vasquez@isfodosu.edu.do', 'QR-0234', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Alberto Agustín', 'Pérez Cruz', 'ISFODOSU', '', 'alberto.perez@isfodosu.edu.do', 'QR-0235', 'DO'),
       ('Erick', 'Padilla Bonilla', 'ISFODOSU', '', '202230056@issu.edu.do', 'QR-0236', 'DO'),
       ('Wilmer Lucidio', 'Arzolay Abreu', 'ISFODOSU', '', 'wilmer.arzolay@isfodosu.edu.do', 'QR-0237', 'DO'),
       ('Franklin Rafael', 'Astudillo Villalba', 'ISFODOSU', '', 'franklin.villalba@isfodosu.edu.do', 'QR-0238', 'DO'),
       ('Penelope', 'Rodríguez Moreta', 'ISFODOSU', '', '202230054@issu.edu.do', 'QR-0239', 'DO'),
       ('Newman Yonander', 'Zambrano Leal', 'ISFODOSU', '', 'newman.zambrano@issu.edu.do', 'QR-0240', 'DO'),
       ('Agueda Nicole', 'Báez Jiménez', 'ISFODOSU', '', 'aguedabaezj@gmail.com', 'QR-0241', 'DO'),
       ('Rafael Pastor', 'Martinez Vargas', 'ISFODOSU', '', 'rafael.martinez@isfodosu.edu.do', 'QR-0242', 'DO'),
       ('Aquiles Julio', 'Guerrero Fondeur', 'ISFODOSU', '', 'julio.guerrero@isfodosu.edu.do', 'QR-0243', 'DO'),
       ('Damarys Dinorah', 'Castellanos', 'ISFODOSU', '', 'damarysuni0928@gmail.com', 'QR-0244', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Antonia Del Carmen', 'Álvarez Reynoso', 'ISFODOSU', '', 'antonia.alvarez@isfodosu.edu.do', 'QR-0245', 'DO'),
       ('Melissa', 'Vásquez Hernández', 'ISFODOSU', '', 'melissavh0611@gmail.com', 'QR-0246', 'DO'),
       ('Dirwin Alfonzo', 'Muñoz Pinto', 'ISFODOSU', '', 'dirwin.munoz@isfodosu.edu.do', 'QR-0247', 'DO'),
       ('Wilson', 'Rodríguez Calderón', 'ESAP', '', 'wilroca50@hotmail.com', 'QR-0248', 'CO'),
       ('Darwin Dacier', 'Peña González', 'Universidad Del Magdalena', '', 'ddpenag@unimagdalena.edu.co', 'QR-0249',
        'CO'),
       ('Roberto Carlos', 'Torres Peña', 'Externo', '', 'rtorres@unimagdalena.edu.co', 'QR-0250', 'CO'),
       ('Leobel', 'Morell Pérez', 'Universidad Estatal Amazónica', '', 'leobelm2014@gmail.com', 'QR-0251', 'EC'),
       ('Maria Teresa', 'Fernández Blanco', 'Universidad De Santiago De Compostela', '', 'teref.blanco@usc.es',
        'QR-0252', 'ES'),
       ('Henry Alexander', 'Ramírez Bernal', 'Externo', '', 'haramirezb@udistrital.edu.co', 'QR-0253', 'CO'),
       ('Mario Nicolas', 'Covaleda Olave', 'Externo', '', 'nicova9207@gmail.com', 'QR-0254', 'CO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Luciana', 'Boemer Cesar Pereira', 'UTFPR', '', 'lucianapereira@utfpr.edu.br', 'QR-0255', 'BR'),
       ('Miguel Ángel', 'Delgado Fernández', 'Univ. Interamericana De Puerto Rico', '', 'miguel.delgado2773@gmail.com',
        'QR-0256', 'PR'),
       ('Alejandra', 'Sánchez Ávila', 'UNED', '', 'alsanchez@uned.ac.cr', 'QR-0257', 'CR'),
       ('Alvaro Rafael', 'Lecompte Montes', 'Univ. Interamericana De Puerto Rico', '', 'alvarolecompte@gmail.com',
        'QR-0258', 'PR'),
       ('Pedro', 'Pimenta', 'A.Esc.Da Caparica / Univ. Nova De Lisboa', '', 'pedropimenta@aecaparica.pt', 'QR-0259',
        'PT'),
       ('Alejandro José', 'Taveras Reyes', 'ISFODOSU', '', 'alejandro.taveras@isfodosu.edu.do', 'QR-0260', 'DO'),
       ('Gabriel', 'Dos Santos E Silva', 'Universidade Federal Do Paraná', '', 'gabriel.santos22@gmail.com', 'QR-0261',
        'BR'),
       ('Natalia', 'Ruiz López', 'Universidad Autónoma De Madrid', '', 'natalia.ruiz@uam.es', 'QR-0262', 'ES'),
       ('José', 'Bosch Betancor', 'Smpm Emma Castelnuovo', '', 'jobobet@gmail.com', 'QR-0263', 'ES'),
       ('Raquel', 'Carneiro Dörr', 'Universidade De Brasília', '', 'raqueldorr@unb.br', 'QR-0264', 'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Magdalena Waleska', 'Aldana Segura', 'Externo', '', 'waldanasegura@gmail.com', 'QR-0265', 'GT'),
       ('Gilberto', 'Chavarría Arroyo', 'Universidad Nacional', '', 'gilberto.chavarria.arroyo@una.cr', 'QR-0266',
        'CR'),
       ('Maria Madalena', 'Dullius', 'Externo', '', 'madalena@univates.br', 'QR-0267', 'BR'),
       ('Cristiana Amparo', 'Abreu Espinal', 'Externo', '', 'cr.abreu@ce.pucmm.edu.do', 'QR-0268', 'DO'),
       ('Ramón', 'De Los Santos Suero', 'PUCMM', '', 'r.delossantos@ce.pucmm.edu.do', 'QR-0269', 'DO'),
       ('Inés Jovanna', 'Ramírez De Los Santos', 'PUCMM', '', 'ij.ramirez@ce.pucmm.edu.do', 'QR-0270', 'DO'),
       ('Manuel Calixto', 'Rodriguez Gonzalez', 'PUCMM', '', 'mca.rodriguez@ce.pucmm.edu.do', 'QR-0271', 'DO'),
       ('Luis Armando', 'Hernandez Solis', 'Univ. Estatal A Distancia De Costa Rica', '', 'lhernandez@uned.ac.cr',
        'QR-0272', 'CR'),
       ('Angel', 'Mastromartino Perez', 'PUCMM', '', 'a.mastromartino@ce.pucmm.edu.do', 'QR-0273', 'DO'),
       ('Isabel Cristina', 'Márquez De Mastromartino', 'PUCMM', '', 'ic.marquez@ce.pucmm.edu.do', 'QR-0274', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Jose Luis', 'Bossio Velez', 'Universidad De Antioquia', '', 'jose.bossio@udea.edu.co', 'QR-0275', 'CO'),
       ('Carlos Mario', 'Jaramillo López', 'Externo', '', 'carlos.jaramillo1@udea.edu.co', 'QR-0276', 'CO'),
       ('Gabriela', 'Rodriguez', 'Soc. Peruana De Educacion Matematica', '', 'gabyrodriguez.pe@gmail.com', 'QR-0277',
        'PE'),
       ('Jennifer', 'Fonseca Castro', 'Universidad Nacional', '', 'jennifer.fonseca.castro@una.cr', 'QR-0278', 'CR'),
       ('Filánder', 'Sequeira Chavarría', 'Universidad Nacional', '', 'filander.sequeira.chavarria@una.ac.cr',
        'QR-0279', 'CR'),
       ('Helen', 'Guillén Oviedo', 'Universidad Nacional', '', 'hellen.guillen.oviedo@una.ac.cr', 'QR-0280', 'CR'),
       ('Jose', 'Saquimux', 'Externo', '', 'jsaquimux@yahoo.co.uk', 'QR-0281', 'GT'),
       ('Diana Carolina', 'Pineda Pérez', 'Externo', '', 'dianapineda1710@gmail.com', 'QR-0282', 'CO'),
       ('Bruna Aparecida', 'Ferreira De Castro', 'UNESPAR', '', 'brunaacastro217@gmail.com', 'QR-0283', 'BR'),
       ('Carmen Eulalia', 'Calle Palomeque', 'Universidad De Cuenca', '', 'eulalia.calle@ucuenca.edu.ec', 'QR-0284',
        'EC');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Andrés Fernando', 'Mosquera Díaz', 'Externo', '', 'afernando.mosquera@udea.edu.co', 'QR-0285', 'CO'),
       ('Andrea', 'Pinto', 'Universidad De Santiago De Chile', '', 'andrea.pinto@usach.cl', 'QR-0287', 'CL'),
       ('Andrea Milena', 'Osorio Cardenas', 'Secretaría De Educación De Manizales', '', 'milenacardenas23@gmail.com',
        'QR-0288', 'CO'),
       ('Silvia Gabriela', 'Pérez', 'GPDM-IFDC-UNICEF-RD', '', 'perezdaq@gmail.com', 'QR-0289', 'AR'),
       ('Carlos Jacinto', 'Vargas Samaniego', 'Universidad De Panamá', '', 'carlos23199220@gmail.com', 'QR-0290', 'PA'),
       ('Jazmín Adriana', 'Juárez Ramírez', 'IPN', '', 'jjuarezr@ipn.mx', 'QR-0291', 'MX'),
       ('Claudia Amelia', 'Matus Zuñiga', 'USACH', '', 'claudia.matus.z@usach.cl', 'QR-0292', 'CL'),
       ('Jose Manuel', 'Castillo Sedano', 'UNISON', '', 'a215290112@unison.mx', 'QR-0293', 'MX'),
       ('Luis Miguel', 'Amador Silva', 'UNISON', '', 'luis.amador@unison.mx', 'QR-0294', 'MX'),
       ('Marli Teresinha', 'Quartieri', 'Universidade Do Vale Do Taquari', '', 'mtquartieri@univates.br', 'QR-0295',
        'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Luis Manuel', 'Henríquez Grullón', 'PUCMM', '', 'lhenriquez@pucmm.edu.do', 'QR-0296', 'DO'),
       ('Franciele', 'Santos Teixeira', 'UNESP', '', 'fs.teixeira@unesp.br', 'QR-0297', 'BR'),
       ('Santa Daysi', 'Sánchez González', 'Externo', '', 'sanchez.daysi@gmail.com', 'QR-0298', 'DO'),
       ('Ana Catalina', 'Siles Murillo', 'Externo', '', 'ana.silesmurillo@ucr.ac.cr', 'QR-0299', 'CR'),
       ('Joshua Mauricio', 'Paniagua-Chavarría', 'Universidad De Costa Rica', '', 'joshua.paniagua@ucr.ac.cr',
        'QR-0300', 'CR'),
       ('Jeremias', 'Willmore Metivier', 'PUCMM', '', 'j.willmore@ce.pucmm.edu.do', 'QR-0301', 'DO'),
       ('Danitza Soledad', 'Mirabal Aybar', 'Externo', '', 'danitzamirabal920@gmail.com', 'QR-0302', 'DO'),
       ('Elizabeth', 'Rincón Santana', 'UASD', '', 'te10elirisa@gmail.com', 'QR-0303', 'DO'),
       ('Carmen Miguelina', 'Santos Abreu', 'PUCMM', '', 'cm.santos@ce.pucmm.edu.do', 'QR-0304', 'DO'),
       ('Luis Manuel', 'Montero Hernández', 'Universidad Nacional', '', 'luismanuel1808@gmail.com', 'QR-0305', 'CR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Miledis Teresa', 'Tavarez Marzan', 'UASD', '', 'miledyst@gmail.com', 'QR-0306', 'DO'),
       ('Jeser Caleb', 'Candray Menjívar', 'Universidad Francisco Gavidia', '', 'jccandray@gmail.com', 'QR-0307', 'SV'),
       ('José Romilio', 'Loría Fernández', 'Universidad Nacional', '', 'jose.loria.fernandez@una.cr', 'QR-0308', 'CR'),
       ('Carmen Luisa', 'Lopez De Pena', 'PUCMM', '', 'cl.lopez@ce.pucmm.edu.do', 'QR-0309', 'DO'),
       ('Karen', 'Mancera', 'PERSONAL', '', 'dra.kelokumpu@gmail.com', 'QR-0310', 'MX'),
       ('Karina Amalia', 'Rizzo', 'Siglo 21- Universidad Tecnológica Nacional', '', 'karinarizzo71@gmail.com',
        'QR-0311', 'AR'),
       ('Luis Carlos', 'Arboleda Aparicio', 'Externo', '', 'luis.carlos.arboleda@gmail.com', 'QR-0312', 'CO'),
       ('Osvaldo Jesus', 'Rojas Ve3Lazquez', 'Universidad Antonio Nariño', '', 'orojasv69@uan.edu.co', 'QR-0313', 'CO'),
       ('Gert', 'Schubring', 'UFRJ', '', 'gert.schubring@uni-bielefeld.de', 'QR-0314', 'BR'),
       ('Yuriko', 'Baldin', 'UFSCAR', '', 'yuriko@ufscar.br', 'QR-0315', 'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Angel', 'Ruiz', 'Universidad De Costa Rica', '', 'ruizz.angel@gmail.com', 'QR-0316', 'CR'),
       ('Fredy', 'Rivadeneira Loor', 'Universidad Técnica De Manabí', '', 'fredy.rivadeneira@utm.edu.ec', 'QR-0317',
        'EC'),
       ('Claudia Lorena', 'Vargas Díaz', 'Universidad De Santiago De Chile', '', 'claudia.vargas.d@usach.cl', 'QR-0318',
        'CL'),
       ('Carlos', 'Sánchez Fernández', 'Universidad De La Habana', '', 'csanchez@matcom.uh.cu', 'QR-0319', 'CU'),
       ('Gilberto De Jesus', 'Obando Zapata', 'Universidad De Antioquia', '', 'gilberto.obando@udea.edu.co', 'QR-0320',
        'CO'),
       ('Ramón Aridio', 'Cueto Mejia', 'PUCMM', '', 'aridiocm@hotmail.com', 'QR-0321', 'DO'),
       ('Edwin Antonio', 'Chaves Esquivel', 'Externo', '', 'echavese@gmail.com', 'QR-0322', 'CR'),
       ('Luis Sebastião', 'Barbosa Bemme', 'Universidade Franciscana', '', 'luis.bemme@ufn.edu.br', 'QR-0323', 'BR'),
       ('Yuri', 'Morales Lopez', 'Universidad Nacional', '', 'yurimoralesl@yahoo.com', 'QR-0324', 'CR'),
       ('Adrián', 'Gómez Árciga', 'Universidad Autónoma De Baja California', '', 'adrian.arciga@uabc.edu.mx', 'QR-0325',
        'MX');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Gabriela', 'Gomez Pasquali', 'OMAPA', '', 'gabriela@omapa.org.py', 'QR-0326', 'PY'),
       ('Sonia Ximena Nivia', 'Cordero Cárdenas', 'Universidad Mayor De San Andrés', '', 'soniacordero3r@gmail.com',
        'QR-0327', 'BO'),
       ('Augusta Rosa Maria', 'Osorio Gonzales', 'PUCP', '', 'arosorio@pucp.edu.pe', 'QR-0328', 'PE'),
       ('Adriana', 'Breda', 'Universidad De Barcelona', '', 'adriana.breda@ub.edu', 'QR-0329', 'ES'),
       ('Edgar Alberto', 'Guacaneme Suárez', 'Universidad Pedagógica Nacional', '', 'guacaneme@pedagogica.edu.co',
        'QR-0330', 'CO'),
       ('José María', 'Chamoso Sánchez', 'Universidad De Salamanca', '', 'jchamoso@usal.es', 'QR-0331', 'ES'),
       ('Jorge Daniel', 'Mello Román', 'Universidad Nacional, Concepción', '', 'jdmello@facet-unc.edu.py', 'QR-0332',
        'PY'),
       ('Dagoberto Moises', 'Pena', 'PUCMM', '', 'dm.pena@ce.pucmm.edu.do', 'QR-0334', 'DO'),
       ('Patrick', 'Scott', 'CIAEM', '', 'pscott@nmsu.edu', 'QR-0335', 'US'),
       ('Claudia Lisete', 'Oliveira Groenwald', 'Universidade Franciscana', '', 'claudiag1959@gmail.com', 'QR-0336',
        'BR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Eliecer Leonardo', 'Fitoria Pérez', 'Externo', '', 'eliecer.fitoria@ucr.ac.cr', 'QR-0337', 'CR'),
       ('Eduardo Iván', 'Mancera Alarcón', 'Externo', '', 'eduardoivanma@gmail.com', 'QR-0338', 'MX'),
       ('Salvador', 'Llinares', 'Universidad De Alicante', '', 'salvadorllc@gmail.com', 'QR-0339', 'ES'),
       ('Michèle Jeanne', 'Lanne Artigue', 'Université Paris Cité', '', 'michele.artigue@gmail.com', 'QR-0340', 'FR'),
       ('Diego Eduardo', 'Lieban', 'Ifrs Gonçalves', '', 'diego.lieban@bento.ifrs.edu.br', 'QR-0341', 'BR'),
       ('Luis Fabián', 'Gutiérrez Fallas', 'Universidad De Costa Rica', '', 'luisfabian.gutierrez@ucr.ac.cr', 'QR-0342',
        'CR'),
       ('Eduardo', 'Basurto Hidalgo', 'ULSA', '', 'basurto.e@gmail.com', 'QR-0343', 'MX'),
       ('Marcelo', 'Bairral', 'Univ. Federal Rural De Rio De Janeiro', '', 'mbairral@ufrrj.br', 'QR-0344', 'BR'),
       ('Luis Diego', 'Chavarria Brenes', 'Universidad De Costa Rica', '', 'luis.chavarriabrenes@ucr.ac.cr', 'QR-0345',
        'CR'),
       ('Manuel Alberto', 'Montero Lora', 'PUCMM', '', 'manuelmonterolora@gmail.com', 'QR-0346', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Sylvia', 'Celedon-Pattichis', 'University Of Texas At Austin', '', 'sylvia.celedon@austin.utexas.edu',
        'QR-0347', 'US'),
       ('Emily Caroline', 'Felix Cordeiro', 'Universidade Estadual De Londrina', '', 'emilycfcordeiro@gmail.com',
        'QR-0348', 'BR'),
       ('Luis Antonio', 'Soto Hernández', 'Universidad Pedagógica Nacional F.M.', '', 'lsoto@upnfm.edu.hn', 'QR-0349',
        'HN'),
       ('Lizbeth', 'Alvarado Vargas', 'Univ. Puerto Rico', '', 'lizbeth.alvarado@upr.edu', 'QR-0350', 'CR'),
       ('Ariana Inés', 'Rodríguez Flores', 'Univ. Puerto Rico, Rio Piedras', '', 'ariana.rodriguez20@upr.edu',
        'QR-0351', 'CR'),
       ('Ariana Paola', 'Lozano Campos', 'Universidad Nacional', '', 'plozano725@gmail.com', 'QR-0352', 'CR'),
       ('Axel', 'Jiménez Matamoros', 'Universidad De Costa Rica', '', 'axel.jimenezmatamoros@ucr.ac.cr', 'QR-0353',
        'CR'),
       ('Fernanda', 'Drummond Pequeno Valadão', 'UNB', '', 'nandadrummond09@gmail.com', 'QR-0358', 'BR'),
       ('Juliana', 'Ramírez Ramírez', 'Externo', '', 'juliana.ramirez7@udea.edu.co', 'QR-0360', 'CO'),
       ('Marcelina', 'Piña Del Rosario', 'CHPI', '', 'marcelina.pina@gmail.com', 'QR-0361', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('María Alejandra', 'Pérez Torres', 'Univ. Distrital Francisco José De Caldas', '', 'mariaaperez0802@gmail.com',
        'QR-0362', 'CO'),
       ('Pascual', 'Leocadio', 'UASD', '', 'pleocadio76@uasd.edu.do', 'QR-0363', 'DO'),
       ('Josias Rosselin', 'Carrión Cordones', 'UNPHU', '', 'jrcarrion00@gmail.com', 'QR-0364', 'DO'),
       ('Jaime Vladimir', 'González De La Cruz', 'UNPHU', '', 'jgonzalez@unphu.edu.do', 'QR-0365', 'DO'),
       ('Arelis', 'Manzueta Sánchez', 'Instituto Sup. De Estudio Pedro Poveda', '', 'arelismanzuetasanchez@gmail.com',
        'QR-0366', 'DO'),
       ('Angel Gabriel', 'Lopez Rodriguez', 'PUCMM', '', 'aglr0003@ce.pucmm.edu.do', 'QR-0367', 'DO'),
       ('Carolyn', 'Rodríguez Núñez', 'PUCMM', '', 'cxrn0001@ce.pucmm.edu.do', 'QR-0368', 'DO'),
       ('Juana Iris', 'Salvador López', 'MINERD', '', 'iris.lopezsena@gmail.com', 'QR-0369', 'DO'),
       ('Francis', 'Mora Ferreras', 'UNPHU', '', 'fm10900@unphu.edu.do', 'QR-0370', 'DO'),
       ('Reiny', 'Rojas', 'PUCMM', '', 'rarg0004@ce.pucmm.edu.do', 'QR-0371', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Dominicana', 'Asencio Germán', 'UNPHU', '', 'da6606@unphu.edu.do', 'QR-0372', 'DO'),
       ('Arisbel', 'Tavárez Tavárez', 'PUCMM', '', 'axtt0002@ce.pucmm.edu.do', 'QR-0373', 'DO'),
       ('Edwin Eduardo', 'Domínguez Pérez', 'PUCMM', '', 'eedp0001@ce.pucmm.edu.do', 'QR-0374', 'DO'),
       ('Scarlin Aurora', 'Martínez Herrera', 'PUCMM', '', 'samh0001@ce.pucmm.edu.do', 'QR-0375', 'DO'),
       ('Wirlenia', 'Marrero Cepeda', 'PUCMM', '', 'wxmc0001@ce.pucmm.edu.do', 'QR-0376', 'DO'),
       ('Azarías', 'Escarramán Barrera', 'PUCMM', '', 'axeb0001@ce.pucmm.edu.do', 'QR-0377', 'DO'),
       ('Cila Eduviges', 'Mola Reyes', 'MESCYT', '', 'cilaeduvijesmolareyes@gmail.com', 'QR-0378', 'CU'),
       ('Bartolo Máximo', 'Triana Hernández', 'MESCYT', '', 'bartolotriana@gmail.com', 'QR-0379', 'CU'),
       ('Olga Lidia', 'Pérez González', 'MESCYT', '', 'olguitapg@gmail.com', 'QR-0380', 'CU'),
       ('José David', 'Arias Rosa', 'PUCMM', '', 'jdar0002@ce.pucmm.edu.do', 'QR-0381', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Robert', 'Naveo Hernandez', 'PUCMM', '', 'rxnh0001@ce.pucmm.edu.do', 'QR-0382', 'DO'),
       ('María Del Pilar', 'Álvarez Martín', 'PUCMM', '', 'md.alvarez@ce.pucmm.edu.do', 'QR-0383', 'DO'),
       ('Esteban Junior', 'Rodriguez Arias', 'PUCMM', '', 'ejra0002@ce.pucmm.edu.do', 'QR-0384', 'DO'),
       ('Crismeiry Rosalía', 'Fortuna Rivera', 'PUCMM', '', 'crfr0001@ce.pucmm.edu.do', 'QR-0385', 'DO'),
       ('Luz Vimeiry', 'Gómez De Peña', 'PUCMM', '', 'lvgd0001@ce.pucmm.edu.do', 'QR-0386', 'DO'),
       ('Genesis', 'Ramirez', 'PUCMM', '', 'gxrx0002@ce.pucmm.edu.do', 'QR-0387', 'DO'),
       ('Freddy Nicolás', 'Saviñón Peralta', 'PUCMM', '', 'fnsp0001@ce.pucmm.edu.do', 'QR-0388', 'DO'),
       ('Julissa', 'Peña Mercedes', 'PUCMM', '', 'jxpm0004@ce.pucmm.edu.do', 'QR-0389', 'DO'),
       ('María Isabel', 'Agustín Ramos', 'PUCMM', '', 'miar0001@ce.pucmm.edu.do', 'QR-0390', 'DO'),
       ('Angel Manuel', 'Ortiz Montas', 'PUCMM', '', 'amom0002@ce.pucmm.edu.do', 'QR-0391', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Maria Dolores', 'Then Alvarado', 'UCNE', '', 'morynathen@gmail.com', 'QR-0392', 'DO'),
       ('Elidania', 'Moreta Matías', 'PUCMM', '', 'exmm0007@ce.pucmm.edu.do', 'QR-0393', 'DO'),
       ('Lázaro', 'Pérez', 'UNISA', '', 'lperez@isa.edu.do', 'QR-0394', 'CU'),
       ('Paola', 'Hidalgo Vargas', 'PUCMM', '', 'nphv0001@ce.pucmm.edu.do', 'QR-0395', 'DO'),
       ('Aselys Lisbeth', 'Lora Rodríguez', 'PUCMM', '', 'allr0002@ce.pucmm.edu.do', 'QR-0396', 'DO'),
       ('Neel Lobatchewski', 'Báez Ureña', 'UASD', '', 'nbaez18@uasd.edu.do', 'QR-0397', 'DO'),
       ('Wilmary', 'Gómez Soto', 'PUCMM', '', 'wxgs0002@ce.pucmm.edu.do', 'QR-0398', 'DO'),
       ('Gloria Estefani', 'Morel Brito', 'PUCMM', '', 'gemb0002@ce.pucmm.edu', 'QR-0399', 'DO'),
       ('Máxima', 'Méndez Rosa', 'ISA', '', 'mmendez@isa.edu.do', 'QR-0400', 'DO'),
       ('Miranda Elena', 'Lebron De Los Santos', 'PUCMM', '', 'meld0002@ce.pucmm.edu.do', 'QR-0401', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Andy Gabriel', 'Tavarez Tejada', 'PUCMM', '', 'andygt1822@gmail.com', 'QR-0402', 'DO'),
       ('Girbelis', 'Guante Terrero', 'PUCMM', '', 'gxgt0001@ce.pucmm.edu.do', 'QR-0403', 'DO'),
       ('Laura Gabriela', 'Alvarez Paniagua', 'PUCMM', '', 'ga719953@gmail.com', 'QR-0404', 'DO'),
       ('Michael Jefree', 'Manzanillo Jiménez', 'PUCMM', '', 'mjmj0001@ce.pucmm.edu.do', 'QR-0405', 'DO'),
       ('Ana Mercedes', 'Báez', 'ISA', '', 'abaez@isa.edu.do', 'QR-0406', 'DO'),
       ('Leanny Elizabeth', 'De Los Santos Toledo', 'PUCMM', '', 'ledt0002@ce.pucmm.edu.do', 'QR-0407', 'DO'),
       ('Jaroly', 'Méndez Subervi', 'PUCMM', '', 'jxms0005@ce.pucmm.edu.do', 'QR-0408', 'DO'),
       ('Zaida Altagracia', 'De Jesús Guzmán', 'INTEC', '', 'zaida.dejesus@intec.edu.do', 'QR-0409', 'DO'),
       ('Wander Francisco', 'Lara Medina', 'PUCMM', '', 'wflm0001@ce.pucmm.edu.do', 'QR-0410', 'DO'),
       ('Denzel Johan', 'Martínez Herrera', 'PUCMM', '', 'djmh0001@ce.pucmm.edu.do', 'QR-0411', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Disneyri', 'Juliao Espinosa', 'PUCMM', '', 'disneyrijuliaoespinosa@gmail.com', 'QR-0412', 'DO'),
       ('Yajaira', 'Manzueta Manzueta', 'PUCMM', '', 'yxmm0003@ce.pucmm.edu.do', 'QR-0413', 'DO'),
       ('Manueliza', 'Rodriguez Encarnación', 'PUCMM', '', 'mxre0002@ce.pucmm.edu.do', 'QR-0414', 'DO'),
       ('Rosely', 'Meran Ramirez', 'PUCMM', '', 'larossi0417@gmail.com', 'QR-0415', 'DO'),
       ('Carlos Adrián', 'Genao Marcelino', 'PUCMM', '', 'cagm0003@ce.pucmm.edu.do', 'QR-0417', 'DO'),
       ('Edgar', 'Garcia', 'PUCMM', '', 'edgar_deni@outlook.com', 'QR-0418', 'DO'),
       ('Emely Esmeralda', 'De La Rosa Del Rosario', 'PUCMM', '', 'eedd0001@ce.pucmm.edu.do', 'QR-0419', 'DO'),
       ('Stephany', 'Quevedo Cortorreal', 'PUCMM', '', 'stephanyquevedo45@gmail.com', 'QR-0420', 'DO'),
       ('Perla Maciel', 'Lape', 'PUCMM', '', '20186419@ce.pucmm.edu.do', 'QR-0421', 'DO'),
       ('Corina', 'Tejada Polanco', 'UASD', '', 'ctejada40@uasd.edu.do', 'QR-0422', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Edrax Joaquín', 'Tineo', 'UTESA', '', 'edrax1979@gmail.com', 'QR-0423', 'DO'),
       ('Luis Daniel', 'Batista Miranda', 'PUCMM', '', 'ldbm0002@ce.pucmm.edu.do', 'QR-0424', 'DO'),
       ('Rommel Montgomery', 'Rodriguez Chireno', 'UTESA', '', 'rommelrodriguez@docente.utesa.edu', 'QR-0425', 'DO'),
       ('Jesuanny', 'Muñoz Geraldo', 'PUCMM', '', 'jxmg0001@ce.pucmm.edu.do', 'QR-0426', 'DO'),
       ('Sahira', 'Medina Ramírez', 'PUCMM', '', '20186370@ce.pucmm.edu.do', 'QR-0427', 'DO'),
       ('Ángel Pablo', 'Castillo Guillén', 'Externo', '', 'angelpablocastilloguillen@gmail.com', 'QR-0428', 'DO'),
       ('Yolaisy', 'Carmona Díaz', 'PUCMM', '', '20186422@ce.pucmm.edu.do', 'QR-0429', 'DO'),
       ('Abel Alejandro', 'Peña Madera', 'PUCMM', '', 'abel.pena.madera@gmail.com', 'QR-0430', 'DO'),
       ('Gabriell Elias', 'Rosado Ruiz', 'PUCMM', '', 'gerr0001@ce.pucmm.edu.do', 'QR-0431', 'DO'),
       ('Sonnia Quisqueya', 'Méndez Matos', 'Externo', '', 'soquime21@hotmail.com', 'QR-0432', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Willy Daniel', 'Rivera Cuevas', 'PUCMM', '', 'wdrc0001@ce.pucmm.edu.do', 'QR-0433', 'DO'),
       ('Luz Isaris', 'De La Rosa Sanchez', 'PUCMM', '', 'lids0001@ce.pucmm.edu.do', 'QR-0434', 'DO'),
       ('Claudia Jisela', 'Dorantes Villa', 'IPN', '', 'cjdorante@outlook.com', 'QR-0435', 'MX'),
       ('Luis David', 'Ricardo Pineda', 'PUCMM', '', 'ldrp0001@ce.pucmm.edu.do', 'QR-0436', 'DO'),
       ('Karianny', 'Guerrero Sánchez', 'PUCMM', '', '20176435@ce.pucmm.edu.do', 'QR-0437', 'DO'),
       ('Gregori José', 'Pinales Lorenzo', 'PUCMM', '', 'gjpl0001@ce.pucmm.edu.do', 'QR-0438', 'DO'),
       ('Bárbara', 'Campos Guzmán', 'PUCMM', '', 'licenciadacampos@hotmail.com', 'QR-0439', 'DO'),
       ('Janie Elizabeth', 'Santana Ramírez', 'PUCMM', '', 'jesr0001@ce.pucmm.edu.do', 'QR-0440', 'DO'),
       ('José Leocadio', 'Rodríguez Toribio', 'UASD', '', 'josedzes@hotmail.com', 'QR-0441', 'DO'),
       ('Betina', 'Duarte', 'UNIPE', '', 'betina.duarte@gmail.com', 'QR-0442', 'AR');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Leonte', 'Ramirez', 'UASD', '', 'leontera.ramirez@gmail.com', 'QR-0443', 'DO'),
       ('Gaviana Mabel', 'Borge Montilla', 'Instituto 512', '', 'gaviana.borge@512.com.do', 'QR-0444', 'DO'),
       ('Jonathan', 'Toribio Toribio', 'MINERD', '', 'jonathan.toribio@minerd.gob.do', 'QR-0445', 'DO'),
       ('Alberto Mahavir', 'Zapata Gómez', 'PUCMM', '', 'albertozapata0925@gmail.com', 'QR-0446', 'DO'),
       ('Silverio', 'Pérez García', 'MINERD', '', 'silverio.perez@minerd.gob.do', 'QR-0447', 'DO'),
       ('Víctor Manuel', 'Féliz Méndez', 'MINERD', '', 'victor.feliuz@minerd.gob.do', 'QR-0448', 'DO'),
       ('Paco', 'Castillo', 'MINERD', '', 'paco.castillo@minerd.gob.do', 'QR-0449', 'DO'),
       ('Rudy M.', 'López Matos', 'MINERD', '', 'rudi.lopez@minerd.gob.do', 'QR-0450', 'DO'),
       ('Jhonny', 'Perez Alcantara', 'MINERD', '', 'jhonny.perez@minerd.gob.do', 'QR-0451', 'DO'),
       ('Dionisio', 'Portes Moreta', 'MINERD', '', 'dionisio.portes@minerd.gob.do', 'QR-0452', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Kendall', 'Valdez Jaquez', 'MINERD', '', 'kendall.valdez@minerd.gob.do', 'QR-0453', 'DO'),
       ('María Mercedes', 'Cano', 'MINERD', '', 'mariamercedesc72@gmail.com', 'QR-0454', 'DO'),
       ('Angela', 'De Leon Ogando', 'MINERD', '', 'angela.deleon@minerd.gob.do', 'QR-0455', 'DO'),
       ('Carlos', 'Sanchez Marquez', 'MINERD', '', 'iancasama@gmail.com', 'QR-0456', 'DO'),
       ('Santo Franco', 'Bautista', 'MINERD', '', 'santo.franco@minerd.gob.do', 'QR-0457', 'DO'),
       ('Antonio', 'De Los Santos', 'MINERD', '', 'kataleyavasquez987@gmail.com', 'QR-0458', 'DO'),
       ('Gerobal', 'Tejeda', 'MINERD', '', 'gerobaltejeda@gmail.com', 'QR-0459', 'DO'),
       ('Arianna', 'Corporán Montero', 'IDEICE', '', 'ariannacorporanmontero@gmail.com', 'QR-0460', 'DO'),
       ('Joseph Davitte', 'Morrison Brito', 'IDEICE', '', 'josephmorrisonpga@gmail.com', 'QR-0461', 'DO'),
       ('Ivan', 'Leger', 'MINERD', '', 'ivanleger2103@gmail.com', 'QR-0462', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Luis Ariel', 'Acosta Rodríguez', 'IDEICE', '', 'luisarielrey23@gmail.com', 'QR-0463', 'DO'),
       ('Adriano', 'Angustia', 'MINERD', '', 'elastro3000@gmail.com', 'QR-0464', 'DO'),
       ('Yilenny Isabel', 'Sosa Santos', 'IDEICE', '', 'sosayilenny@gmail.com', 'QR-0465', 'DO'),
       ('Samuel', 'Perez', 'MINERD', '', 'samuelpvizcaino565@gmail.com', 'QR-0466', 'DO'),
       ('Erika', 'Arias', 'IDEICE', '', 'erikaariasblanco17@gmail.com', 'QR-0467', 'DO'),
       ('Miguel Onelio', 'De La Rosa', 'MINERD', '', 'miguel.delarosa@minerd.gob.do', 'QR-0468', 'DO'),
       ('Orquídea', 'Acevedo', 'IDEICE', '', 'orquideacvd2026@gmail.com', 'QR-0469', 'DO'),
       ('Angela', 'Chalas', 'MINERD', '', 'angelachalasb@gmail.com', 'QR-0470', 'DO'),
       ('Miguelina Elizabeth', 'Sirí Cabrera', 'IDEICE', '', 'elysirenita@gmail.com', 'QR-0471', 'DO'),
       ('Eduardo', 'Minaya', 'MINERD', '', 'eduardo.minaya@minerd.gob.do', 'QR-0472', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Eduardo', 'Mendez', 'MINERD', '', 'mendezedward95@gmail.com', 'QR-0473', 'DO'),
       ('Enmanuel De Jesús', 'Rodríguez Vargas', 'IDEICE', '', 'enmanuelbonifacio9@gmail.com', 'QR-0474', 'DO'),
       ('Nestor', 'Montero', 'MINERD', '', 'nestor.montero@minerd.gob.do', 'QR-0475', 'DO'),
       ('Joel Miguel', 'Corona Rodríguez', 'IDEICE', '', 'joelcorona_01@hotmail.com', 'QR-0476', 'DO'),
       ('Leonardo Ariel', 'Muñoz', 'IDEICE', '', 'leonardoariel749@gmail.com', 'QR-0477', 'DO'),
       ('Laidys Ámbar', 'Jiménez Bernard', 'IDEICE', '', 'ambarfj1728@gmail.com', 'QR-0478', 'DO'),
       ('Ismely Miguelina', 'Abreu Ventura', 'IDEICE', '', 'lamaestraismely@gmail.com', 'QR-0479', 'DO'),
       ('Katherine', 'Matos Valdez', 'IDEICE', '', 'maestrakatherinemv@gmail.com', 'QR-0480', 'DO'),
       ('Jesus', 'Valdez Cabrera', 'MINERD', '', 'jesus031385@outlook.com', 'QR-0481', 'DO'),
       ('Andrés Gabriel', 'Silverio Vásquez', 'IDEICE', '', 'andresgabrielsilveriovasquez@gmail.com', 'QR-0482', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Yeuris', 'Sueares', 'MINERD', '', 'yeuris.suarez@minerd.gob.do', 'QR-0483', 'DO'),
       ('Jennifer', 'Cid Reyes', 'IDEICE', '', 'jennifer.cid@rdmescyt.edu.do', 'QR-0484', 'DO'),
       ('Juan Orlando', 'Cueto Santos', 'IDEICE', '', 'juan.cueto@minerd.gob.do', 'QR-0485', 'DO'),
       ('Anderzon', 'Araujo', 'MINERD', '', 'anderzon.moreno@minerd.gob.do', 'QR-0486', 'DO'),
       ('Yasmiris Daiana', 'Calvo Volquez', 'MINERD', '', 'daianaclv@gmail.com', 'QR-0487', 'DO'),
       ('Linosca Dominga', 'Ulloa Rosario', 'IDEICE', '', 'inc_girl@hotmail.com', 'QR-0488', 'DO'),
       ('Elizabeth', 'Michel Mustafa', 'MINERD', '', 'tecnicomustafa@gmail.com', 'QR-0489', 'DO'),
       ('Jawal', 'Berihuete De Los Santos', 'MINERD', '', 'reynacrystal2412@gmail.com', 'QR-0490', 'DO'),
       ('Libeth Dilone', 'López', 'IDEICE', '', 'libethdilonelopez1991@gmail.com', 'QR-0491', 'DO'),
       ('Crisanta', 'Rodríguez', 'MINERD', '', 'crisantar79@gmail.com', 'QR-0492', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Mariano', 'Agramonte', 'MINERD', '', 'marianoagramonte1592@gmail.com', 'QR-0494', 'DO'),
       ('Maribel', 'Galvá Montero', 'MINERD', '', 'maribel.galva@minerd.gob.do', 'QR-0495', 'DO'),
       ('Anderzon', 'Araujo', 'MINERD', '', 'anderzon.moreno@minerd.do.gob', 'QR-0496', 'DO'),
       ('Juana Esther', 'Ureña Cortorreal  De Nuñez', 'IDEICE', '', 'juana.urenac@minerd.gob.do', 'QR-0497', 'DO'),
       ('Victor Alfonso', 'García Aracena', 'MINERD', '', 'profesormatvictorgarcia@gmail.com', 'QR-0498', 'DO'),
       ('Cristòbal', 'Peralta', 'MINERD', '', 'cristobal.peralta@minerd.gob.do', 'QR-0499', 'DO'),
       ('Víctor Roldan', 'Núñez Vásquez', 'IDEICE', '', 'victor.nunez@minerd.gob.do', 'QR-0500', 'DO'),
       ('Altagracia Nais', 'Pérez', 'MINERD', '', 'altagracianais27@gmail.com', 'QR-0501', 'DO'),
       ('Claribel', 'Hernández Dipré', 'MINERD', '', 'claribelhd2980@gmail.com', 'QR-0502', 'DO'),
       ('Wendy Altagracia', 'Mejía Aybar', 'MINERD', '', 'wendy.mejia@minerd.gob.do', 'QR-0503', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Gretty Maria  Tavarez  Perez', 'Tavarez  Perez', 'MINERD', '', 'gretty.tavarez@minerd.gob.do', 'QR-0504',
        'DO'),
       ('Patricia', 'Maríano', 'MINERD', '', 'roseiri1096@gmail.com', 'QR-0505', 'DO'),
       ('María Del Carmen', 'Suero Suero', 'IDEICE', '', 'elizabethmichelmustafa@gmail.com', 'QR-0506', 'DO'),
       ('Luis Humberto', 'Uribe Díaz', 'MINERD', '', 'humbertouribe653@gmail.com', 'QR-0507', 'DO'),
       ('Miselanea', 'Pérez Gómez', 'MINERD', '', 'miselania.perezgo@minerd.gob.do', 'QR-0508', 'DO'),
       ('Yesenia Maribel', 'Santamaría Leyba', 'MINERD', '', 'yesenia.santa@minerd.gob.do', 'QR-0509', 'DO'),
       ('José Manuel', 'Veloz', 'MINERD', '', 'jomavegar@gmail.com', 'QR-0510', 'DO'),
       ('Francoise Bárbara', 'Molina Vazquez', 'MINERD', '', 'francoisemolina27@gmail.com', 'QR-0511', 'DO'),
       ('Ashley', 'Gutierrez', 'IDEICE', '', 'ashley.gutierrez@ideice.gob.do', 'QR-0512', 'DO'),
       ('Mariela', 'Encarnación', 'IDEICE', '', 'marielaencarnacion23@gmail.com', 'QR-0513', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Sarah Esther', 'Calderón De Coronado', 'MINERD', '', 'sarah2027c@gmail.com', 'QR-0514', 'DO'),
       ('Ibelise', 'García Contreras', 'MINERD', '', 'ibelisegarciacontreras@gmail.com', 'QR-0515', 'DO'),
       ('Julio César', 'Díaz Cabrera', 'MINERD', '', 'juliodc3838@gmail.com', 'QR-0516', 'DO'),
       ('Luisa', 'Samboy', 'MINERD', '', 'laminisamboy@gmail.com', 'QR-0517', 'DO'),
       ('Jawer Raulin', 'Encarnación De Óleo', 'MINERD', '', 'jawered2092@gmail.com', 'QR-0518', 'DO'),
       ('José David', 'Francisco', 'MINERD', '', 'jose.franciscom@minerd.gob.do', 'QR-0519', 'DO'),
       ('Sheila Elizabeth', 'De La Rosa Silvestre', 'MINERD', '', 'silvestresheila2@gmail.com', 'QR-0520', 'DO'),
       ('Claudel Santiago', 'Santana Camacho', 'MINERD', '', 'cssc1021@gmail.com', 'QR-0521', 'DO'),
       ('Jahaner Antonio', 'Sosa Silvestres', 'MINERD', '', 'jahaner.sosa@minerd.gob.do', 'QR-0522', 'DO'),
       ('Gregorina', 'Deprats Peña', 'MINERD', '', 'depratsgrego@gmail.com', 'QR-0523', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Wendy Carolina', 'Carolina Hernàndez', 'MINERD', '', 'wencar895@gmail.com', 'QR-0524', 'DO'),
       ('Angie Carolina', 'De Los Santos Reyes', 'MINERD', '', 'angiedelossantos22@gmail.com', 'QR-0525', 'DO'),
       ('Carlos David', 'Vargas González', 'MINERD', '', 'carloesdavid@gmail.com', 'QR-0526', 'DO'),
       ('Cristian Martin', 'Medina Ferreras', 'MINERD', '', 'cristian.medina@minerd.gob.do', 'QR-0527', 'DO'),
       ('Juana Odalys', 'Caraballo De León', 'MINERD', '', 'juana.caraballo@minerd.gob.do', 'QR-0528', 'DO'),
       ('Yobanes', 'Cabrera De La Rosa', 'MINERD', '', 'segundinooperaciones@gmail.com', 'QR-0529', 'DO'),
       ('Luis Ramón', 'M. García De La Cruz', 'MINERD', '', 'luisgarcia73@hotmail.com', 'QR-0530', 'DO'),
       ('Diana Carolina', 'Vélez Pantaleon', 'MINERD', '', 'dianavelezp@hotmail.com', 'QR-0531', 'DO'),
       ('Marvin Diaz', 'Mendez', 'MINERD', '', 'marvin.diaz@minerd.gob.do', 'QR-0532', 'DO'),
       ('Daysi Paola', 'Nuñez', 'MINERD', '', 'dpnunezm@gmail.com', 'QR-0533', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Perla Nicol', 'Soriano Perez', 'MINERD', '', 'perlasoriano24@gmail.com', 'QR-0534', 'DO'),
       ('Gemimax', 'Anderson Pook', 'MINERD', '', 'gemimaxpool@gmail.com', 'QR-0535', 'DO'),
       ('Tania Beatriz', 'Cordero Javier', 'MINERD', '', 'taniacordero1723@gmail.com', 'QR-0536', 'DO'),
       ('Israely', 'Kaide Placencio', 'MINERD', '', 'israely.placencio@minerd.gob.do', 'QR-0537', 'DO'),
       ('Berkis', 'De La Cruz Belen', 'MINERD', '', 'belkisdelacruzbelen80@gmail.com', 'QR-0538', 'DO'),
       ('Kelly Altagracia', 'Báez Sosa', 'MINERD', '', 'kellybaezsosa04@gmail.com', 'QR-0539', 'DO'),
       ('Sandra A.', 'Peña Matos', 'MINERD', '', 'lic.sandramatos@gmail.com', 'QR-0540', 'DO'),
       ('Yugelis', 'De La Rosa Mendez', 'MINERD', '', 'yugelis.delarosa@minerd.gob.do', 'QR-0541', 'DO'),
       ('Onesimo', 'Valenzuela De Los Santos', 'MINERD', '', 'onesimoacademico@gmail.com', 'QR-0542', 'DO'),
       ('Rosa Esther', 'Pierre', 'MINERD', '', 'proferosapierre@gmail.com', 'QR-0543', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Nelson', 'Ortiz Pascual', 'MINERD', '', 'nelson.ortizpa@minerd.gob.do', 'QR-0544', 'DO'),
       ('Aury Rafael', 'Pérez Cuevas', 'MINERD', '', 'aury.perez@minerd.gob.do', 'QR-0545', 'DO'),
       ('Katherine Anyeline', 'Sánchez', 'MINERD', '', 'licdasanchezmate@gmail.com', 'QR-0546', 'DO'),
       ('Roberto', 'Lantigua Sánchez', 'MINERD', '', 'lantigua29@hotmail.com', 'QR-0547', 'DO'),
       ('Silsi Maria', 'Ortiz Albuez', 'MINERD', '', 'silsi.ortiz@minerd.gob.do', 'QR-0548', 'DO'),
       ('Marinelys', 'Peguero', 'MINERD', '', 'marinelyspeguero383@gmail.com', 'QR-0549', 'DO'),
       ('Geovanny Arturo', 'Lachapell Maldonado', 'MINERD', '', 'geovanny.lachapell@minerd.gob.do', 'QR-0550', 'DO'),
       ('Hilda Nohely De La Cruz Morel', 'Hilda Nohely De La Cruz Morel', 'MINERD', '', 'hilda.delacruz@minerd.gob.do',
        'QR-0551', 'DO'),
       ('Ninoska', 'Torres De La Guarda', 'MINERD', '', 'ninoska.torres@minerd.gob.do', 'QR-0552', 'DO'),
       ('Stephany', 'Gil Sanchez', 'MINERD', '', 'stephanygilsanchez@gmail.com', 'QR-0553', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Esbelin Altagracia', 'Pérez Mora', 'MINERD', '', 'esbelynperz26@gmail.com', 'QR-0554', 'DO'),
       ('Germania', 'Jiménez Sánchez', 'Externo', '', 'germania.jimenez@minerd.gob.do', 'QR-0555', 'DO'),
       ('Juan', 'Manzueta Mendez', 'MINERD', '', 'juanmaz1983@gmail.com', 'QR-0557', 'DO'),
       ('Delvi Antonio', 'Polanco Adames', 'MINERD', '', 'delvi.polancoad@minerd.gob.do', 'QR-0558', 'DO'),
       ('Ángel Manuel', 'Díaz González', 'MINERD', '', 'angel.diazgo@minerd.gob.do', 'QR-0559', 'DO'),
       ('Imenia Mercedes', 'Sabino', 'MINERD', '', 'imenia.sabino@minerd.gob.do', 'QR-0560', 'DO'),
       ('César Abel', 'Santil Glass', 'MINERD', '', 'cesar.santil@minerd.gob.do', 'QR-0561', 'DO'),
       ('Andy José', 'Rivas Moreno', 'MINERD', '', 'andyrivas45@gmail.com', 'QR-0562', 'DO'),
       ('Anny', 'Del Valle Zarzuela', 'MINERD', '', 'anny.delvalle@minerd.gob.do', 'QR-0563', 'DO'),
       ('Iris Josefa', 'Mendez Lopez', 'MINERD', '', 'irismendezlopez15@gmail.com', 'QR-0564', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Adriana', 'Gonzalez', 'MINERD', '', 'adriana.gonzalez@minerd.gob.do', 'QR-0565', 'DO'),
       ('Luz María', 'Rodríguez De Aza', 'MINERD', '', 'luz.rodriguez@minerd.gob.do', 'QR-0566', 'DO'),
       ('Elizabeth', 'Adames', 'MINERD', '', 'eadamesa1@gmail.com', 'QR-0567', 'DO'),
       ('Cecilia Marleny', 'Mambrú', 'MINERD', '', 'katy.duran@minerd.gob.do', 'QR-0568', 'DO'),
       ('Pascual Ovidio', 'Hernández Payano', 'MINERD', '', 'pascual112783@gmail.com', 'QR-0569', 'DO'),
       ('Yoandri', 'Romano', 'MINERD', '', 'sofonias_hageos@hotmail.com', 'QR-0570', 'DO'),
       ('Teresa De Jesus', 'Lima De Santana', 'MINERD', '', 'coordinadorateresalima01@gmail.com', 'QR-0571', 'DO'),
       ('Roberto', 'Mejía', 'MINERD', '', 'md07roberto@gmail.com', 'QR-0572', 'DO'),
       ('Miancer David', 'Rubio Abreu', 'MINERD', '', 'miancer.rubio@minerd.gob.do', 'QR-0573', 'DO'),
       ('Mirlandy', 'Bautista García', 'MINERD', '', 'bmirlandy@gmail.com', 'QR-0574', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Elizabeth', 'Figueroa', 'MINERD', '', 'elizabeth.figueroa@minerd.gob.do', 'QR-0575', 'DO'),
       ('Cirilo', 'Peña Gonzalez', 'MINERD', '', 'cirilopenagonzalez@gmail.com', 'QR-0576', 'DO'),
       ('Esther Judith', 'Núñez Ureña', 'MINERD', '', 'esther.figueroa@minerd.gob.do', 'QR-0577', 'DO'),
       ('Santa Gribel', 'Azor King', 'MINERD', '', 'santa.azor@minerd.gob.do', 'QR-0578', 'DO'),
       ('Rossy Danny', 'Reyes Gonzalez', 'MINERD', '', 'rossyreyes6@gmail.com', 'QR-0579', 'DO'),
       ('Argenis Elpidio López Stubbs', 'López Stubbs', 'MINERD', '', 'argenis.lopez@minerd.gob.do', 'QR-0580', 'DO'),
       ('Sobeida Antonia', 'Nuñez', 'MINERD', '', 'sobeida.nunez@minerd.gob.do', 'QR-0581', 'DO'),
       ('Francheska', 'Rodríguez Santana', 'MINERD', '', 'franches2800@gmail.com', 'QR-0582', 'DO'),
       ('Edwin William', 'Ortiz Pimentel', 'MINERD', '', 'edwin.ortiz@minerd.gob.do', 'QR-0583', 'DO'),
       ('Yetcenia Licett', 'Pérez', 'MINERD', '', 'yetcenia.diaz@minerd.gob.do', 'QR-0584', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Yaneris', 'Polanco Rosario', 'MINERD', '', 'yanerispolqnco14@gmail.com', 'QR-0585', 'DO'),
       ('Jocelyn Pierre', 'Louis Vilmeney', 'MINERD', '', 'jocelyn.pierrelouis@docente.edu.do', 'QR-0586', 'DO'),
       ('Saghasiehany', 'De Jesús Bencosme', 'MINERD', '', 'saghasiehany.dejesus@minerd.gob.do', 'QR-0587', 'DO'),
       ('Juan Ariel', 'De Los Santos Arcángel', 'MINERD', '', 'ariel24141002@gmail.com', 'QR-0588', 'DO'),
       ('Reina María', 'Cuevas Peña', 'MINERD', '', 'reina.cuevas@minerd.gob.do', 'QR-0589', 'DO'),
       ('Rosanna Mártires', 'Zapata Casado', 'MINERD', '', 'rosanna.zapata@minerd.gob.do', 'QR-0590', 'DO'),
       ('Aneudy', 'Minier', 'MINERD', '', 'aneudy.minier@minerd.gob.do', 'QR-0591', 'DO'),
       ('Ramón Bienvenido', 'De La Cruz Marte', 'MINERD', '', 'ramonb38@hotmail.com', 'QR-0592', 'DO'),
       ('Teudis', 'Santana Meran', 'MINERD', '', 'teudisantanameran@gmail.com', 'QR-0593', 'DO'),
       ('Andrea Dipré', 'Jiménez', 'MINERD', '', 'andrea.dipre@minerd.gob.do', 'QR-0594', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Jorge Guillermo', 'Jabalera  Bastardo', 'MINERD', '', 'jorge.jabalera@minerd.gob.do', 'QR-0595', 'DO'),
       ('Yordalisa', 'Del Rosario De Los Santos', 'MINERD', '', 'yorda147delrosario@gmail.com', 'QR-0596', 'DO'),
       ('Freisy Elisa', 'Cabrera Tejeda', 'MINERD', '', 'freisytejeda@gmail.com', 'QR-0597', 'DO'),
       ('Nereyda Julan', 'Ovilsano', 'MINERD', '', 'nereyda.julian@minerd.gob.do', 'QR-0598', 'DO'),
       ('Bienvenida', 'Urbaez', 'MINERD', '', 'bienbaurbaez@hotmail.com', 'QR-0599', 'DO'),
       ('Ambar Larimar', 'Pinales De La Cruz', 'MINERD', '', 'ambarpinales@gmail.com', 'QR-0600', 'DO'),
       ('Otto Manuel', 'Pérez', 'MINERD', '', 'ottoperez2610@gmail.com', 'QR-0601', 'DO'),
       ('Yojana', 'Rivera Disla', 'MINERD', '', 'yojanariveradisla@gmail.com', 'QR-0602', 'DO'),
       ('Hanser', 'Peña Gonzalez', 'MINERD', '', 'hanser.pena@minerd.gob.do', 'QR-0603', 'DO'),
       ('Biarcy De Jesús', 'Franco Cuello', 'MINERD', '', 'biarcy-jima@hotmail.com', 'QR-0604', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Ana Mercedes', 'Candelario Solano', 'MINERD', '', 'ana.candelario@minerd.gob.do', 'QR-0605', 'DO'),
       ('Martín', 'García Olivo', 'MINERD', '', 'martin.garcia@minerd.gob.do', 'QR-0606', 'DO'),
       ('Nilsi Nikaury', 'Pichardo Devora', 'MINERD', '', 'nilsi.pichardo@minerd.gob.do', 'QR-0607', 'DO'),
       ('Ramon Alexis', 'Moreno De Los Santos', 'MINERD', '', 'alexismoreno1001@gmail.com', 'QR-0608', 'DO'),
       ('Eudy Margarita', 'Lebrón Fernández', 'MINERD', '', 'almanicole0605@gmail.com', 'QR-0609', 'DO'),
       ('Yvelise', 'De Jesús Silverio', 'MINERD', '', 'yvelisedejesussilverio@gmail.com', 'QR-0610', 'DO'),
       ('Santos', 'Concepción Fernández', 'MINERD', '', 'santos.concepcionfe@minerd.gob.do', 'QR-0611', 'DO'),
       ('Joselyn', 'De Jesús Collado', 'MINERD', '', 'joselyncollado01@gmail.com', 'QR-0612', 'DO'),
       ('Francisca Altagracia', 'Morrobel Arias', 'MINERD', '', 'famniarias2282@gmail.com', 'QR-0613', 'DO'),
       ('Edwin Abad Núñez Díaz', 'Edwin Abad Núñez Díaz', 'MINERD', '', 'edwinabadnunezdia@gmail.com', 'QR-0614', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Lenny Amado', 'González Cruz', 'MINERD', '', 'lic.lennygonzalez@gmail.com', 'QR-0615', 'DO'),
       ('José Israel', 'González Geraldino', 'MINERD', '', 'geraldino33@gmail.com', 'QR-0616', 'DO'),
       ('Maderlyn', 'Silverio Hurtado', 'MINERD', '', 'maderlynsh@gmail.com', 'QR-0617', 'DO'),
       ('Frankely', 'Escolastico Robles', 'MINERD', '', 'frankely.escolastico@docente.edu.do', 'QR-0618', 'DO'),
       ('Jhoselyn', 'Adames Adames', 'MINERD', '', 'jhoselyn.adames@minerd.gob.do', 'QR-0619', 'DO'),
       ('Maryuri', 'Rodriguez', 'MINERD', '', 'mariajavier497@gmail.com', 'QR-0620', 'DO'),
       ('Luis Daniel', 'Cea Sosa', 'MINERD', '', 'luisdanielsea95@gmail.com', 'QR-0621', 'DO'),
       ('Ana Josefina', 'Castillo Canejeter', 'MINERD', '', 'anacanejeter16@gmail.com', 'QR-0622', 'DO'),
       ('Edilia', 'Florian Santana', 'MINERD', '', 'ediliaflorian08@gmail.com', 'QR-0623', 'DO'),
       ('Nidia Natasha', 'Agüero Paulino', 'MINERD', '', 'nidianatacha1@gmail.com', 'QR-0624', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Teresa Yocelyn', 'Matos Garcia', 'MINERD', '', 'teresamatos@cepmsd.edu.do', 'QR-0625', 'DO'),
       ('Nathael', 'Santana Redman', 'MINERD', '', 'nathael13@gmail.com', 'QR-0626', 'DO'),
       ('Anerfri', 'Lora Acosta', 'MINERD', '', 'anerfri06@gmail.com', 'QR-0627', 'DO'),
       ('Tirso Del Jesús', 'Figuereo Guerrero', 'MINERD', '', 'tirso.figuereo@docente.edu.do', 'QR-0628', 'DO'),
       ('Claudia Janet', 'Jiménez Peguerro', 'MINERD', '', 'jclaudiajanet@gmail.com', 'QR-0629', 'DO'),
       ('Lilian Amparo', 'Díaz Concepción', 'MINERD', '', 'lilianamparod90@gmail.com', 'QR-0630', 'DO'),
       ('Carlos Manuel', 'De La Cruz Suero', 'MINERD', '', 'carlosdelacruzsuero@gmail.com', 'QR-0631', 'DO'),
       ('Milvia', 'Roa Familia', 'MINERD', '', 'milvia.roa@minerd.gob.do', 'QR-0632', 'DO'),
       ('Junior', 'Rafael Rodriguez', 'MINERD', '', 'juniorr.rodriguez@minerd.gob.do', 'QR-0633', 'DO'),
       ('Jordy', 'Diaz Payano', 'MINERD', '', 'jordy.diazp@minerd.gob.do', 'QR-0634', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Josefa Andrea', 'Valdez Rijo', 'MINERD', '', 'ajosefa.valdez@minerd.gob.do', 'QR-0635', 'DO'),
       ('Danny Esteban', 'Ramírez Lobo', 'Universidad Nacional', '', 'danny.ramirez.lobo@una.cr', 'QR-0636', 'CR'),
       ('Cruz María', 'Santana Nieves', 'PUCMM', '', 'cruma03@gmail.com', 'QR-0637', 'DO'),
       ('Leonardo', 'Jiménez Flores', 'ADP', '', 'ljimenez@prof.unen.edu.do', 'QR-0638', 'DO'),
       ('Santo', 'Lauriano Martes', 'ADP', '', 'santolauriano@gmail.com', 'QR-0639', 'DO'),
       ('Silvanio', 'De Andrade', 'UEPB', '', 'silvanio@usp.br', 'QR-0640', 'BR'),
       ('Dolores Paola', 'Ramírez Mosquea', 'ADP', '', 'paolaramos1518@gmail.com', 'QR-0641', 'DO'),
       ('Yokasta Josefina', 'Javier Guzmán', 'ADP', '', 'yokastajavi@gmail.com', 'QR-0642', 'DO'),
       ('Eduardo', 'Sánchez Figuereo', 'MINERD', '', 'eduarch.96@gmail.com', 'QR-0643', 'DO'),
       ('Grisel Alejandra', 'Saturria De Fernández', 'ADP', '', 'griselalejandra1996@gmail.com', 'QR-0644', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Ana Iris', 'Calzado Cayetano', 'Externo', '', 'iriscayetano29@gmail.com', 'QR-0645', 'DO'),
       ('Naurael', 'Arias Ibert', 'Externo', '', 'naurael.ibert@gmail.com', 'QR-0646', 'DO'),
       ('Felipe Antonio', 'Valverde Reyes', 'ADP', '', 'wuelinto@gmail.com', 'QR-0647', 'DO'),
       ('Cristina', 'Lara Casilla', 'Externo', '', 'larac4415@mail.com', 'QR-0648', 'DO'),
       ('Alialys Josefina', 'Espinal Pérez', 'ADP', '', 'espinalalialys@gmail.com', 'QR-0649', 'DO'),
       ('Francis Gerardo', 'Ferreras Encarnación', 'Externo', '', 'francisgerardo05@gmail.com', 'QR-0650', 'DO'),
       ('Kelvin Polanco', 'Polanco Cepin', 'ADP', '', 'cepin0322@gmail.com', 'QR-0651', 'DO'),
       ('Celeste', 'Riveron Arias', 'Externo', '', 'celesteriveron18@gmail.com', 'QR-0652', 'DO'),
       ('Gaudy', 'Ovalle Capellan', 'O&M', '', 'gaudyovalles23@gmail.com', 'QR-0653', 'DO'),
       ('Pedro Julio', 'Alcántara De Los Santos', 'ISFODOSU', '', 'pedrojulioalcantara7@gmail.com', 'QR-0654', 'DO');
INSERT INTO attender (name, last_name, company, title, email, phone, country)
VALUES ('Yasmel', 'Ferreras Tineo', 'Externo', '', 'yasmelferreras0906@gmail.com', 'QR-0655', 'DO'),
       ('Januel Fernando', 'De La Cruz Rodríguez', 'ADP', '', 'djanuel9@gmail.com', 'QR-0656', 'DO'),
       ('Luis Alfredo', 'Morillo Arias', 'MINERD', '', 'alfredo.morillo96@gmail.com', 'QR-0657', 'DO'),
       ('Bárbara Inés', 'Peña Lebron', 'MINERD', '', 'barbarapena206@gmail.com', 'QR-0658', 'DO'),
       ('Rosa Aneris', 'Peña Batista', 'ADP', '', 'rosa.aneris1990@gmail.com', 'QR-0659', 'DO'),
       ('Ana Virginia', 'Bernart Rodriguez', 'ADP', '', 'anavbernart25@gmail.com', 'QR-0660', 'DO'),
       ('Jenny Abigail', 'Restituyo Jimenez', 'UCATECI', '', 'jrestituyo@ucateci.edu.do', 'QR-0662', 'DO'),
       ('Yomeiri', 'Buret De Los Santos', 'ADP', '', 'yomiburet19@gmail.com', 'QR-0663', 'DO'),
       ('Yubelkis', 'Rodríguez Hernández', 'ADP', '', 'licyubelkisrodriguezhernandez@gmail.com', 'QR-0664', 'DO'),
       ('Yotania', 'González Mañón', 'MINERD', '', 'gonzalez299074@gmail.com', 'QR-0665', 'DO');
